### ISSUE TITLE
Fabric Message is too large

### ISSUE THREAD

**Issue by shlatchz** [Azure/service-fabric-issues#1]
I'm trying to pass 5MB~ data from a service to an actor, and I'm getting the error:

>Fabric Message is too large

How can I increase the maximum size that can be transferred between micro-services?

I looked at the following [page][1] to see my options.

I tried setting:

    <Section Name="ServiceReplicatorConfig">
        ...
        <Parameter Name="MaxReplicationMessageSize" Value="1073741824" />
    </Section>
    
Please help.

  [1]: https://github.com/Azure/azure-content/blob/master/articles/service-fabric/service-fabric-reliable-actors-reliabledictionarystateprovider-configuration.md

**Comment by VipulM-MSFT** [comment]
The replication configuration is for the replicated messages, in order to set maximum size for the remoting transport, you can use the following attribute and place it on your actor interface assembly or configure the maximum message size in the ServiceProxyFactory and ServiceRemotingListener creation.

https://msdn.microsoft.com/en-us/library/azure/microsoft.servicefabric.actors.remoting.fabrictransport.fabrictransportactorremotingproviderattribute.aspx

**Comment by VipulM-MSFT** [comment]
The documentation for the base provider type describes how the attribute is looked up:

https://msdn.microsoft.com/en-us/library/azure/microsoft.servicefabric.actors.remoting.actorremotingproviderattribute.aspx

**Comment by shlatchz** [comment]
It didn't really work...
I've added

    [assembly: FabricTransportActorRemotingProvider(MaxMessageSize = 10485760)]

to the actor's interface and I still get the error.

**Comment by gc-hiten-soni** [comment]
Hi,

I am facing same issue of "Fabric Message is too large". However this is happening into Self hosted Web API in Service Fabric. Is there any way i can increase the limit for Stateless Web API?

Thanks,
Hiten

**Comment by vturecek** [comment]
Service Fabric doesn't limit message size for Web API. My guess is that it's coming from within your Web API service. Are you using ServiceProxy or ActorProxy in your Web API service?

**Comment by vturecek** [comment]
@shlatchz Make sure you add that attribute to both your actor service assembly **and** the assembly that's using ActorProxy to call your actors.

**Comment by gc-hiten-soni** [comment]
Hi vturecek,

I am using ServiceProxy in Web API Service.

**Comment by vturecek** [comment]
@gc-hiten-soni OK, so just make sure you set the max message size on **both** the service being called, **and** the client (the Web API service doing the calling).

The easiest way to set it is to use the assembly-wide attribute:

using Microsoft.ServiceFabric.Services.Remoting.FabricTransport;
[assembly: FabricTransportServiceRemotingProvider(MaxMessageSize = 134217728)]

Again make sure this is available in the assembly that is creating the service remoting listener **and** the assembly that is calling it with ServiceProxy.

Alternatively, you can set the max message size programmatically when you create the listener, or in a settings.xml config file. See here for more info on that: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-services-secure-communication/

**Comment by vturecek** [comment]
I verified that this works as expected, so I'm going to close this issue. If you still run into problems with message size in Service Remoting, please feel free to re-open this.

**Comment by Remy-Burney-Powerfront** [comment]
Hello,

Just want to share my config as well, as it took me a while to get this sorted as well.

First I tried the famous assembly tag that I saw a lot
`[assembly: FabricTransportActorRemotingProvider(MaxMessageSize = 1073741824)]`
but that just didn't work

So in the end I also used the doc https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-secure-communication as mentionned by @vturecek 

In the CreateServiceReplicaListeners method of my service, I've got 

```
protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
        {
            return new[]
            {
                new ServiceReplicaListener(this.CreateServiceRemotingListener)
            };
        }
```
and in the file Config/Settings.xml I have 
```
<Settings>
<Section Name="TransportSettings">
    <Parameter Name="MaxMessageSize" Value="1073741824" />
  </Section>
</Settings>
```
Just a note that the value 1073741824 and be parameterized from the ApplicationManifest.xml if needed so that you can control the limit depending on the Publish Profile you use.

**Comment by eugeneagafonov** [comment]
@Remy-Burney-Powerfront, @vturecek I also met this problem, and also cannot make the assembly attribute working. However, I use actors and I don't see where I can tweak its listener. I would appreciate any help a lot.
