### ISSUE TITLE
Service Fabric Errors in Event Viewer

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1005]
Team,

could you explain me and help me troubleshoot below errors in SF ?

i replaced ipaddress and port with ## below.

client-#####:### failed to bind to local port for connecting: 0x80072747

client-#####:### : cannot send, state = Closed, fault = 2147952455, dropping message {b0a079b1-2c28-4ae9-b549-ed54d7c9a285}:862014, Actor = NamingGateway, Action = 'PingRequest'

ImpersonateAndCopyFile for SourcePath:\\##########\131680066181846676\Release 2.0\131680065707109428_17179869184_653.ApplicationManifest.xml, DestinationPath:C:\ProgramData\SF\19VS\Fabric\work\Applications\__FabricSystem_App4294967295\work\Store\131680066181846675\Release 2.0\131680065707109428_17179869184_653.ApplicationManifest.xml failed: 0x80070035. Have tried all access tokens.

Thanks,
Naresh Khatri

**Comment by oanapl** [comment]
What prompted you to look at the event log? Is the cluster unhealthy? Is image store not working properly?
Many of the warnings you see in event log are transient and it's not worth spending too much time on them. Others are indicative of actual issues. 

For your specific ones:
Failed to bind to local port failed with 0x80072747, which means "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full." The ping request message fails because of this.

ImpersonateAndCopyFile warning tells you that the image store operation of copying ApplicationManifest file failed with 0x80070035, which is "The network path was not found." One reason for this would be that the node it tries to copy the file from went down, in which case it's transient. It can also mean more serious issues, but that's hard to tell from just one trace.

For the RAP warning you pasted above, you can see in SFX that the replica in question is in Warning state. The health report that it has on it will point you to [sfhealth](http://aka.ms/sfhealth), which has description about [why this warning may pop up and what to do about it](https://docs.microsoft.com/azure/service-fabric/service-fabric-understand-and-troubleshoot-with-system-health-reports#replica-system-health-reports).

**Comment by oanapl** [comment]
- What kind of cluster do you have - how many nodes, is it SFRP/on-prem? 
- What service fabric version do you have?
- What events are reported on image store service and its partition & replicas? Is the reconfig stuck event you pasted from image store or other service?
- Can you check that you have enough disk space on the VMs?

**Comment by nareshkhatri81** [comment]
Its onpremise cluster with 3 nodes.
There is one replicatorlog file with size of 8GB in SF log folder.
Is there way to limit SF replicator log size ?

**Comment by leikong** [comment]
0x80072747 usually meant that dynamic ports are depleted, either dynamic port range is too small, or there are too many sockets on the machine.
Dynamic TCP port range can be checked with "netsh int ipv4 show dynamicport tcp".
You can dump all sockets with "netstat -abno -p TCP"

**Comment by oanapl** [comment]
@nareshkhatri81 , take a look at https://github.com/Azure/service-fabric-issues/issues/138 for more about replicator log.
Can you check the dynamic ports as @leikong suggested?

**Comment by nareshkhatri81** [comment]
@leikong - How many dynamic ports we need ? is 256 sufficient
PS D:\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 20032
Number of Ports : 256

**Comment by nareshkhatri81** [comment]
It seems most of connection are for SF, docker and Redis.
is there any reason why SF doesnt close tcp connection or its relay on OS to close it ?

PS D:\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> (netstat -abno -p TCP | findstr Fabric).Count
176
PS D:\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> (netstat -abno -p TCP | findstr Docker).Count
0
PS D:\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> (netstat -abno -p TCP | findstr docker).Count
146
PS D:\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> (netstat -abno -p TCP | findstr redis).Count
79

Thanks,
Naresh Khatri

**Comment by leikong** [comment]
Service fabric uses persistent connections, we do not open and close connections for each message exchange. Please share the output from netstat if you want us to check if the connections mentioned above are legit.

**Comment by nareshkhatri81** [comment]
@leikong 
can you share your MS Email address ?
we can send you sharefile location.

Thanks,
Naresh Khatri

**Comment by leikong** [comment]
leikong@microsoft.com

**Comment by leikong** [comment]
This should no longer be an issue with 6.2 release.

From: Ray Kong
Sent: Friday, April 27, 2018 10:26 AM
To: Azure/service-fabric-issues <reply@reply.github.com>; Azure/service-fabric-issues <service-fabric-issues@noreply.github.com>; Rajeet Nair <rajeetn@microsoft.com>; Hasibur Rahman <harahma@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/service-fabric-issues] Service Fabric Errors in Event Viewer (#1005)

@Rajeet Nair<mailto:rajeetn@microsoft.com>@Hasibur Rahman<mailto:harahma@microsoft.com>
The attached shows that FabricHost.exe has 149 connections to dockerrd.exe, is this expected?

I am assigning this to Hasibur.

**Comment by mcbc** [comment]
I face this issue after adding health probe port number 13. as I remove that health and load balancer probe port cluster is back.
