### ISSUE TITLE
Service Fabric  - Analysis of ETL Files

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1030]
Hi Team,

i see bunch of ETL files in SF Programdata folder.
D:\ProgramData\SF\Log\Traces.

fabric_traces_6.1.480.9494_131698193371752128_1.etl
FabricInstallerService_6.1.480.9494_131698193202417092.trace.

i am using Microsoft Message analyzer to look into etl files but as it contains lots of information.
i am not able to do analysis of it.
is there way to filter errors in etl files only for troubleshooting purpose

Thanks,
Naresh Khatri

**Comment by srrengar** [comment]
Hi @nareshkhatri81 these files are used by our engineers during support cases. We recommend you turn on Azure Diagnostics (if you haven't already) and you can view events from your cluster in Log Analytics to troubleshoot. 

Here are the instructions on this: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-oms-setup 

Additionally you can open a support case and our engineers will provide 1:1 assisted support

Thanks,
Sravan

**Comment by nareshkhatri81** [comment]
@srrengar 
we are running cluster onpremise.
is there any way for us to filter errors in ETL logs ?

Thanks,
naresh Khatri

**Comment by nareshkhatri81** [comment]
@srrengar 
Thats strange. is there way to filter out errors from those ETL logs ?
are you saying errors will be displayed in SFx and Event viewer ?
there wont be any error that will be missed in these places.
there is no way to filter out errors from ETL logs ?
what is purpose of ETL logs ? does it contain only verbose information.

Thanks
Naresh

**Comment by srrengar** [comment]
@nareshkhatri81 there isn't a way to filter out errors from the ETL files, they are used by our engineers to parse through the verbose information for particular support cases

**Comment by nareshkhatri81** [comment]
@srrengar 
could you confirm if SF logs all errors in event viewer ?
can we consider event viewer as single source of truth for all errors ?
is it possible to enable verbose logging where we can see what happening inside cluster when some error occurred in event viewer ?

Thanks,
naresh Khatri

**Comment by EVMartinez** [comment]
Hello @nareshkhatri81 There are two options that you can use:

- Copy the .etl file to your local machine (if is an issue with service fabric you can copy the .etl file that starts with Fabricblahblahblah.etl because there others like leaseblahblah.etl)
- Go to Event Viewer of your local computer (i.e. laptop)
- Right click in Event Viewer(local) and click in open saved log
- In the file filter select .etl file type (it's not the default choice)
- You will be prompted to convert the log file, accept
- You will be prompted to save the converted file in the Saved Logs section, accept
- Right click in the converted log file and filter by error critical and warning
- Identif

y the issue and then clear the filter and look for informational events before and after the error, since many times informational events contains additional information

As a side note, no, Not all the events are sent to the event viewer (potential performance hit, hence the .etl file)

Another option is to use Perfview and look into the events section, there you can filter by text for the several service fabric subsystems.

Hope this helps.
