### ISSUE TITLE
Partition.ReportPartitionHealth fails with Exception when Description is too long (>4096)

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#104]
Partition.ReportPartitionHealth fails with Exception when Description is too long (>4096) and as long I definitely agree that parameter validation is good there are some places I would definetely prefer automatic truncation over exception.

Methods used for error reporting are definitely one of this exceptional groups.

Consider following scenario:
Partition.ReportPartitionHealth(new HealthInformation("MySource", "MyProperty", HealthState.Error) { Description = $"Something went really wrong: {ex.ToString()}" }

This line is non-deterministic but it looks quite legit. Usually exceptions are short and everything will go as expected, but if you exceed 4096 not only error will not be reported, but also health state would be considered as OK and also it might cause some unexpected behavior in code. What would lead to serious diagnostic issues.

I would definitely recommend reshaping this API to run automatic description truncation to 4096 instead.

**Comment by mkosieradzki** [comment]
There is also another (minor) off-by-one issue:
Documentation states: The maximum string length for the description is 4096 characters.
While actually accepted max string length is 4095 :).

**Comment by masnider** [comment]
Hi @mkosieradzki - this should now be fixed in 5.6. Now if the health report is longer than the default limit, the health report description is truncated. If it has more than 4096 characters, the size is reduced to 4096, with last characters containing a marker " [Truncated]". The marker is intended to show users that truncation occurred. If you're still seeing it please reopen and let us know. 

Thanks again for reporting the issue.
