### ISSUE TITLE
Add PartitionRepresentativeKey to ServicePartitionInformation

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#105]
ServicePartitionInformation generic class does not contain **directly** any information allowing to determine a representative key for backup/restore/data loss scenarios. As we know (and according to the backup documentation) PartitionId changes after service is recreated so you cannot depend on this value for backup/restore.

My suggestion would be to add PartitionRepresentativeKey (or CanonicalKey) as string or object to the ServicePartitionInformation base class - it might be through an extension method to help identify partition for backup/restore purposes.

If someone complies to the guideline of not modifying partitioning scheme this might be a straightforward way to deal with backup/restore.

Alternatively please update documentation:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-backup-restore

"One caveat is that the partition ID may have now changed, since the runtime creates partition IDs dynamically. Thus, the service needs to store the appropriate partition information and service name to identify the correct latest backup to restore from for each partition."

and add suggestion with a code snippet to upcast to get a Partition Representative Key: for example((Int64RangePartitionInformation)Partition.PartitionInfo).LowKey

**Comment by masnider** [comment]
Thanks for the feedback!

**Comment by masnider** [comment]
Forgot to reply to this: the docs have been revamped, but I'm not sure if this is specifically called out yet. We'll get that, and hopefully upcoming work with backup and restore should make this less error prone. In the meantime I've confirmed that our sample that shows off backup and restore [does](https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/blob/811eff1ccedacc420eb2a3e7113202c7e892e21a/ReferenceApp/Inventory.Service/LocalBackupStore.cs#L56) take the partition keys into account (I included both since there's no guarantee that the ranges are the same in the restored location - you may be doing some sort of complex replay).
