### ISSUE TITLE
Removing the replication endpoint in a stateful service puts the cluster in an unusable state

### ISSUE THREAD

**Issue by tastyeggs** [Azure/service-fabric-issues#1111]
Due to a mistake on our side, one of our engineers removed the Replication Endpoint in a Stateful Service's manifest.

We tried to perform and upgrade; that broke as the new node understandably didn't come online. Rollback was just stuck for well over an hour with 0 progress.

Unable to delete service, unable to delete application. Clearing node states didn't work. Nothing worked, and eventually had to go delete the entire service fabric cluster on Azure. And of course, I couldn't create another cluster on the side, due to the Core Quota limitations, where I can have at most just 1 16x5 core cluster in my region.

We're looking at 1hr downtime because thats how long it takes for a new cluster to come online. Thankfully we had just started using stateful services, so there was not much data to lose.

Here's Get-ServiceFabricApplicationUpgrade output:
```
ApplicationName               : fabric:/Egg.Core.Fabric
ApplicationTypeName           : Egg.Core.FabricType
TargetApplicationTypeVersion  : 1.0.11
ApplicationParameters         : { "Egg.Core.MediaProxy_InstanceCount" = "-1";
                                "Egg.Core.MessageBroker_MinReplicaSetSize" = "3";
                                "Egg.Core.MessageBroker_PartitionCount" = "1";
                                "Egg.Core.MessageBroker_TargetReplicaSetSize" = "3" }
StartTimestampUtc             : 6/15/2018 3:57:03 AM
FailureTimestampUtc           : 6/15/2018 4:57:11 AM
FailureReason                 : Interrupted
UpgradeState                  : RollingBackInProgress
UpgradeDuration               : 00:59:08
CurrentUpgradeDomainDuration  : 00:57:08
CurrentUpgradeDomainProgress  : 2

                                NodeName            : _16C64G_2
                                UpgradePhase        : PreUpgradeSafetyCheck
                                PendingSafetyChecks :
                                        EnsurePartitionQuorum - PartitionId: 414b5e2c-e8fa-4f2c-805b-a7972452f41c
NextUpgradeDomain             : 3
UpgradeDomainsStatus          : { "2" = "InProgress";
                                "0" = "Completed";
                                "1" = "Completed";
                                "3" = "Pending";
                                "4" = "Pending" }
UpgradeKind                   : Rolling
RollingUpgradeMode            : UnmonitoredAuto
ForceRestart                  : False
UpgradeReplicaSetCheckTimeout : 00:00:30
```

How can 1 mistake like this be allowed to take down an entire cluster?

Could you please share guidance on how I could recover from these situations?

I'm sorry to say, but using Service Fabric is so hard, as its a very opaque system. That I have to delete everything and start over as the only way to fix small mistakes is quite unimaginable. Maybe it's just my lack on knowledge, but no resource online was helpful. The documentation continues to be sparse after all these years.

Here are my learnings:
- There must be a switch that will at least force-delete the service from the cluster. This should succeed no matter what
- There must be a switch to do a force revert
- Maybe the upgrade could have worked, maybe it wouldn't have had I let it run for 1 day, but we need to be able to deploy fast and rollback fast. Hour-long processes simply do not cut it.
- We need a step-by-step guide on take *complete* control of the upgrade process, where we push the correct versions of the packages on each node

**Comment by masnider** [comment]
Added some folks who might be able to comment on why the original upgrade was stuck. But upgrades just don't "get stuck" randomly. [This guide](https://blogs.msdn.microsoft.com/huizhu/2018/05/04/troubleshoot-service-fabric-cluster-upgrade-issues/
) can be pretty useful in figuring out where things are stuck and why. Technically it's for cluster upgrades, but the same mechanisms are used for application upgrades too. 

In this case it might have been worth looking at the partition indicated in the health report you pasted, so you can figure out why it's stuck. In this case the other replicas were probably not coming up, but we can look at why. Completely agree this should be preventable. Also you almost certainly didn't need to reset the cluster to get out of this. 

> There must be a switch that will at least force-delete the service from the cluster. This should succeed no matter what

This is Remove-ServiceFabricApplication -ForceRemove for the whole application or Remove-ServiceFabricReplica -ForceRemove to drop an individual replica. Are you saying that you used these and they didn't work?

> There must be a switch to do a force revert

This is usually just starting another upgrade to target the original version, or Start-ServiceFabricApplicationRollback

> Maybe the upgrade could have worked, maybe it wouldn't have had I let it run for 1 day, but we need to be able to deploy fast and rollback fast. Hour-long processes simply do not cut it.

Upgrade durations and speed are almost entirely in your control. In this case it would be good to know what parameters you specified when starting the upgrade. More info on upgrade parameters is [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-parameters). For example, the reason the upgrade didn't stop and roll back automatically might be something like UpgradeTimeout or UpgradeDomainTimeoutSec, both of which are infinite by default. 

> We need a step-by-step guide on take complete control of the upgrade process, where we push the correct versions of the packages on each node

You probably don't since that's not a great idea - you want an automated system to take care of this for you. The issue here is probably that `Deploy- `is hiding some things from you, and we can do a better job of describing those parameters.

**Comment by abhishekram** [comment]
Can you please share the cluster resource ID and region in which the cluster was deployed so we can take a closer look?

**Comment by abhishekram** [comment]
Hi, just following up on this. If you'd like us to investigate further, please share the cluster resource ID and region as requested in the previous post. Thank you!

**Comment by tastyeggs** [comment]
I no longer have the cluster around, due to Azure quota limitations. So its going to be difficult to investigate this issue right now.

The only thing to look into would be the upgrade behavior should I accidentally remove the Replicator endpoint in a stateful service; would it lead to an automated rollback?

**Comment by motanv** [comment]
Hello @tastyeggs, 
Since I have not heard back from you, I am closing this issue. Please open a new issue if you face the problem again.
Thanks,
Tanvir
