### ISSUE TITLE
No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.

### ISSUE THREAD

**Issue by nailene** [Azure/service-fabric-issues#1132]
I have been struggling for days to connect to a cluster that I had created via Azure Portal, Visual Studio, and Azure Resource Manager. I get the same problem. I am not able to connect to the new cluster that was created. I am also not able to view the service fabric explorer, with an error "The site can't be reached."
What am I missing? I followed all the single steps of creating a cluster via Azure Portal, Visual Studio, and Azure Resource Manager but somehow connecting to the cluster with its endpoint was not possible. 

![image](https://user-images.githubusercontent.com/40427310/41777789-d2fb57ca-762c-11e8-8b88-ec12a1b092de.png)
![image](https://user-images.githubusercontent.com/40427310/41777862-1ae064ae-762d-11e8-99c8-7a1aed20549a.png)

Please help me! Thank you...

**Comment by aljo-microsoft** [comment]
My assumption is you created a cluster using with basic security configuration type:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-portal

or 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-arm

In the case of the later, please be mindful of:

https://github.com/Azure/azure-powershell/issues/5998

You'll need to have an updated preview release of the AzureRM module to avoid creating a client auth only self signed certificate that doesn't work for Server Authentication (Subsequently not allowing browsers to trust the machines hosting Service Fabric Explorer)

Then my assumption is you did not Set up a client certificate on the remote computer your attempting to connect to your cluster from:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster#connectsecureclustersetupclientcert

The certificate you will use for this action is the one you used to create your cluster.

So if you used: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-portal

Under the "4. Summary" section, you'll see a screen shot with a Red Arrow that points to "this link" that is hyper linked to a portal blade where you can download your cluster certificate that is hosted in your Azure Key Vault.

Below which is the following:

"In order to perform management operations on your cluster using Powershell or CLI, you need to connect to your cluster, read more on how to at connecting to your cluster."

Which has the hyper link for "connecting to your cluster" which lands on a page with a top paragraph that states:

"If you are connecting to a cluster secured with certificates, set up the client certificate on the computer that connects to the cluster."

with "set up the client certifcate on the computer that connects to the cluster" hyperlinked to 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster#connectsecureclustersetupclientcert

Which decribes the certificate import process.

Lastly,
Self Signed certificates do not support the common name certificate declarations, and it is recommend you obtain a CA issued certificate for your production environment and follow: 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-change-cert-thumbprint-to-cn

To greately simplify management, and gain security value of a CA issued certificate.
