### ISSUE TITLE
Cleanup leftover replica state

### ISSUE THREAD

**Issue by JohnNilsson** [Azure/service-fabric-issues#1137]
We had an issue where an exception in `StatefulServiceBase.OnOpenAsync()` impacting all services for a few hours seems to have caused all available disk space to be consumed by freshly created replicas.

Is this expected behavior? And if so, what is the recommended approach to avoid it, and if failing that, how to clean things up?

Using the various ways to query the cluster
- The  `Get-ServiceFabricReplica` and `Get-ServiceFabricDeployedReplicaDetail` commandlets
- The new rest based FabricClient methods `GetReplicaInfoListAsync`,`GetDeployedServiceReplicaInfoListAsync`,`GetDeployedServiceReplicaDetailInfoByPartitionIdAsync`
I failed to find any information about the majority of the replicas (expected to find in status `Down`, `Dropped` or `InBuild` or some such, but found only the normal `Ready` and one or two `Standby`

My conclusion from that was that most of the replica state was no longer being tracked and would continue to cause troubles until manually removed. Reasonable conclusion?

In the end we ran a clean-up script on all the nodes to move those "unknown" replica folders out of the disk. By comparing the output of `Get-ServiceFabricDeployedReplica` with the partition and replica folder names. Moving anything without a corresponding `PartitionId` or `ReplicaId` in the `Get-ServiceFabricDeployedReplica` result. (Having the node set to `Pause` during this operation).
Is this a "reasonably" safe approach to resolve this situation? What would you recommend as an alternative?

**Comment by masnider** [comment]
Hi there. Can you share with us how you determined it was replica state that was taking up all the space? Generally for stateful service replicas SF doesn't give up on them, so you wouldn't see "new" replicas or new resources allocated for them, just repeated attempts to recover the failed one. 

Regarding why the other replicas weren't showing up, they're filtered out of most queries by default. So depending on which API you would have had to modify the filter to see everything.  Ex:

![image](https://user-images.githubusercontent.com/10968331/41882250-c6f49078-789c-11e8-9ecf-3d8717428369.png)

So depending on what you had there it's possible things weren't showing up. 

Pause is probably good but I probably would have used Restart as the intent, since otherwise there were still services running on the machine (see my answer [here](https://stackoverflow.com/a/34321564) )

**Comment by masnider** [comment]
Can you share the specific path you see these in? It might be the application's package cache.

**Comment by JohnNilsson** [comment]
The path we saw this in was the one returned by
```powershell
$ApplicationWorkDir = (Get-ServiceFabricDeployedApplication -NodeName $NodeName -ApplicationName $ApplicationName).WorkDirectory
```
Where the `P_*` and R_* folders was identified by
```powershell
$PartitionFolders = Get-ChildItem "$ApplicationWorkDir\P_*"
```

**Comment by aljo-microsoft** [comment]
@JohnNilsson 

The recommended approach " to avoid it:", is to properly plan your capacity, and monitor your resources:

https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-capacity-scaling
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-best-practices-monitoring

New best practices content has been published, and I recommend reviewing:
https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-overview

Specifically validate you:
"Use a D2v2 or higher SKU for the primary node type. It is recommended to pick a SKU with at least 50 GB hard disk capacity."
https://docs.microsoft.com/azure/service-fabric/service-fabric-production-readiness-checklist

Although I am closing this, if this issue isn't resolved, please reopen.
