### ISSUE TITLE
question: is there a way to restart application with different parameters?

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#114]
Is there a way to restart application with different parameters, without publishing a new version and do an upgrade?

For some operation tasks, we only want to change some configs. I looked through the doc, it seems only possible to delete the application first and then re-new it.

**Comment by mkosieradzki** [comment]
1. You can keep configs inside stateful service, then change parameters through your API.
2. Upgrading application does not require deleting application (!).
3. There are special builit-in facilities for config upgrade without even restarting application: When ForceRestart is false and new service version does differ only by only ConfigPackages or DataPackages service instances are not restarted and you can handle event Context.CodePackageActivationContext.ConfigurationPackageModifiedEvent
4. If you really want to force restart your stateful service without running upgrades etc you can use: new FabricClient().ServiceManager.RestartReplicaAsync...

**Comment by qrli** [comment]
Sorry I didn't make it clear. I'm working with guest executables, so there is no stateful service for me.

**Comment by masnider** [comment]
What do you mean by new parameters then? How (specifically) are you specifying the parameters today?

**Comment by qrli** [comment]
There are two sets of parameters:
1. The parameter override of Publish-NewServiceFabricApplication and Upgrade-ServiceFabricApplication.
2. The environment variables and config files on the cluster VM.

If all I want is to change some parameters or env variables and restart the services to pick up new value, what I do today:
For 1, publish a upgrade, which will re-upload the big package, which is slow.
For 2, restart the VMs one by one.

**Comment by masnider** [comment]
Don't think I get it yet, sorry. Where does the guest read these settings from?  Is it a config file that gets deployed alongside it, or is it literally just environment variables? If it is environment variables, who sets them and when? 

This feels like it should either be a config file deployed next to the guest which it reads (and then you can use differential packaging (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#upgrade-with-a-diff-package) or a differential package that you do an upgrade with with -ForceRestart set, which will shut your service down, and then set the values with a SetupEntryPoint so that they are present when the rest of the package starts up.

**Comment by qrli** [comment]
@masnider Currently our guest executables read setting from env variables, as well as certficate file (as node.js cannot read certificate store), which is initialized via script in cluster ARM file, and later changed manually via remote desktop or remote powershell. These settings are `shared` by all applications/services.

For parameters of manifest, though guest executable cannot read them, they can still be used in the manifest file to change various settings, e.g. service instance count, port, placement constraint. It is also possible to use the paramater to set env variables for a specific service, with the latest version of service fabric.

Diff package looks interesting, but it still involves a new package, which also adds complication to CI build.
I'd think there were an easy way for Ops people, just like when you create new or upgrade where you can simply specify pass a parameter override cmdlet argument. But it seems no.

So I'm also investigating other approaches, like using etcd. But for taking up the configuration setting changes, I still want a simple solution (we have services in different languages, so I'd like to avoid handling conf change for each of them): like simply restarting my services gently.

I found Restart-ServiceFabricDeployedCodePackage, but the doc says it is for testing. What's the implication if I use it for production?

**Comment by masnider** [comment]
I think we may be talking past each other. Here's some things you can do to make this work. These steps are easy, normal, and how we recommend this problem be solved for your case.

- Today Service Fabric's config integration only comes via settings.xml, if you aren't going to use that then the package level parameters (which would solve your problem) are not going to work. Please use this. 
- Since you are using a guest exe, there's no integration with the API to help you consume config changes. This is fine. The way to do it yourself is as I specified: use the settings.xml, use a setupentrypoint to read the config and to set the new environment variables, and do a normal upgrade with by changing the application parameters and the -ForceRestart flag. This solves your restart problem, and does -NOT- require you to necessarily create a new package every time - if you have the settings plumbed down into settings.xml then you don't need to create a new package to change them, just to pass new parameters by start-servicefabricapplicationupgrade.
- yes there are enhancements coming to make environment variables more useful, but for now this is what I'd recommend unless you are running many service instances on a machine.
- if you are using the default services of the application manifest then we recommend that you do not since as you have mentioned you have to change the manifest to deploy new settings. If you want a more ops way of doing things, then you can remove the default services and use Update-ServiceFabricService to change the parameters on the fly. Generally we recommend default services only for dev/test.

**Comment by qrli** [comment]
@masnider Thanks for the great explaination. It is much clearer to me now.

* Regarding your first point: we used guest executable because we wanted to keep it close to docker solution, as we tentatively want to go in the docker direction. I used to investigate whether the service fabric config API can be used independent of the service fabric framework, but I didn't figure out within time budget.

* Regarding your second point: I actually tried to use SetupEntryPoint to set env variables a while ago. However, the env values are lost as soon as the SetupEntryPoint process exits. I also tried to use machine scope env variables. It worked for the first time. But after the VM is restarted, Fabric service process inherits a copy of those env variables, then that copy is always used no matter how I change the env variables later, unless I restart the FabricHostSvc. I think the new env variable override feature (I like it) in manifest should solve this.

**Comment by VipulM-MSFT** [comment]
Regarding the original question about restarting the application with different application parameters without changing the manifest version:

Yes this is possible. See the example below. I used the unmonitored upgrade in the example, but you can use monitored upgrade as well.

```
PS C:\windows\system32> Get-ServiceFabricApplication


ApplicationName        : fabric:/Application1
ApplicationTypeName    : Application1Type
ApplicationTypeVersion : 1.0.0
ApplicationStatus      : Ready
HealthState            : Ok
ApplicationParameters  : { "Actor1ActorService_PartitionCount" = "1" }

PS C:\windows\system32> $appParams = @{ "Actor1ActorService_PartitionCount"="1"; "TestParameter"="AFTER"}

PS C:\windows\system32> Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/Application1 -ApplicationTypeVers
ion 1.0.0 -ApplicationParameter $appParams -UnmonitoredAuto


ApplicationName               : fabric:/Application1
ApplicationParameters         : { "TestParameter" = "AFTER";
                                "Actor1ActorService_PartitionCount" = "1" }
TargetApplicationTypeVersion  : 1.0.0
UpgradeKind                   : Rolling
ForceRestart                  : False
UpgradeMode                   : UnmonitoredAuto
UpgradeReplicaSetCheckTimeout : 49710.06:28:15

PS C:\windows\system32> Get-ServiceFabricApplication


ApplicationName        : fabric:/Application1
ApplicationTypeName    : Application1Type
ApplicationTypeVersion : 1.0.0
ApplicationStatus      : Ready
HealthState            : Ok
ApplicationParameters  : { "Actor1ActorService_PartitionCount" = "1";
                         "TestParameter" = "AFTER" }

```

**Comment by lovelangy** [comment]
@vipul-modi,  your scripts seem not working any more.  It returns  "Start-ServiceFabricApplicationUpgrade : Application is already in the target version".

According to https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricapplicationupgrade?view=azureservicefabricps

- Start-ServiceFabricApplicationUpgrade is to  **Upgrade** a Service Fabric application to specified ApplicationTypeVersion.   it is not @qrli wants, he wants to restart the application with different application parameters without changing the manifest version.

@qrli   can you please give more information how you solve this problem?  Irun into the same situation.

**Comment by raunakpandya** [comment]
@lovelangy Are you passing different application parameters to Start-ServiceFabricApplicationUpgrade cmdlet? Seems like no and that is the reason it would complain that application is already in target version. The cmdlet expects either the application type version to change or the application parameters.

**Comment by lovelangy** [comment]
@raunakpandya  yes, you are right.  My parameters are the same.  thanks for pointing it out.    After that i run into new problem.   not sure why we need to upgrade default service? 

Start-ServiceFabricApplicationUpgrade : Default service descriptions can not be modified as part of upgrade. Modified default service: 
fabric:/xxxxx  To allow the modification, set EnableDefaultServicesUpgrade to true.

**Comment by raunakpandya** [comment]
Refer to @masnider point above - 

"if you are using the default services of the application manifest then we recommend that you do not since as you have mentioned you have to change the manifest to deploy new settings. If you want a more ops way of doing things, then you can remove the default services and use Update-ServiceFabricService to change the parameters on the fly. Generally we recommend default services only for dev/test."

Seems like there is some difference in the placement constraint or the no of instances etc in one of the default services. As mentioned above, we recommend you do not have default services in your application manifest.

**Comment by qrli** [comment]
@lovelangy We ended up not using SF's parameter system. We used Consul instead, which is straight-forward and easy to dynamically update. And it has centralized setting management with web UI, rather than 100s of parameters.xml files.

**Comment by lovelangy** [comment]
@raunakpandya  thanks for your help.  I followed your advice to remove the default service from application.xml. and use powershell to create service.  it works like charm.

https://devblogs.microsoft.com/premier-developer/how-not-to-use-service-fabric-default-services/
