### ISSUE TITLE
What security is being used by default with Windows based authentication?

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#1141]
Hello,

I can see that Windows authentication to UI is based off HTTP protocol. Not sure if Kerberos or NTLM is being used but it seems insecure. So either HTTPS shall be enabled out of the box (even with self signed certificate) or only Kerberos shall be allowed.

**Comment by leikong** [comment]
"Negotiate" security provider is used for "Windows" security, The actual protocol depends on whether it is in a domain environment or not. Kerberos if yes, NTLM otherwise. 

Even with Kerberos, only auth is done, no traffic encryption, as it is HTTP.

On the other hand, with "Windows" security, Server fabric TCP based transport always encrypts traffic.

**Comment by artisticcheese** [comment]
I would assume NTLM with no HTTPS considered to be insecure for any corporate environment. I think SF shall expose HTTPS endpoint with self signed certificate to mitigate all of this issues.

**Comment by leikong** [comment]
Customers who choose "Windows" security should be in a domain-joined environment, in which case, "Windows" security means Kerberos, not NTLM. I am not arguing, just want to point out this minor point.

Currently, if you choose X509 security, then you get HTTPS. I agree that making the default secure is a desired improvement.
