### ISSUE TITLE
The "ProjectReferencesWithConfiguration" parameter is not supported

### ISSUE THREAD

**Issue by felipecruz91** [Azure/service-fabric-issues#1147]
**Environment information**
OS: Windows 10 Pro
Version: 10.0.16299 Build 16299
Microsoft Azure Service Fabric: 6.2.301.9494
Microsoft Azure Service Fabric SDK: 3.1.301.9494
Cluster Mode: 1 Node
**Issue**

Sometimes when I build my SF application and I try to deploy it to my local SF cluster I get the following error:

![image](https://user-images.githubusercontent.com/15997951/42025066-01584f38-7ac4-11e8-8da8-fd54b410f9e9.png)

I faced this issue a long time ago and I fixed by upgrading Visual Studio to version 15.6.7 and Service Fabric SDK to version 3.1.269. However, nowadays those versions are older and it is pointless to go back to those old versions.

**Comment by ravipal** [comment]
Looks like there is a mismatch between Microsoft.VisualStudio.Azure.Fabric.Application.targets file and Microsoft.VisualStudio.Azure.Fabric.BuildTasks.dll in the Microsoft.VisualStudio.Azure.Fabric.MSBuild nuget package. What is the version of nuget package used by the project?

**Comment by felipecruz91** [comment]
@ravipal In the `.sproj` file, I have the following version: `packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.5`

**Comment by ravipal** [comment]
The *target file somehow loads the old version Microsoft.VisualStudio.Azure.Fabric.BuildTasks.dll assembly from somwhere else instead of the one from the current nuget package. Can you please attach debugger to msbuild.exe and check where the Microsoft.VisualStudio.Azure.Fabric.BuildTasks.dll is loaded from?
![image](https://user-images.githubusercontent.com/1775825/42775006-23d38d7a-88e8-11e8-9aff-5a0aaf4811eb.png)

Here are the steps to get the Microsoft.VisualStudio.Azure.Fabric.BuildTasks.dll path.
1. Make sure no MSBuild.exe is running, if so kill all the processes.
2. Package the application and repro the issue. Now there will be one MSBuild.exe process.
3. Using VS attach debugger to this MSBuild.exe process
4. Now open the Debug->Windows->Module and check which Microsoft.VisualStudio.Azure.Fabric.BuildTasks.dll is being used. 

Also please share the content of *sfproj.

**Comment by StenPetrov** [comment]
I had the same issue with VS 2017 Preview 5.
When I opened a solution with SF project in it VS prompted for some incompatible packages to be updated. Once "updated" the projects wouldn't build.

With the update VS created a _packages_ folder with the latest SF nuget and was loading *.targets and *.BuildTask.dll from different places.

Make sure you only have a single version of SF packages on your machine.

**Comment by ravipal** [comment]
Please reopen if this issue still happens.
