### ISSUE TITLE
Question: [Service Fabric] After installing EventFlow, the Service Fabric cluster from Azure goes in an unhealthy state, the service will be no longer available.

### ISSUE THREAD

**Issue by nanamag** [Azure/service-fabric-issues#1162]
I have the following scenario:
- a working SF microservice in Azure;
- I need to create a pipeline to send the logs to OMS;
- I did everything that  documentation says here: https://blogs.msdn.microsoft.com/maheshk/2017/07/11/azure-service-fabric-five-steps-to-achieve-event-aggregation-and-collection-using-eventflow-in-service-fabric/
- but after installing all the necessary libraries to create the pipeline, the service is not working anymore in Azure. it goes in an unhealthy state.
- on my local machine there is no problem, I can still ping my API methods. it doesn't behave different.

There is an incompatibility issue that I should be aware of? Or a library version that affects the Service Fabric?
This is the error from Service Fabric Cluster:
"	       Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'.
There was an error during CodePackage activation.The service host terminated with exit code:3762504530"

**Comment by guibirow** [comment]
This message is because the service failed to start, you could try debugging the service or see the application logs, stored somewhere for debugging until you fix the error, maybe in a database, once you are confident with the logging, you switch back to app insights. You could also log using ETW and use a separate service listening these events

**Comment by srrengar** [comment]
Hey @nanamag if you want to get the data into OMS have you seen our article on the SF integration for this? https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-oms-setup

Looking at the blog you mentioned, this is for sending data to Application Insights instead of OMS, if that's the case then you may also want to consider our App Insights nuget package. The steps to enable are here - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-monitoring-aspnet
