### ISSUE TITLE
[Documentation]What is the Reverse Proxy retry policy for non-idempotent HTTP verbs like POST?

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#118]
I am unable to find some specification regarding reverse proxy retry policy.

1. I assume that in case of 404 without proper header or 503 request is retried.
2. No retry when any other HTTP error occurs? Or?
3. What happens in case of underlying TCP connection error before receiving any response headers? retry or no-retry?
4. In case of error before receiving the entire response but after receiving response headers - in that case I suppose there is no retry as this condition is handled on the client
5. What about Retry-After header?

Are there any optional headers allowing to force proxy to do some hammering with exponential back-off for different responses or is this something intended to be done on the client side?

**Comment by alzuma** [comment]
+1

**Comment by Mardoxx** [comment]
[From release notes of 6.0](https://msdnshared.blob.core.windows.net/media/2017/10/Microsoft-Azure-Service-Fabric-Release-Notes-SDK-2.8.0-Runtime-6.0.0.pdf):

> Reverse Proxy – Retry behavior
> For service response status codes 404 (without `X-ServiceFabric=ResourceNotFound`, 410 and 503), reverse proxy will retry the request only for idempotent safe methods: GET, OPTIONS and HEAD. For any other HTTP method, it will not retry and forward the status code back to the client. 
> As of now, Reverse proxy will not honor the Retry-After header for such retries. We will look at adding that support in one of the future releases

**Comment by kavyako** [comment]
In addition to this, reverse proxy also re-resolves and retries if there is a connection error when making the initial connection.

**Comment by pr4d33p** [comment]
Hi @kavyako I am writing a health runner endpoint that will send 503 response code in case of health failure of any dependent resource/dependency and its a Get call, but due to reverse proxy my call is getting retry until the timeout, how can I bypass the retry logic in that case, do we have something like  404 and X-ServiceFabric=ResourceNotFound for 503 Get call?

**Comment by jasonrmh** [comment]
I have a similar issue if my api returns 422 - UnproccessableEntity due to invalid model on a POST, service fabric reverse proxy retries. 
Although the retries do not have a request body and fail anyway with a 400 - BadRequest.

I can't find any documentation on the behaviour or how to prevent retries in these scenarios (aside from 404).
