### ISSUE TITLE
Remoting V2 Time Out part of Actor Method Call

### ISSUE THREAD

**Issue by mathavanmani** [Azure/service-fabric-issues#1211]
Hi,
I got a simple Stateful Actor Service and invoking the method of Actor from client using 

var actorInstance = ActorProxy.Create<ICompileActor>(actorId, new Uri("uri"), "ActorServiceEndpointListener");

I have added the following attribute part of Actor interface 
[assembly: FabricTransportActorRemotingProvider(RemotingListenerVersion = RemotingListenerVersion.V2, RemotingClientVersion = RemotingClientVersion.V2)]

And also overridden the CustomActorService with following method to use Remoting V2

 protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
        {
           return new[]
			{
				new ServiceReplicaListener(context => new FabricTransportActorServiceRemotingListener(this,new FabricTransportRemotingListenerSettings()
                {
							EndpointResourceName = "ActorServiceEndpointV2", OperationTimeout = TimeSpan.FromHours(2)
					}),"ActorServiceEndpointListener")
			};
        }

And ActorServiceEndpointV2 is being referred in Service manifest as well.

I still get time out exception(This can happen if message is dropped when service is busy or its long running operation and taking more time than configured Operation ) part of actor method call. May I know what I'm doing wrong here.?

Thanks.

Using Version 3.2.162 of Microsoft.ServiceFabric.Actors .

**Comment by mathavanmani** [comment]
Using 3.2.162 version of Microsoft.ServiceFabric.Actors

**Comment by suchiagicha** [comment]
@mathavanmani 
You are not changing the default timeout on client side. Looks like your actor method are taking more time than default timeout ( 5 mins)
You don't need to override the actor service if you are using attribute. Check below attribute

[assembly: FabricTransportActorRemotingProvider(RemotingListenerVersion = RemotingListenerVersion.V2, RemotingClientVersion = RemotingClientVersion.V2
,OperationTimeoutInSeconds =2*60*60)]

Also we don't recommend long running actor calls since it is single threaded model. All other calls for the same actor will wait for that time.

**Comment by mathavanmani** [comment]
@suchiagicha Thanks for your help.
