### ISSUE TITLE
Need better logging for Windows on-prem installations

### ISSUE THREAD

**Issue by guidoffm** [Azure/service-fabric-issues#123]
Logging on Windows should be done using ETW. It is described how to get the logs on Azure and how to get the logs in Visual Studio. But there is no description on how to to get the logs on a production on-prem SF cluster. Windows event logs do not show the SF logs out of the box.

**Comment by Liphi** [comment]
On the json config, the root folder containing the trace logs on each cluster node is configured.

      "fabricSettings": [
        {
          "name": "Setup",
          "parameters": [
            {
                "name": "FabricLogRoot",
                "value": "C:\\ProgramData\\SF\\Log"
            }
          ]

**Comment by ms-toddabel** [comment]
Couple of things, first the logs Liphi points to in the manifest are the service fabric logs that will be needed by the support team if you ever call Microsoft for support. They are not really useful to someone outside of our customer support team, but please ensure you have them. Service Fabric will groom these for you. To get events written to the Windows Event log off a box, most customers use OMS. See [this article ](https://blogs.technet.microsoft.com/msoms/2016/09/29/how-to-enable-data-and-log-collection-in-microsoft-oms/) for how to collect logs and data from nodes using OMS
Both of these are different from instrumenting your code, which you can do any way you want. The recommendation so far has been to use EventSource, which is a managed interface on top of the ETW layer. This is still a great choice for service that demand high performance, as you want to minimize the overhead of instrumentation and logging. If you use this, then you must have a listener on the machine listening to the events that are generated. Because this is on-prem, there is more of a burden on you to setup and monitor the cluster correctly. So just like you have to wire up your fault domains, you have to have a solution that listens. The [article on using ELK ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostic-how-to-use-elasticsearch) works perfectly fine on-prem too -- but you have to setup an ELK cluster on-prem. There are a number of other instrumentation solutions that can be used and the articles will be updated this month to describe them in details, but here's a preview. [EventFlow](https://github.com/Azure/diagnostics-eventflow) can be used to listen to EventSource based events and other inputs. [Serilog](https://serilog.net/) and [nLog](http://nlog-project.org/) can both be used to instrument your code -- both have ways to gather and visualize the logs.
