### ISSUE TITLE
IdleSecondary replicas left on incompatible nodes after change in placement constraints

### ISSUE THREAD

**Issue by plillevold** [Azure/service-fabric-issues#1272]
We are having a weird scenario with changes in placement constraints and replicas of stateful services. 

Our cluster is running Service Fabric 6.2.301.9494.
It contains two nodetypes, _worker_ and _compute_. _worker_ have no placement properties, _compute_ have a placement property _persisted=true_.

### Initial state of services
**FileActor** and **FileQueue** (a stateful service) default services running on primary nodetype _worker_
Both services have no placement constraints. Both services have Primary, ActiveSecondary and IdleSecondary replicas only running on _worker_ nodes.

### State after changing placement constraints
In an update to the **FileActor** and **FileQueue** services we added a placement constraint , "(persisted==true)", to both services that would require SF to move the services to secondary nodetype _compute_.

After SF completed moving the services to the _compute_ nodes, both services was left with IdleSecondary replicas on _worker_ nodes.

![idlesecondaries](https://user-images.githubusercontent.com/613604/45297370-74922980-b505-11e8-9cde-f26697b98e86.png)

![stateful service idlesecondaries](https://user-images.githubusercontent.com/613604/45297656-5a0c8000-b506-11e8-8790-4ea3dbc8ccaf.png)

### Points to note
We have other stateful services in the same cluster that was initially created with the "persisted==true" placement constraint. Correctly, these services have _only_ replicas running on the _compute_ node.

We are not receiving any warning or error traces in the cluster. 

### Solution
Since SF did not do anything about the "rogue" IdleSeconary replicas, I ended up removing them manually using the **Remove-ServiceFabricReplica** powershell command.

**Comment by plillevold** [comment]
To further illustrate, here is the before and after state of the **FileActor** service in our production environment. Again, no errors or warnings are surfaced, and the system is behaving just fine. 
The state of all the "rogue" IdleSecondary instances is **Standby**.

![fileactor-prod-replica-states before and after upgrade](https://user-images.githubusercontent.com/613604/45343666-d30ce580-b5a1-11e8-939e-292123e87d66.png)

**Comment by masnider** [comment]
These are "[Standby](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-replica-lifecycle#standby-sb)" replicas, as you point out. 

Standby replicas are copies of old replicas that we keep around so that we can use them in case other replicas fail (we presume it's cheaper to build up from partial state than it is to build a replica from scratch if we can help if). Standby replicas are kept for a default of 1 week. 

When you create the service you can modify the StandbyReplicaKeepDurationSeconds parameter on the StatefulServiceDescription or in the default service description in your app manifest if you want to keep them around for less time. If you just wanted to mitigate this easily, you could also Update-ServiceFabricService for the service to set the KeepDuration to a small value, wait for the replicas to get dropped, and then Update again to set the value explicitly back to the default. You could also change the default for all services (rather than setting it per service), by changing the UserStandByReplicaKeepDuration setting within the [FailoverManager](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings#failovermanager) section of your cluster configuration. 

In this case you might point out that since the constraints are currently set to prevent those replicas from ever being valid that we should just drop them. This is fair and we may add that optimization specifically in the future. We've considered this in the past, but (as you did) constraints can change during runtime (these nodes were valid before - who says they won't be valid again?), and we have so far prefered the safest/most conservative default around keeping state in the cluster, to provide the greatest chance that there are portions of state available to reconstruct/rebuild from if needed.

Hope this helps explain what you're seeing!

**Comment by plillevold** [comment]
@masnider awesome explanation as always. Thanks! The design makes sense now that I understand the replicas would go away at a given timeout. My point though wouldn't be that they should be dropped when constraints changed, I was rather expecting them to be moved along with the other replicas.

**Comment by joaocpribeiro** [comment]
This also happened to me. I do understand the reason why those idle secondary replicas remain in the nodes where they were valid, but unlike @plillevold, I faced problems because of this.
After the placement constraints were successfully changed, a second upgrade is failing.
I could see a warning message in the SF explorer containing `The Cluster Resource Manager has detected a Constraint Violation for this Replica`.
As far as I understand, SF tries to bring the idle replicas to active, but they are in the wrong nodes.
I was expecting SF to handle this behavior properly during the second upgrade, but it seems it does not.
