### ISSUE TITLE
Azure Service Fabric behavior on severe Azure incident

### ISSUE THREAD

**Issue by juho-hanhimaki** [Azure/service-fabric-issues#1274]
Hi,

As most probably know 9/4 South Central US Azure region was hit by quite severe incident. We had no resources hosted on the affected region but either way this raises a question what would happen to Service Fabric clusters if similar incident was to hit the datacenter a cluster is hosted in.

I assume the virtual machines are automatically shut down to protect the hardware. But what happens after that? Can/will the cluster and its services and state be restored if 5 or more replicas are used?

Is this automated or is there something the customer should do?

**Comment by olitomlinson** [comment]
This is a good question and I too would like some clarity and recommendations from the SF team.

By default a Service Fabric Cluster set up with VMSS uses a temp drive (d:) in Windows to persist the cluster state. This drive is not guaranteed to ever come back after a shutdown/failure, so yes it is entirely probable that the entire cluster state would be lost if not enough nodes came back up to satisfy the write quorum.

This is why we need Service Fabric clusters that support multi-region deployment (despite the problems of running a quorum across two physical geo-locations)

Obviously taking regular back-ups of the cluster is essential to mitigate a complete data loss scenario. See here https://github.com/loekd/ServiceFabric.BackupRestore

**Comment by masnider** [comment]
Going back and looking at this situation (and other similar cases we've seen in the past) the short answer is that recovery would usually be automatic.

The cluster will automatically recover if:
- A majority of the replicas of the system services can be recovered, and
- If a majority of the other nodes in the cluster are recovered

If  _any_ replica or instance of your services can be recovered, then _knowledge_ of those services can be recovered, even if some of the system services do not fully recover automatically. For example, if the replicas of the Failover Manager system service are all lost, but the worker nodes containing the replicas of your services are recovered, then after the VMs themselves recover, SF will realize that the FM could not be recovered and build a new one, which will recover the information about your services from the worker nodes, rebuild itself and then proceed to recover and restart your services. 

In the specific case of stateful services, if a majority of the replicas cannot be recovered, but some replicas are recovered, then SF will be able to recover that those services existed, but will not automatically recover those services since we cannot guarantee that they have seen all progress. This is where backup and restore is particularly valuable, since you can revert to a last known good state and then tell SF to RecoverPartition from there. 

The only time SF would fail to recover a service and also fail to _know_ that it had failed to recover a service would be if the system services (particularly the FailoverManager) were destroyed and rebuilt AND no instance of the service was recovered from any of the machines that were recovered (Consider a far fetched scenario where a stateless service had only ever existed with one instance on one node and that node was destroyed along with all the replicas of the failover manager). Upon rebuild there would be no record of this service. 

Generally to avoid concerns with regional failures like this we do recommend running multiple clusters in multiple regions, using something like multi-region-replicated CosmosDB, SQLDB, or Blob Storage for handling point in time backups of your services. Running more copies of the system services in each region generally ensures that you can recover the cluster even if some VMs are unable to recover their local data, and service recovery should proceed automatically from there.
