### ISSUE TITLE
Windows Printing Does not Work in Service Fabric Hosted Applications

### ISSUE THREAD

**Issue by groogiam** [Azure/service-fabric-issues#1294]
I am running into issues where Win32 functionality does not seem to work correctly for applications hosted inside service fabric.

I'm attempting to check the status of Printers on our network via a service. The System.Drawing.PrintDocument will randomly return false values for the PrinterSettings.IsValid.

In addition calling the winspool.drv open and print functions fails with 
System.ComponentModel.Win32Exception (1801): The printer name is invalid

The exact same code operates fine outside of service fabric. All processes are being run under a privileged user. Is there some other security mechanism that would be preventing these calls?

**Comment by groogiam** [comment]
A little more information about the issue. The issue appears to happen when making the win32 call to winspool.Drv OpenPrinterA The exception thrown is below.

Win32Exception (1801): The printer name is invalid

I did come across the following article about this error when calling this method for processes running under "System" The actual service process in this case is running under a AD service account but the FabricHost which spawned these processes is running under "System". Is there a configuration mechanism to change the FabricHost process to a service account?

https://social.msdn.microsoft.com/Forums/en-US/a27c6615-9452-44b1-90fc-9b91b15f0e50/openprinter-returing-errorinvalidprintername1801-when-called-with?forum=windowsgeneraldevelopmentissues

**Comment by oanapl** [comment]
@groogiam , have you checked [this article](https://docs.microsoft.com/azure/service-fabric/service-fabric-application-runas-security)?

**Comment by groogiam** [comment]
Yes. All services are running under a domain account. The services have no issue accessing network resources using this network credential except for shared printers. I have created a driver with the same code and run it outside of service fabric on the cluster nodes and it works fine as well. The issue only manifest when running the code inside of a Service Fabric Stateless service on Server 2012 R2 cluster machines. It appears something inside Service Fabric is stopping network printer names from resolving correctly on this particular version of the operating system. The 1801 exception is not a security exception it is a name resolution exception.

**Comment by masnider** [comment]
Yeah 
  | 1801 | ERROR_INVALID_PRINTER_NAME | The printer name is invalid.

Would it be possible for you to share the code that you're trying to use to print? Things I have seen that have resulted in this error:

- The printer is not listed in AD as a resource
- The printer name had some illegal characters in its name
- The machine has just come up and something about the machine policies hasn't gotten applied yet
- There is some additional policy that you need in order to access the printer, which is getting applied when you launch it manually but not when SF launches it. 

One thing you can try which then you can use to debug further is to mark the user as requiring an interactive logon for when SF launches the process. In your application manifest where you reference the domain user, add the PerformInteractiveLogon flag and say 'true'

<User Name="dom\user" AccountType="DomainUser"  PerformInteractiveLogon="true"/>

Give that a shot and let us know if it makes a difference.

**Comment by masnider** [comment]
Closing as we have not heard back from you in some time about whether any of these options helped provide an answer. If you are still having this issue, please let us know and we can assist further in debugging.
