### ISSUE TITLE
Service Fabric should not require separate SDK

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#132]
It should really just be part of Azure PS cmdlets, as absolutely every other feature

**Comment by masnider** [comment]
It is unlikely now as well in the future that this will ever happen. 

Historically this was not possible since the Azure SDK was not 64-bit, but Service Fabric's is exclusively 64-bit. 

Today, Service Fabric must have a standalone version that operates outside of Azure, and hence must have its own SDK separately from the rest of Azure. Including it in the Azure SDK would set up a cadence issue where Service Fabric wanted to updated but needed to wait and coordinate with the rest of the Azure SDK. It would also make it confusing since there would be multiple ways to get the SDK. It would also make it possible to have "both" installed (unless some work was taken to prevent it). 

In general, for all these reasons, it's been avoided to date, and kept separate.

**Comment by TarasRoshko** [comment]
I'm not following, why can't PowerShell cmdlets be part of Azure RM PS SDK? What does it have to do with app code being `x64/x86`? I could have sounded confusing, I mainly meant PS cmdlets, not application SDK, sorry

**Comment by masnider** [comment]
For example: we have customers that never touch Azure. They are on-premises in their own datacenters. No other Azure componentry. Or in AWS. They shouldn't have to download and use the Azure SDK. They don't have any use for 99% of it. We don't want to make people download the entire Azure SDK when they don't need it. 

Today the only real crossover between SF and Azure is the support in ARM for creating Service Fabric clusters. But the rest of the Service Fabric interaction is the same and exists both inside and outside of Azure. 

Also yes, even the Service Fabric PS modules are 64-bit only (since they used the Service Fabric runtime bits locally on the box which were also 64-bit only). Historically AzurePS was 32-bit only (since fixed) but that meant you couldn't run the SF PS commands from within the AzurePS context, and made interactions between the two sets of cmdlets hard.

**Comment by TarasRoshko** [comment]
Fair point, but seems like you could integrate SF cmdlets into Azure PS cmdlets, providing people who use Azure a shortcut, this would not require removing them from SF SDK, you can keep both which makes perfect sense, code can be shared internally, does not need to be a duplication?

If a customer is already using Azure, they are all set on cmdlets, no extra modules to install.
If a customer is not using Azure (say AWS), providing SDK with same cmdlets sounds reasonable.

Both scenarios seem legit to me, I don't have the data, but I think you can make the call based on # of Azure SF customers, I'd guess it's non-negligible compared to AWS/onprem/whatnot

**Comment by masnider** [comment]
Sure but 

1. We have not seen this being a huge complaint and
2. It causes the cadence issue that I mentioned in my first reply
3. It causes the "two mechanisms" mentioned in my first reply

I get what you are saying but it hasn't been a big problem (really ever) and it causes a bunch of things that would have to be worked through. For these reasons, as I said, it's unlikely that this will change any time soon.
