### ISSUE TITLE
Standard Output Console Redirection to a specified file

### ISSUE THREAD

**Issue by code-surf-er** [Azure/service-fabric-issues#1355]
Is it possible to redirect standard output to a specified file in a folder e.g. C:\Logs\ ? It works with ConsoleRedirection tag where it stores it in the working folder but when the application crashes Service Fabric cleans up all folders including the log folder which would have contained valuable information.

Note: I HAVE to use Console.writeline() since I call native code and I am unable to change console.SetOut for Native code from within Service Fabric.

**Comment by masnider** [comment]
I don't think that we have a way to direct the console output elsewhere, because SF doesn't know what places the service has access to write to. Is that other native code you call your own, or do you have access to it?

> when the application crashes Service Fabric cleans up all folders including the log folder

Hm, Service Fabric doesnt generally clean up the application's working directories aggressively, so I'm surprised that the file is getting cleaned up that quickly. Can you show us where you're looking and what you see when the app is running and then it disappearing?

> I am unable to change console.SetOut for Native code from within Service Fabric.

Service Fabric doesn't control what type of code you run. Do you have a mechanism for redirecting that works for a general console project or exe that doesn't work when you have SF launch that same exe? Something like [this](https://stackoverflow.com/questions/1412288/suppress-3rd-party-library-console-output)? If so we can try to figure out why that doesn't work for you when you host via SF.

**Comment by masnider** [comment]
Closed as we have not heard from you in a while. If you are still having this issue or experiencing problems, please feel free to reopen or open a new issue with a repro and we can take a look.
