### ISSUE TITLE
Multiple versions of a service fabric service

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#1361]
We have a microservices architecture hosted on service fabric that has 4 microservices. Services include a Router service, Provisioner Service, Registry Service, Backend Service. The architecture is depicted in the image aswell.
![image](https://user-images.githubusercontent.com/15942196/48616654-0a3eaf00-e9b6-11e8-8a36-ac9d6445d781.png)

The workflow is such that router is the only public facing service of the cluster, a request comes into the router and router checks if there is a backend for that particular request or not. If not router asks the provisioner to setup a back-end and if the backend is already there the router simply routes the request.
The metadata for provisioning the service comes from Registry service.
What we want to have is that we are able to have more than one version of backend service and based on some parameter in user request we ask the provisioner to instantiate a specific version of backend.
Is this possible without creating out new application for each version of backend?

**Comment by usamaazhar** [comment]
any comments @masnider  @ashishnegi

**Comment by guibirow** [comment]
The only way I can see you doing that without creating a new Application is registering multiple package versions inside the same application manifest. But this would be to complex to maintain also would make your application package very big.

I would recommend you create:

- one application per service, or, 
- create one application per version, and then create the services for each version in their respective applications

This approach will make much simple to maintain multiple different versioning.

**Comment by usamaazhar** [comment]
Our backend service resides in a different application and the other 3 mircoservice are in separate application. 
So you are recommending to create a new application each time we want to publish a new version for backend ?
I would be interested in knowing what that exactly means? I mean what really needs to change in the code base to create a new application? Are you recommending to change the application type name in the application manifest each time ?

Thanks

**Comment by guibirow** [comment]
When you register a package in SF, you are registering an application type and version. 
Whenever you update any of the services within the application, a new application version will be generated. 
Each new version will have the same type but the package version will be different.


When you create an application, you have to define the AppType and the Version. 
It is no possible to have one Application from an AppType targeting multiple versions, technically, not possible to have multiple services versions as well (without workaround). 

With this limitation, if only one of these services needs an upgrade, you have to upgrade the Application and then all the services of same type within the application will change in the upgrade.

.

The solution is having one application per version, and every time you create a new service targeting a version, you create the service within the application already created. Or one application per service.

Example: Your current scenario you have the application type BackendAppType@1.0 and create an instance as BackendApp and a service of name SvcV1 (fabric:/**BackendApp**/Svc**V1**) and then you want to keep SvcV1  and deploy V2, you can't have (fabric:/**BackendApp**/Svc**V2**) targeting different versions.

The approach would be create the App as (fabric:/BackendApp**V1**/Svc) and when a new version comes along, you create the (fabric:/BackendApp**V2**/Svc)

- Create within the same application based on version: 
  - fabric:/BackendAppV1/Svc123 _(BackendAppType@1.0)_
  - fabric:/BackendAppV1/Svc456 _(BackendAppType@1.0)_
  - fabric:/BackendAppV1/Svc789 _(BackendAppType@1.0)_
  - fabric:/BackendAppV2/Svc246 _(BackendAppType@2.0)_
  - fabric:/BackendAppV2/Svc802 _(BackendAppType@2.0)_


Having one application per service, makes much more flexible to upgrade each service individually and keep multiple versions running side by side. Based on the above approach, if you plan to have multiple instances of same version, you could:

- Create each on their own app even though they target same version:
  - fabric:/BackendApp123/Svc _(BackendAppType@1.0)_
  - fabric:/BackendApp456/Svc _(BackendAppType@1.0)_
  - fabric:/BackendApp789/Svc _(BackendAppType@1.0)_
  - fabric:/BackendApp246/Svc _(BackendAppType@2.0)_
  - fabric:/BackendApp802/Svc _(BackendAppType@**2.1**)_

> PS: The above example represents: fabric:/AppName/ServiceName _(AppType@version)_

The application type should stay the same, because it will make easier to upgrade from older versions, otherwise, you will have to remove the old version and create a new one targeting the new type.

**Comment by usamaazhar** [comment]
Yes makes sense now. We create the service today using [CreateServiceAsync ](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.servicemanagementclient.createserviceasync?view=azure-dotnet#System_Fabric_FabricClient_ServiceManagementClient_CreateServiceAsync_System_Fabric_Description_ServiceDescription_)method of fabric client. Where we provide the service description as a parameter
