### ISSUE TITLE
Service Fabric support for Availability Zones

### ISSUE THREAD

**Issue by pamedasa** [Azure/service-fabric-issues#1363]
Currently we have RDFE based PaaS service running in every region and wanted to move away from RDFE dependency. We are thinking of to use VMSS (or) Service fabric runs on top of VMSS.  We also wanted to use availability zones for high availability. Could you please suggest which suits better for our requirement in context of high avialability?

**Comment by masnider** [comment]
Generally we say that most apps would make sense to utilize Service Fabric on top of VMSS, since you get some benefits in terms of scalability and density. That said, at this moment, Multi-AZ VMSS aren't supported by Service Fabric for a couple internal reasons. This should be getting resolved soon.

**Comment by pamedasa** [comment]
Is there any ETA/Timeline to enable zonal support for SF deployments as well?

**Comment by pamedasa** [comment]
To add up one more query, does Service fabric of type Azure Ring-0 service?

**Comment by guibirow** [comment]
@masnider if possible, would be nice to know some of these reasons we can't have Multi-AZ VMSS, would avoid us designing cluster with these limitations in mind.

I had the impression this would be possble, because the VMSS [docs ](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones)says it is possible .

**Comment by aljo-microsoft** [comment]
@pamedasa and @guibirow 
https://github.com/Azure-Samples/service-fabric-cluster-templates/tree/master/9-VM-Windows-Cross-AZ-UnSecure

There isn't a timeline to provide publicly.

Ring-0 doesn't mean anything publicly, and again we don't support this yet. 

If you meant by Ring-0, can you deploy an on Prim cluster by yourself, that is distributed geographically across your own data-centers fault domains; Yes. SF doesn't care where its located, as long as network connectivity is sufficient, and above is the template for how to do this.

Key Note from the Readme found at the above link:
"The main intent for this template is to show how you can stitch a cluster across three Azure Zones. Since this tempalte deploys only an unsecure cluster, it is not for production use."

So although you can do this, its not recommended for production scenarios (Specifically its not ready for Stateful workloads, which SF is a Stateful application, so it and your stateful applications should not be deployed in this configuration yet for production scenarios),

**Comment by pamedasa** [comment]
we are having stateless services and main reasons to switch to SF is to gain AZ support which is smoother when compared to AZ support on RDFE based deployments and remove the dependency on RDFE.
