### ISSUE TITLE
On-Premise cluster upgrade failing 6.3->6.4

### ISSUE THREAD

**Issue by PepijnGramberg** [Azure/service-fabric-issues#1382]
When trying to update our on premise cluster (5 vms) from 6.3.187.9494 to 6.4.187.9494. However after the upgrade of the first machine(UD) it does not rejoin the cluster and after the healthcheck timeout a rollback is being done.
I tried the upgrade multiple times but the same thing happens.

Looking at the eventlogs I can find the following events:
Windows application log
```
Faulting application name: Fabric.exe, version: 6.4.617.9590, time stamp: 0x5bf55547
Faulting module name: CONCRT140.dll, version: 6.3.9600.19153, time stamp: 0x5b93ffa7
Exception code: 0xc0000135
Fault offset: 0x00000000000ecf30
Faulting process id: 0xe94
Faulting application start time: 0x01d49069f1aa5e55
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Fabric.exe
Faulting module path: CONCRT140.dll
Report Id: 2f594c45-fc5d-11e8-814d-00155d128f09
Faulting package full name: 
Faulting package-relative application ID: 
```
Windows system log
`The Service Fabric Installer Service service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.`

If more information is required I'll happily supply it.

**Comment by masnider** [comment]
This is a known issue that is fixed in 6.4.622.9590, which should be rolled out and available for you to upgrade to. This fixes the issue, which was that the VCRedist was not being installed correctly in some cases for clusters which were initially created ~6.1. Please give it a try and let us know if you're successful or if you have any other issues.

**Comment by maburlik** [comment]
When you are upgrading from 6.3, go directly to 6.4.622 to have the issue be auto resolved. This is happening because the VC++14 redistributable was not being invoked for cluster upgrade. This is now being done in the new version.

If you want to manually mitigate and install 6.4.617 you can install the vcredist on each node from "%ProgramFiles%\Microsoft Service Fabric\bin\fabricdrop\bin\Fabric\Fabric.Code\vc14_redist.x64.exe", which is carried in 6.3.

**Comment by PepijnGramberg** [comment]
Upgrade to 6.4.622 completed without issues.

**Comment by Lemraj** [comment]
Yes! the new version 6.4.622.9590 solved my problem also. One thing is that status of the cluster now set to Failed. Anyone knows why?

**Comment by ravibhooshan** [comment]
it helped thanks
