### ISSUE TITLE
Clear Health Report errors from Cluster

### ISSUE THREAD

**Issue by Pete1138** [Azure/service-fabric-issues#1385]
We have health errors showing against the cluster that have been raised in code (FabricClient.HealthManager.ReportHealth - both ServiceHealthReport and DeployedServicePackageHealthReport).

The TTL was set, but not the "RemoveWhenExpired" flag. These errors never clear and they prevent upgrades in monitored mode.

We have tried raising "Ok" Health Reports via powershell (Send-ServiceFabricDeployedApplicationHealthReport and Send-ServiceFabricDeployedServicePackageHealthReport) to replace the errors, but this does not work.

Is it possible to remove these without re-installing the cluster? If there is no official way supported in the SDK then we are open to hacking/deleting files if necessary. Where does the cluster read the health report from (is it a file on disk)?

**Comment by oanapl** [comment]
@Pete1138 , your approach - reporting through Powershell should work.
Send a report for the same source and property, small TTL (1 sec) and RemoveWhenExpired.
The important part is that **the sequence number on the new report must be higher than the sequence number of the report that's persisted**. Otherwise, the report is rejected as stale. 
So look at the existing report, take the sequence number and add 1 and try sending again.

**Comment by oanapl** [comment]
@Pete1138 , I will close the issue based on the above. If you still have questions, feel free to reopen or open a new issue.
