### ISSUE TITLE
[Feature Request]UseImplicitHost for StatefulServices

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#139]
It would be nice to be able to run a guest executable with a soft guarantee that it's the only instance alive. It would be even better to be able to run containers this way (as a stateful service).

No replication - just leases and the guarantee to terminate process/container whenever replica looses it's primary status.

**Comment by masnider** [comment]
Would running it as a stateless service with an instance count of 1 be sufficient? Or what are you trying to guarantee?

**Comment by mkosieradzki** [comment]
I would like to guarantee that at a given time there is no more than one active instance of a service. I don't think it is guaranteed by stateless service with instance count = 1?

**Comment by masnider** [comment]
Not quite, but then I'm not sure what "soft" means to you. What are you relying on this for?

**Comment by mkosieradzki** [comment]
By soft I mean that a hosted process has been notified by ctrl+c - that it is no longer active.

**Comment by masnider** [comment]
Guest exes would get that if there were only instance count of 1, but there may be multiple instances running (not in the normal path, but if there were an upgrade or a failure multiple may get temporarily started and then shut down).

**Comment by mkosieradzki** [comment]
Yes. That's exactly what I am affraid - if there is a state managed by such an executable its host needs to track the leases and send ctrl+C whenever lease expires. Such a host would be usefull when porting systems from Java-based application servers as a replacement for singleton service or when you want to implement a "stateful service" on a different platform, for example NodeJS.

But this one is even better as it might support partitioning :).

What I am trying to point out is that Stateful Services provide a great value even **without** Reliable Collections (which are epic BTW) - they are just great in multiple cache scenarios that are hard to achieve different way. They can also offer local in-process locking mechanisms.

Combined with Reverse Proxy which will retry communication as many times as needed in case of a failure it provides a nice xplat programming model! Even without replication or SF-backed durability.

Of course such a host could pass some settings through the environment variables to the underlying process including associated endpoints etc. It will also work great with containers.

Such a host should not be that difficult to implement outside of the core SDK however it's something that can really benefit from the config-file integration.

**Comment by masnider** [comment]
Currently what you're talking about is only available through the reliable services programming model. We may consider doing something like you're talking about in the future, but in practice we've seen people do the following to solve your problem

- Have an empty stateful service which does the actual work you're talking about
- Have an empty stateful service that serves as a proxy between the workload and the backing store and ensures that there is only ever a single writer at a time. 
- Have the application level use existing store primitives (locks and timeouts implemented by the backing data store, blob leases, whatever) to ensure that there is only one writer and that data remains correct. 

The last is most common since that is how almost all "stateless frontend with backing stateful store" type services work today. Hence this hasn't been a big priority for us. Also today the notion of primary or being the single writer is tied fairly tightly to our actual APIs, and pulling it out and marrying it to something like just a process lifecycle would be a significant effort. 

I've marked this as a potential enhancement, but for now it is won't fix (at least not any time soon). If we see this being a big request we may come back to it some day. In the meantime the other architectures should work for people.

**Comment by mkosieradzki** [comment]
I definitely agree, thanks @masnider for your detailed response.

**Comment by masnider** [comment]
No problem. Thanks @mkosieradzki
