### ISSUE TITLE
Runtime, SDK come with not the latest C++ 2017 Runtime

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#1397]
Installing SF Runtime, SDK using Web Platform Installer brings Visual C++ 2017 version 14.12.25810 while the latest is [14.16.27012](https://aka.ms/vs/15/release/VC_redist.x64.exe).

The same for Visual C++ 2012. WPI installs version 11.0.51106 while the latest is [11.0.61030](https://www.microsoft.com/en-us/download/details.aspx?id=30679).

Moreover, SF Runtime, SDK installation will fail if a greater version of C++ Runtime is already installed, because that's how C++ installer behaves: you can install lower version first, then greater. But not the other way around. So it returns an error and the fails the whole insulation.

**Comment by abatishchev** [comment]
Ping.

**Comment by maburlik** [comment]
The above should not be happening for VC++14.x since it does a lookup on the installation state and min version in the registry. If you are still hitting this please include the WebPI and VC++ installation logs. We talked about this over IM.

As for VC++11 there was a bug in the WebPI feed for the lookup pattern so at times it may attempt to install this when it's already present. We've seen previously that vcredist installation get blocked by pending Windows Updates so running the installation unnecessarily has some risk of blocking SF installation. I've sent a PR to update the global WebPI feed so you should see the change reflected within a few business days.

Let me know if you are still hitting any issue regarding VC++14 and we can follow up.
