### ISSUE TITLE
Application Upgrade is Stuck

### ISSUE THREAD

**Issue by shlatchz** [Azure/service-fabric-issues#14]
I've deployed a new version of my service fabric app to azure and it got stuck on the 2nd domain. After I waited for an hour I disrupted the upgrade with `Start-ServiceFabricApplicationRollback` and now it's stuck in rollback.

Why does it work so poorly? 

The last time it happened, I had to recreate the whole fabric. 

This is really really annoying.

**UPDATE**

The rollback is actually progressing...

Why is it so sloooooooow?

**Comment by masnider** [comment]
can you Get-ServiceFabricApplicationUpgrade and share that information? Before you interrupted the upgrade, did you look at the status to see what parts of the safety checks were taking a long time to pass? Usually the info there is a pretty good indicator of what is going on. Does this happen every time that you try to upgrade? If it is reproducible what do the events/traces coming out of your service indicate? Usually this type of slowness is an indication that the service isn't shutting down cleanly. If it is a ReliableService based service, usually this is because the cancellation token we pass to RunAsync is not being respected, but that's just one possibility.

**Comment by vturecek** [comment]
@shlatchz I'm going to close this out since we haven't heard back for a while. If you run into it again, just re-open this.

**Comment by krvladislav** [comment]
Hi.

I am currently dealing with the same problem.

I deployed a SF container application to a cluster. There was incorrect container repository credentials in manifest, so the app was in a error state. It was 1.0.0 version.

Then I initated a new version 1.0.1 deploy but without fixing credentials so it also errorneous.

Output of Get-ServiceFabricApplicationUpgrade: 
```
ApplicationName               : fabric:/testApplication
ApplicationTypeName           : testApplicationType
TargetApplicationTypeVersion  : 1.0.1
ApplicationParameters         : { "test_Isolation" = "hyperv";
                                "ElasticSearch_InstanceCount" = "-1";
                                "Kibana_InstanceCount" = "-1" }
StartTimestampUtc             : 9/19/2018 5:25:22 AM
UpgradeState                  : RollingForwardInProgress
UpgradeDuration               : 00:23:02
CurrentUpgradeDomainDuration  : 00:22:02
CurrentUpgradeDomainProgress  : 1

                                NodeName            : _vm_1
                                UpgradePhase        : Upgrading
NextUpgradeDomain             : 1
UpgradeDomainsStatus          : { "0" = "Completed";
                                "1" = "Pending";
                                "2" = "Pending";
                                "3" = "Pending";
                                "4" = "Pending" }
UpgradeKind                   : Rolling
RollingUpgradeMode            : UnmonitoredAuto
ForceRestart                  : False
UpgradeReplicaSetCheckTimeout : 00:00:01
```

Output of Cloud.xml
  ```
<UpgradeDeployment Mode="UnmonitoredAuto" Enabled="true">
    <Parameters UpgradeReplicaSetCheckTimeoutSec="1" Force="True" />
  </UpgradeDeployment>
```

Now I get "An upgrade for the application  is already in progress" error when I try to publish next version 1.0.2.

To cancel the application upgrade I use command Start-ServiceFabricApplicationRollback

The rollback also hangs because the previous version of application is in error state.

Output of Get-ServiceFabricApplicationUpgrade:

```
ApplicationName               : fabric:/testApplication
ApplicationTypeName           : testApplicationType
TargetApplicationTypeVersion  : 1.0.0
ApplicationParameters         : { "test_InstanceCount" = "-1";
                                "test_Isolation" = "default";
                                "ElasticSearch_InstanceCount" = "-1";
                                "Kibana_InstanceCount" = "-1" }
StartTimestampUtc             : 9/19/2018 5:25:22 AM
FailureTimestampUtc           : 9/19/2018 5:50:25 AM
FailureReason                 : Interrupted
UpgradeState                  : RollingBackInProgress
UpgradeDuration               : 01:01:09
CurrentUpgradeDomainDuration  : 00:35:02
CurrentUpgradeDomainProgress  : 4

                                NodeName            : _vm_4
                                UpgradePhase        : Upgrading
NextUpgradeDomain             : 4
UpgradeDomainsStatus          : { "0" = "Completed";
                                "1" = "Completed";
                                "2" = "Completed";
                                "3" = "Completed";
                                "4" = "Pending" }
UpgradeKind                   : Rolling
RollingUpgradeMode            : UnmonitoredAuto
ForceRestart                  : False
UpgradeReplicaSetCheckTimeout : 00:00:01
```

In my case the application is stateless and it is already destroyed so I can delete and recreate the application.

But what can I do to proceed further without loss? What to do if an application is stateful?  Is there an option to force new upgrade?

**Comment by MikkelHegn** [comment]
Some of these topics were discussed here: https://github.com/Azure/service-fabric-issues/issues/1279
