### ISSUE TITLE
How to uninstall Azure Service Fabric Runtime using Powershell?

### ISSUE THREAD

**Issue by v-etzha** [Azure/service-fabric-issues#1401]
Hi experts,
I want to uninstall Service Fabric using the PowerShell. I can successfully uninstall Service Fabric SDK by the following command, 
![image](https://user-images.githubusercontent.com/34734408/50418274-8524a080-0865-11e9-892c-dc66427de9e6.png)
but don't know how to uninstall Service Fabric Runtime. Could you please share some guideline here? Thank a lot!

**Comment by anantshankar17** [comment]
@v-etzha it seems win32_product has several issues because of which it doesnt list all the installed products.
You might want to give this script a try to achieve what you want as this script queries the registry instead: https://gallery.technet.microsoft.com/scriptcenter/Get-RemoteProgram-Get-list-de9fd2b4
![image](https://user-images.githubusercontent.com/39825466/50505691-2d6f7a80-0a9b-11e9-9c97-ab37303a50b5.png)

**Comment by v-etzha** [comment]
@anantshankar17 Thanks for your sharing! I tried the script and got the required products, but when I tried to run app.Uninstall(). It failed. 
![image](https://user-images.githubusercontent.com/34734408/50507962-b77b0b80-0aba-11e9-8567-e03cd1179cc7.png)
It seems the value that Get-RemoteProgram returns is different from what Get-WmiObject returns. Is there an approach to uninstall the queried products by Get-RemoteProgram?

**Comment by anantshankar17** [comment]
I did look around a little and it seems the win32_product class has several issues because of which it will not list apps which aren't installed by an msi. 
https://community.idera.com/database-tools/powershell/ask_the_experts/f/powershell_for_windows-12/22674/get-wmiobject--class-win32_product-doesn-t-list-all-installed-applications

The script I shared earlier will just get all the app names, but will not be able to uninstall the runtime. https://gallery.technet.microsoft.com/scriptcenter/Get-RemoteProgram-Get-list-de9fd2b4

To uninstall the runtime using a script, you can directly call this anyways as a workaround: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\CleanFabric.ps1

**Comment by v-etzha** [comment]
Thanks for the help! I will try the workaround above.
