### ISSUE TITLE
ImageStore crashing and Application deletion stuck

### ISSUE THREAD

**Issue by Richard-Payne** [Azure/service-fabric-issues#1407]
We have an issue with our on-prem Service Fabric.  It has started crashing the ImageStoreService whenever we try to register a new version of an application package.

We're running 5 primary nodes and, when we call Copy-ServiceFabricApplicationPackage, the imagestoreservices on all of them fail at the same time.

How do I diagnose this fault?  Where are the logs for the SF system services?

This occurred while an application upgrade was in process and has resulting in the upgrade hanging.  We tried deleting the application but it failed:

```
PS C:\WINDOWS> Get-ServiceFabricApplication  fabric:/App


ApplicationName           : fabric:/App
ApplicationTypeName       : AppType
ApplicationTypeVersion    : 21.79C839
ApplicationStatus         : Deleting
HealthState               : Ok
ApplicationDefinitionKind : ServiceFabricApplicationDescription
ApplicationParameters     : {}



PS C:\WINDOWS> Get-ServiceFabricService fabric:/App/Service
Get-ServiceFabricService : Application not found
At line:1 char:1
+ Get-ServiceFabricService fabric:/App/Service ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabricService], FabricElementNotFoundException
    + FullyQualifiedErrorId : GetServiceErrorId,Microsoft.ServiceFabric.Powershell.GetService

PS C:\WINDOWS> Get-ServiceFabricNode | % { Get-ServiceFabricDeployedReplica -ApplicationName fabric:/App -NodeName $_.NodeName }
PS C:\WINDOWS> Remove-ServiceFabricService fabric:/App/Service -ForceRemove -Force
Remove service succeeded
PS C:\WINDOWS> Remove-ServiceFabricApplication fabric:/App -ForceRemove -Force
Remove-ServiceFabricApplication : Operation timed out.
At line:1 char:1
+ Remove-ServiceFabricApplication fabric:/App -ForceR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Remove-ServiceFabricApplication], TimeoutException
    + FullyQualifiedErrorId : RemoveApplicationInstanceErrorId,Microsoft.ServiceFabric.Powershell.RemoveApplication

PS C:\WINDOWS>
```

So there's no left over replicas, the service deletes successfully but the application delete times out.

**Comment by oanapl** [comment]
@Richard-Payne , what Service Fabric version are you using on the cluster and on the client (the machine where you start deployment from)? How are you doing the deployment (VSTS, Powershell scripts etc)?

For the imagestoreservice crashing, do you have any dumps for the imagestoreservice? You can try re-running the copy package command for a new repro if needed and collect it (if you don't have automatic dump collection). 
To see logs for system services, you can start with [SF event store](https://docs.microsoft.com/azure/service-fabric/service-fabric-diagnostics-events), if you have it enabled. You can also try the event viewer on the nodes themselves to see if there are any warning and errors belonging to Service Fabric. See more at [monitoring the cluster article](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-generation-infra).

If you can't figure it out, please [open a support ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview) and provide the dumps and [the Service Fabric traces](https://docs.microsoft.com/eazure/service-fabric/service-fabric-diagnostics-event-generation-infra#service-fabric-support-logs) and we will take a look.

Re. app deletion timing up, it may be because the upgrade was in progress at the time. What timeout did you provide to the delete operation? Looks like the operation was accepted and then processed in an internal retry if all services and replicas are currently deleted. If you re-try the delete, do you still get a timeout or an error that the app doesn't exist anymore?

**Comment by iyyappam** [comment]
Since you have mentioned image store service has crashed, could you provide us the dump of that process too.  You can get the dump from the location mentioned in the "WinFabCrashDump" section of ClusterManifest.

**Comment by oanapl** [comment]
@Richard-Payne , we haven't heard back from you in a while. I will close this issue due to inactivity. If this is still happening, feel free to re-open and provide us more info so we can continue investigation.

**Comment by idang100102** [comment]
Hi all,
Where can I find general guidance on detecting Service Fabric application crash/stuck and automatic dumps ?
Thanks

**Comment by iyyappam** [comment]
It is usually uploaded to a storage account mentioned in the Cluster Manifest.
Look for this fabric setting in your cluster manifest "AzureBlobServiceFabricCrashDump".
