### ISSUE TITLE
"An existing connection was forcibly closed by the remote host" error under user load on ASF cluster

### ISSUE THREAD

**Issue by sohailskb** [Azure/service-fabric-issues#1415]
We are seeing this exception repeatedly when running a load test on Azure service fabric cluster

Load test details:
Constant user load: 45
Azure service fabric node config: D2V2(2core/7gig)
Number of nodes : 5

Load Runs <40 users product no errors, the errors start happening >40 users. 

The tests are doing below steps:
- Get OAuth2 token from Microsoft
- Get entitlement token from auth service in our Api - This is where the requests start to fail @ loads of over 40 users..

Any inputs are much appreciated..

1 primary requests, 0 dependant requests and 0 conditional rules failed Exception (subtype 'SocketException') occured at 01/17/2019 08:41:23 (UTC) for Uri 'https://*.*.*.com/api', step #4 with the error 'An existing connection was forcibly closed by the remote host', exception text 'System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult) at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult) --- End of inner exception stack trace --- at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult) at System.Net.TlsStream.EndRead(IAsyncResult asyncResult) at System.Net.Connection.ReadCallback(IAsyncResult asyncResult) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at Microsoft.VisualStudio.TestTools.WebStress.WebTestTransaction.ResponseReceived(IAsyncResult result)', stack trace ' at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult) at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)'.

**Comment by ashishnegi** [comment]
If you are using service fabric sdk, then in Open/Close async you are opening/closing your listeners/port.
When service process goes down/restarted, essentially the network connections are broken.

Your service can go down because of service bug or by service fabric if it is moving it to another node.

You need to tell more about your service : stateless or stateful, replica/instance count, placement constraints if any. Also, please answer prior questions. With these details, we can tell if you need to look into your service for bugs or not.

I also hope you have done the profiling of your service with one instance on a single machine to get basic numbers.

**Comment by masnider** [comment]
Hi @sohailskb, we haven't heard back from you here, so I'm going to close down this issue. As @ashishnegi indicated, SF isn't really in this communication flow for the most part, or we'd need more information in order to point to SF as a part of the problem here. Hope you've been able to troubleshoot this issue further. If you're still seeing issues with a newer release of SF, please go ahead and open another issue or reopen this one and provide more information about how communication in your services is handled and whether you see any of the indicators that Ashish pointed out.
