### ISSUE TITLE
Documentation & guidance on enabling Accelerated Networking

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#1423]
Please enable accelerated networking by default in Azure Service Fabric & Mesh clusters, expose this option via Azure Portal and ARM templates, and provide best practice documentation and guidance on how to enable this feature for existing Service Fabric clusters with zero downtime.

When accelerated networking is enabled on a VM, there is lower latency, reduced jitter, and decreased CPU utilization on the VM.

**Comment by aljo-microsoft** [comment]
@MedAnd 

The following will be published in our docs shortly:

Maximize your Virtual Machine’s performance with Accelerated Networking, by declaring enableAcceleratedNetworking property in your Resource Manager template, the following is a snippet of a Virtual Machine Scale Set NetworkInterfaceConfigurations that enables Accelerated Networking:

```json
"networkInterfaceConfigurations": [
{
"name": "[concat(variables('nicName'), '-0')]",
"properties": {
"enableAcceleratedNetworking": true,
"ipConfigurations": [
{
<snip>
}
],
"primary": true
}
}
]
```
Service Fabric cluster can be provisioned on [Linux with Accelerated Networking](https://docs.microsoft.com/azure/virtual-network/create-vm-accelerated-networking-cli), and [Windows with Accelerated Networking](https://docs.microsoft.com/azure/virtual-network/create-vm-accelerated-networking-powershell).

Accelerated Networking is supported for Azure Virtual Machine Series SKU's: D/DSv2, D/DSv3, E/ESv3, F/FS, FSv2, and Ms/Mms.

To enable Accelerated Networking on an existing Service Fabric cluster, you need to first [Scale a Service Fabric cluster out by adding a Virtual Machine Scale Set](https://docs.microsoft.com/azure/service-fabric/virtual-machine-scale-set-scale-node-type-scale-out), to perform the following:
1. Provision a NodeType with Accelerated Networking enabled
2. Migrate your services and their state to the provisioned NodeType with Accelerated Networking enabled

Scaling out infrastructure is required to enable Accelerated Networking on an existing cluster, because enabling Accelerated Networking in place would cause downtime, as it requires all virtual machines in an availability set be [stopped/deallocated before enabling Accelerated networking on any existing NIC](https://docs.microsoft.com/azure/virtual-network/create-vm-accelerated-networking-cli#enable-accelerated-networking-on-existing-vms)

This content will be added to our public documentation in the coming week. Although I'm closing this as I've provided the content requested, please reopen if you feel your issue was not resolved by the content I provided.
