### ISSUE TITLE
Possible security vulnerability when cluster certificate specified by common name

### ISSUE THREAD

**Issue by inech** [Azure/service-fabric-issues#1458]
My cluster was using a certificate specified by a thumbprint 'xxx_0', so I was only able to login to SF explorer using this specific certificate which I think is secure enough.

Later, I decided to switch my cluster to use a certificate specified by a common name, so I did the following:
1. I've obtained a certificate from a trusted CA (e.g. GoDaddy) with a common name 'example.com'.
2. Installed it to the cluster nodes.
3. (**Expected**) I'm able to login to SF explorer using this certificate which is good.

After that, I can imagine that some hacker does the following:
1. The hacker somehow tricks Let's Encrypt to believe that he owns 'example.com' domain and gets a certificate for it.
2. (**Not expected**) Logs in to my cluster's SF explorer using his certificate from Let's Encrypt even though his certificate is not installed on the cluster nodes.

So now I don't believe that my cluster is secure enough because if any CA around the globe has a vulnerability and issues a certificate with the common name 'example.com' for a hacker it would mean this hacker automatically gets access to my cluster. 

Until I've discovered such behavior I thought that it's not enough to have any valid certificate with the common name 'example.com' I thought certificate should also be installed on cluster nodes before it can be used to access cluster management.

**Comment by MikkelHegn** [comment]
@dragav

**Comment by dragav** [comment]
There are a couple of points to address here:
- proving domain ownership is not that easy; in the scenario where a PKI issues a certificate for your domain to an attacker, either the attacker assumed ownership of your IP (and which is bound to your domain name), or the PKI's Registration Authority has a flaw it its domain ownership verification logic. In either case, this is a significant bar.
- when you authenticate to the cluster as a client, you present proof of ownership of the private key associated with that certificate. The cluster does not need to have your certificate in order to authenticate you - irrespective of whether the cert is declared by thumbprint or subject + issuer. You're not inherently less secure with the latter, assuming you obtained your certificate from a well-known issuer. The validation of a cert declared by CN is, in fact, stricter - rather than comparing thumbprints only, the certificate must be issued by either a specified issuer or end up in a trusted root.
- it's always a good practice to specify the issuer thumbprint when declaring a certificate by (subject) common name.
