### ISSUE TITLE
Unable to upgrade application on one node cluster

### ISSUE THREAD

**Issue by jfalameda** [Azure/service-fabric-issues#1483]
Hi,

I have a one node cluster where I host my application. The first time I deploy the application it works as expected, but once I upgrade the application it freezes.

I have observed that all services that do not have InstanceCount -1 get into warning state, therefore blocking the upgrade. Below the image of one of the services showing the warning.

![image](https://user-images.githubusercontent.com/287670/55195301-65767e80-51ac-11e9-9cb7-b85ad38dbc2d.png)

I do not know how to proceed, because the only way to put new versions in production is by recreating the application and do not RollForward.

Thanks in advance.
José.

**Comment by ashishnegi** [comment]
Is this your local dev cluster ? You can create a 3 or 5 node local dev cluster for trying out your app.

I see yours is a stateful service. Before we bring down your primary to upgrade the code package, we need to bring another secondary replica so that we don't have any data loss during upgrade.
However, since you have only one node, SF's Cluster Resource Manager (CRM) can't find another node to place the secondary replica.
