### ISSUE TITLE
Service fabric runtime installation issue

### ISSUE THREAD

**Issue by TehseenNawaz** [Azure/service-fabric-issues#1498]
Hi, 
I uninstall the previous version-6.4.622 of service fabric. Now i am trying to install service fabric runtime 6.4.654 and SDK 3.3.654 using Web Platfrom Installer. But it failed during the installation of service fabric runtime-6.4.654. 

![sf](https://user-images.githubusercontent.com/41328964/56356177-83566280-61f1-11e9-8cc7-9a454d49f9c8.PNG)

I tried to install the previous uninstalled version 6.4.622 by running service fabric runtime executable(**MicrosoftServiceFabric.6.4.622.9590.exe**) its also failed.

**Comment by anantshankar17** [comment]
Can you check the log file to look for the error ? Also, can you try "sc stop docker" from an admin cmd prompt and then retry ?

**Comment by TehseenNawaz** [comment]
Here is the Log file
[Log.txt](https://github.com/Azure/service-fabric-issues/files/3094061/Log.txt) 

And i ran command as an admin here is the result of cmd:
![sf2](https://user-images.githubusercontent.com/41328964/56356919-923e1480-61f3-11e9-9cd6-57a09fccc459.PNG)

**Comment by anantshankar17** [comment]
Can you check if the runtime is already installed on your PC? If it is, kindly remove it manually. 
Also, remove the dir "C:\Program Files\Microsoft Service Fabric". Reboot your PC and try again ?

**Comment by pascal-hauser** [comment]
I also have an issue installing Service Fabric that looks the same. Same message and log content looks similar at the end and also "sc stop docker" shows the same message.
When I try install the runtime from an admin command prompt I get the following output.
<img width="818" alt="ServiceFabricInstallError" src="https://user-images.githubusercontent.com/38853147/56768630-2b9a9700-67af-11e9-834f-44354ab21911.png">
The InstallFabricRuntime.log contains the same information.
[InstallFabricRuntime.log](https://github.com/Azure/service-fabric-issues/files/3118884/InstallFabricRuntime.log)
I made sure "Microsoft Service Fabric" folder is deleted and also rebooted and disabled AV software.
Any ideas?

**Comment by anantshankar17** [comment]
@pascal-hauser that means another instance is still running. Can you reboot the machine and retry ? Also try "sc stop com.docker.service"

**Comment by pascal-hauser** [comment]
@anantshankar17 yes, the message says so, but there is no other instance running. Docker service is stopped. Still the same problem. Running the MicrosoftSerivceFabricAutoextractor.exe manually succeeds, but this doesn't help as it is still not correctly installed. I tried on another machine, there it worked. Don't know if it is a problem that I have VS2019 installed or something else. Is there a way to install the Service Fabric Runtime more manually or diagnose the problem further?

**Comment by ShaunMcGuile** [comment]
I have exactly the same issue - no docker service Windows 10 - command line gets this far - 

C:\Windows\SysWOW64\WindowsPowerShell\v1.0>d:\downloads\MicrosoftServiceFabric.6.3.176.9494.exe /AcceptEULA
13/05/2019 10:58:04,Info,Start installation... Logs created at C:\WINDOWS\TEMP\InstallFabricRuntime.log
13/05/2019 10:58:04,Info,13/05/2019 11:58:04 running: Powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser
13/05/2019 10:58:04,Info,Service Fabric Product not detected in registry.
13/05/2019 10:58:04,Info,Found legacy fabric files at C:\Program Files\Microsoft Service Fabric. Start removal...
13/05/2019 10:58:04,Info,13/05/2019 11:58:04 running: Powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\CleanFabric.ps1'
13/05/2019 10:58:05,Info,Legacy Fabric Uninstalled using CleanFabric.ps1!
13/05/2019 10:58:05,Info,Try deleting C:\Program Files\Microsoft Service Fabric...
13/05/2019 10:58:05,Info,Successfully deleted C:\Program Files\Microsoft Service Fabric.
13/05/2019 10:58:05,Info,Start extracting runtime cab...
13/05/2019 10:58:05,Info,13/05/2019 11:58:05 running: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric" /E /Y
13/05/2019 10:58:09,Info,Successfully extracted cab file
13/05/2019 10:58:09,Info,Start installing...
13/05/2019 10:58:09,Info,13/05/2019 11:58:09 running: Powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -ACCEPTEULA
13/05/2019 10:58:09,Error,Unable to install Service Fabric Runtime using InstallFabric.ps1. ExitCode: 1

**Comment by anantshankar17** [comment]
@ShaunMcGuile/@pascal-hauser  can you please make sure the directory "C:\Program Files\Microsoft Service Fabric" is deleted and you rebooted the machine & "d:\downloads\MicrosoftServiceFabric.6.3.176.9494.exe /AcceptEULA" is being executed from an admin prompt ? 
Also can you check the C:\Windows\Temp\FabricSetupLog.log for errors ?

You can also execute the cmds manually to debug what is wrong here, like this after cleanup and reboot:
1. C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric" /E /Y
2. Powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -ACCEPTEULA
and check where exactly is the install failing ?

**Comment by ShaunMcGuile** [comment]
I have exactly the same issue, no docker, VS 2019 latest install and the log file has the identical Error 1 code.
has there been any progress with this?

**Comment by anantshankar17** [comment]
@ShaunMcGuile I'm trying to debug why it is failing for you, so can you try the above steps or share the C:\Windows\Temp\FabricSetupLog.log ?

**Comment by ShaunMcGuile** [comment]
> @ShaunMcGuile I'm trying to debug why it is failing for you, so can you try the above steps or share the C:\Windows\Temp\FabricSetupLog.log ?

There is no file named FabricSetupLog.log on the computer.

InstallFabricRuntime.log is this - 
C:\Windows\SysWOW64\WindowsPowerShell\v1.0> d:\downloads\MicrosoftServiceFabric.6.3.176.9494.exe /AcceptEULA
13/05/2019 13:02:29,Info,Start installation... Logs created at C:\WINDOWS\TEMP\InstallFabricRuntime.log
13/05/2019 13:02:29,Info,13/05/2019 14:02:29 running: Powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser
13/05/2019 13:02:30,Info,Service Fabric Product not detected in registry.
13/05/2019 13:02:30,Info,Start extracting runtime cab...
13/05/2019 13:02:30,Info,13/05/2019 14:02:30 running: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric" /E /Y
13/05/2019 13:02:34,Info,Successfully extracted cab file
13/05/2019 13:02:34,Info,Start installing...
13/05/2019 13:02:34,Info,13/05/2019 14:02:34 running: Powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -ACCEPTEULA
13/05/2019 13:02:34,Error,Unable to install Service Fabric Runtime using InstallFabric.ps1. ExitCode: 1

**Comment by ShaunMcGuile** [comment]
> @ShaunMcGuile I'm trying to debug why it is failing for you, so can you try the above steps or share the C:\Windows\Temp\FabricSetupLog.log ?

Appreciate your efforts. 👍

**Comment by anantshankar17** [comment]
> > @ShaunMcGuile I'm trying to debug why it is failing for you, so can you try the above steps or share the C:\Windows\Temp\FabricSetupLog.log ?
> 
> There is no file named FabricSetupLog.log on the computer.
> 
> I am running this from the command prompt as administrator
> 
> Fails on your step 2 - _Cannot process the command because of a missing parameter. A command must follow -Command._ with _The filename, directory name, or volume label syntax is incorrect_.
> 
> InstallFabricRuntime.log is this -
> C:\Windows\SysWOW64\WindowsPowerShell\v1.0> d:\downloads\MicrosoftServiceFabric.6.3.176.9494.exe /AcceptEULA
> 13/05/2019 13:02:29,Info,Start installation... Logs created at C:\WINDOWS\TEMP\InstallFabricRuntime.log
> 13/05/2019 13:02:29,Info,13/05/2019 14:02:29 running: Powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser
> 13/05/2019 13:02:30,Info,Service Fabric Product not detected in registry.
> 13/05/2019 13:02:30,Info,Start extracting runtime cab...
> 13/05/2019 13:02:30,Info,13/05/2019 14:02:30 running: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric" /E /Y
> 13/05/2019 13:02:34,Info,Successfully extracted cab file
> 13/05/2019 13:02:34,Info,Start installing...
> 13/05/2019 13:02:34,Info,13/05/2019 14:02:34 running: Powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -ACCEPTEULA
> 13/05/2019 13:02:34,Error,Unable to install Service Fabric Runtime using InstallFabric.ps1. ExitCode: 1

Since its the InstallFabric.ps1 which is returning the exitcode 1, I need you to run that to know what is the  error there. Can you run this command directly "&"C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1" -FabricRootIsPreInstalled -ACCEPTEULA " or the exe with /AcceptEULA? 

The FabricSetupLog.log should be generated either in the c:\windows\temp\FabricSetupLog.log or C:\Users\<your user>\AppData\Local\Temp\FabricSetupLog.log

**Comment by ShaunMcGuile** [comment]
There is no FabricSetupLog.log file on the computer - why am I having to repeat myself?

There is InstallFabricRuntime.log - the content of which was posted above.

I am running the command form the command prompt as administrator.
and this is the result I get -

 _Cannot process the command because of a missing parameter. A command must follow -Command_. 

The powershell help list, followed by - 

 _The filename, directory name, or volume label syntax is incorrect_.

This is all that there is - I have tried various combinations of  ',", {} () and also running the command script inside powershell and it complains about missing parameters.

Thanks.

**Comment by ShaunMcGuile** [comment]
The Web api installer gives this - 

DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webpifeed51
DownloadManager Information: 0 : https://aka.ms/webpifeed51 responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Location: https://webpifeed.blob.core.windows.net/webpifeed/5.1/WebProductList.xml
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Tue, 14 May 2019 08:25:12 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 14 May 2019 08:25:12 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains


DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/5.1/WebProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 03fec3b5-c01e-0032-122e-0a60b9000000
x-ms-version: 2009-09-19
Date: Tue, 14 May 2019 08:25:12 GMT


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\1460077924.xml.temp
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Resource Provider
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Terawe
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webapplicationlist
DownloadManager Information: 0 : https://aka.ms/webapplicationlist responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Location: https://webgallery.microsoft.com/feed/webapplicationlist.xml
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Tue, 14 May 2019 08:25:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 14 May 2019 08:25:14 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains


DownloadManager Information: 0 : Content-Encoding header: 'gzip'
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '65352'
DownloadManager Information: 0 : Number of bytes after possible decompression: '432604'
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webapplicationlist' after preprocessing, location on disk: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-966730450.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 03fec8f6-c01e-0032-4d2e-0a60b9000000
x-ms-version: 2009-09-19
Date: Tue, 14 May 2019 08:25:15 GMT


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\2000756975.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml' after preprocessing, location on disk: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\preprocessor\2000756975.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 03fec94d-c01e-0032-1d2e-0a60b9000000
x-ms-version: 2009-09-19
Date: Tue, 14 May 2019 08:25:15 GMT


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\609314840.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml' after preprocessing, location on disk: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\preprocessor\609314840.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 03fec9c1-c01e-0032-0b2e-0a60b9000000
x-ms-version: 2009-09-19
Date: Tue, 14 May 2019 08:25:15 GMT


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\140237651.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml' after preprocessing, location on disk: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\preprocessor\140237651.xml'
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webpifeed51' after preprocessing, location on disk: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\preprocessor\1460077924.xml'
DownloadManager Information: 0 : Getting ratings file from http://go.microsoft.com/?linkid=9752395
DownloadManager Information: 0 : Contextual entry products: MicrosoftAzure-ServiceFabric-CoreSDK
DownloadManager Information: 0 : Adding product Microsoft Azure Service Fabric SDK - 3.3.658 (MicrosoftAzure-ServiceFabric-CoreSDK) to cart
DownloadManager Information: 0 : Contextual navigation to product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : http://go.microsoft.com/?linkid=9752395 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Location: http://www.microsoft.com/web/handlers/WebPI.ashx?command=getatomfeedwithavgratingquery
Server: Kestrel
Request-Context: appId=cid-v1:26ef1154-5995-4d24-ad78-ef0b04f11587
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Tue, 14 May 2019 08:25:16 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 14 May 2019 08:25:16 GMT
Connection: keep-alive


DownloadManager Information: 0 : Number of bytes downloaded over the internet: '0'
DownloadManager Information: 0 : Number of bytes after possible decompression: '0'
DownloadManager Warning: 0 : Error getting last-modified header, error code: 12150
DownloadManager Warning: 0 : HttpQueryInfoWithRetry for HTTP_QUERY_LAST_MODIFIED failed.
DownloadManager Error: 0 : Error loading rating files: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Microsoft.Web.PlatformInstaller.ProductServiceImpl.GetAppRatings()
DownloadManager Information: 0 : Adding product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricSDK_3_3_CU6
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricRuntime_6_4_CU6
DownloadManager Information: 0 : Setting current install to 1
DownloadManager Information: 0 : Starting install sequence
DownloadManager Information: 0 : Using cached file at C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU6\80B01C5F5D53480A598642C66E49CB2E0A3252F1\MicrosoftServiceFabric.6.4.658.9590.exe instead of downloading from https://download.microsoft.com/download/2/5/0/2502146A-D7AA-4D14-B2C2-10081B2F5853/MicrosoftServiceFabric.6.4.658.9590.exe
DownloadManager Information: 0 : Using cached file at C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_3_3_CU6\080E2254D393C7DF2750AE4A5D9481B64C638947\MicrosoftServiceFabricSDK.3.3.658.msi instead of downloading from https://download.microsoft.com/download/2/5/0/2502146A-D7AA-4D14-B2C2-10081B2F5853/MicrosoftServiceFabricSDK.3.3.658.msi
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c wmic product where name="Microsoft Azure Service Fabric" call uninstall'. Process Id: 2412
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.658' is '0'
DownloadManager Information: 0 : Ignoring exit code '0' for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop KtlLogger'. Process Id: 6672
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.658' is '1060'
DownloadManager Information: 0 : Ignoring exit code '1060' for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop LeasLayr'. Process Id: 9136
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.658' is '1060'
DownloadManager Information: 0 : Ignoring exit code '1060' for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.658'. Commandline is: 'C:\Users\shaun.mcguile\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU6\80B01C5F5D53480A598642C66E49CB2E0A3252F1\MicrosoftServiceFabric.6.4.658.9590.exe /AcceptEULA'. Process Id: 11904
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.658' is '1'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric Runtime - 6.4.658' is Failure
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.658'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric Runtime - 6.4.658 done install completed
DownloadManager Information: 0 : Increasing current install to 2
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.658'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.658 had a dependency fail. Increasing install product to 3
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.658 had a dependency fail. Increasing install product to 4
DownloadManager Information: 0 : Product: ServiceFabricRuntime_6_4_CU6, Install Status: InstallCompleted-Failure, Install Time: 00:01:04.6457736
DownloadManager Information: 0 : Product: ServiceFabricSDK_3_3_CU6, Install Status: DependencyFailed-None, Install Time: 00:00:00
DownloadManager Information: 0 : Product: MicrosoftAzure-ServiceFabric-CoreSDK, Install Status: DependencyFailed-None, Install Time: 00:00:00

**Comment by ShaunMcGuile** [comment]
Powershell.exe is missing from Windows\system32 could this be the actual issue?

**Comment by ShaunMcGuile** [comment]
Yes, that was actually the issue, I have replaced the powershell.exe file and boom the web installer worked.  Cheers for you effort.

**Comment by anantshankar17** [comment]
@pascal-hauser are you still facing this ? These failures are more of machine related issues than SF. I will close this issue if you don't need any further assistance. Running the powershell and looking at the FabricSetupLog.log should indicate the real failure.

**Comment by supritap** [comment]
How did you know this was a powershell missing issue? Was it from attempted run of "C:\WINDOWS\sysnative\cmd.exe". I get the same messages/issue. I have dropped powershell.exe in C:/Windows/System32. The logs still show "Commandline is: 'C:\WINDOWS\sysnative\cmd.exe". Anything I need to do differently?
