### ISSUE TITLE
Chaos testing against service fabric linux cluster not working

### ISSUE THREAD

**Issue by MZDN** [Azure/service-fabric-issues#1513]
I am trying to run a c# code of chaos testing against a azure service fabric linux cluster. I am facing following exception: HRESULT: 0x80071D0A
Is chaos testing really being supported by azure service fabric linux cluster? 
I have read that there are some diffrences between windows cluster and lunix cluster [ https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-linux-windows-differences ]
Any help?

**Comment by motanv** [comment]
Hello @MZDN,
The exception is happening because the system service called FaultAnalysisService must be enabled to use Chaos APIs, most likely the cluster does have FaultAnalysisService enabled. 
You could check if it is enabled either through SFX (under System) or through the powershell cmdlet "Get-ServiceFabricService -ApplicationName fabric:/System"

As of today, we enable FaultAnalysisService by default in Windows clusters but not in Linux clusters. We are in the process of enabling FaultAnalysisService by default in Linux clusters as well. For immediate mitigation, there are a few options:
1. You could enable FaultAnalysisService through a config upgrade and then use Start-ServiceFabricChaos API.
2. You could use (though deprecated) the client version of chaos started through Invoke-ServiceFabricChaosTestScenario cmdlet (https://docs.microsoft.com/en-us/powershell/module/servicefabric/invoke-servicefabricchaostestscenario?view=azureservicefabricps)

If you choose to enable FaultAnalysisService through a config upgrade, below would be the steps:
1. Download the cluster manifest with the cmdlet Get-ServiceFabricClusterManifest as an xml file.
2. In the downloaded clustermanifest you need to change the **Version**.
<ClusterManifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/2011/01/fabric" Name="WRP_Generated_ClusterManifest" **Version="3"** Description=""> 
3. Also in FabricSettings section of the downloaded clustermanifest add the following inner section, you may want to adjust the Target/Min ReplicaSetSize:
  <Section Name="FaultAnalysisService">
   <Parameter Name="MinReplicaSetSize" Value="3"/>
   <Parameter Name="TargetReplicaSetSize" Value="5"/>
  </Section>
4. Now you need to upload this downloaded cluster manifest (with changed Version) to the cluster's ImageStore like below:
Copy-ServiceFabricClusterPackage -Config -ClusterManifestPath F:\man.xml -ClusterManifestPathInImageStore vx1
5. Register the copied clustermanifest like below:
Register-ServiceFabricClusterPackage -Config -ClusterManifestPath vx1
6. Assuming, in step 2, you chose "Version = 3", please start the cluster config upgrade as below (UnmonitoredAuto skips health checks thus quicker, but you could choose Monitored if you want health checks):
Start-ServiceFabricClusterUpgrade -Config -ClusterManifestVersion 3 -UnmonitoredAuto
7. Once upgrade is complete, the cluster will have FaultAnalysisService in it, so you could use Start-ServiceFabricChaos API like below.
Start-ServiceFabricChaos -TimeToRunMinute 5 -MaxConcurrentFaults 3 -MaxClusterStabilizationTimeoutSec 30

Note, the downloaded clustermanifest may have a declaration like below:
<?xml version="1.0" encoding="UTF-8"?>
Whereas the xml file's ByteOrderMark (BOM) could be UTF-16LE, if that is the case please change encoding in the above declaration to UTF-16LE. (You can check the BOM here: http://validator.w3.org/i18n-checker/#validate-by-upload+)

Thanks,
Tanvir
