### ISSUE TITLE
All Backup and Restore API operations return E_ACCESSDENIED

### ISSUE THREAD

**Issue by tastyeggs** [Azure/service-fabric-issues#1553]
My cluster is on version 6.5.641.9590, is standalone (on-prem) and uses X509 Authentication.

Reading through this code, [here](https://github.com/microsoft/service-fabric/blob/6f2a641bdfe4b7e7100780cd4a4473f8eda30d5c/src/prod/src/managed/FabricBRS/src/System/Fabric/BackupRestore/BackupRestoreEndPoints/Handlers/ClientCertAuthorizationHandler.cs ), it looks like the controller is looking to authenticate the client certificate against the ServerCertificate thumbprint, as opposed to client cert thumbprint.

No matter, even providing the server certificate leads to this error.

On the server, I'm seeing a few logs:

```
Failed to open store '' at LocalMachine: E_INVALIDARG
Failed to get the Certificate's private key. Thumbprint:<SERVER_CERT_THUMBPRINT>. Error: E_INVALIDARG
Failed to get private key file. x509FindValue: <SERVER_CERT_THUMBPRINT>, x509StoreName: , findType: FindByThumbprint, Error E_INVALIDARG
```

I'm urgently in need of guidance, as the regular documented process of doing a basic backup / restore doesn't work. Has anyone else hit this issue?

**Comment by lanfeust69** [comment]
Yes, I have the same issue, and I think I finally solved it.

I currently implement backup and restore within my services, but was looking forward to delegating this to the dedicated service. I gave it a try 6 months ago, but had these ACCESS_DENIED errors, no time to investigate further, and only went back on this a few days ago.

I went a step further by actually debugging `FabricBRS.exe`. And indeed, the only certificate in `fabricBrSecuritySetting.AllowedClientCertThumbprints` is the server one. This is correct though, as I understand that it is the gateway's job to validate the "real" client certificate, before calling the BRS. However, the problem is that there is *no* certificate whatsoever in the `HttpRequestMessage` !

The root cause is the comment (or rather metadata) in the cluster configuration json files, that states that certificate thumbprints should be space-separated pairs of hex digits. In the https proxy scenario of BRS (and event store), the string is used verbatim (well, after a `.ToUpper()`) to find the certificate in the store, and that fails on both the gateway (which therefore doesn't include any certificate in the request), and would also fail the validation on the BRS side, where the `X509Certificate2.Thumbprint` property wouldn't have spaces.

I updated my cluster configuration without spaces in the thumbprints, and it seems to work now (the strange thing is that there were three "cycles" of configuration updates before it settled down...).

One up for open-sourcing, this kind of issue is *much* easier to dig through with the source !

**Comment by tastyeggs** [comment]
Ah, that makes sense. @lanfeust69 thanks!

Let me try this out and confirm. You didn't hit any issue with the rest of the cluster rejecting the non-space-separated thumbprint?

**Comment by raunakpandya** [comment]
Yes. The reason why the BRS expects the certificate presented to it is server cert because its the gateway who does all the authentication and authorization and then forwards the request to BRS. The request never lands directly on BRS. 

Seems like the issue was with the way thumbprint was specified. Can you point where is the comment to specify it with space? Is it in the clusterconfig.json? We would like to fix the anamoly one way or the other to ensure folks dont hit into this issue.

**Comment by lanfeust69** [comment]
@tastyeggs : no issue, except the strange "triple rollout", which is possible (probably ?) unrelated to the specific change.

@raunakpandya : This was in the sample configurations within the `Microsoft.Azure.ServiceFabric.WindowsServer.x.y.z.u.zip` files, similar to [this](https://github.com/Azure-Samples/service-fabric-dotnet-standalone-cluster-configuration/blob/master/Samples/ClusterConfig.Windows.X509.MultiMachine.json#L36).

**Comment by tastyeggs** [comment]
Alright, confirmed on my end too; removing the spaces from the ServerCertificate thumbprint fixes this.

Before:
```
               "ServerCertificate": {
                   "Thumbprint": "fe 8c a5 c1 af 4f 89 16 55 72 f7 af 29 b8 a1 7c ae 11 9b 4c",
                   "X509StoreName": "My"
               },
```

After:
```
               "ServerCertificate": {
                   "Thumbprint": "fe8ca5c1af4f89165572f7af29b8a17cae119b4c",
                   "X509StoreName": "My"
               },
```

**Comment by raunakpandya** [comment]
Thanks. We will fix this inconsistency

**Comment by raunakpandya** [comment]
This has been resolved sometime back.
