### ISSUE TITLE
Custom DataContractResolver for known types support

### ISSUE THREAD

**Issue by DenisPitcher** [Azure/service-fabric-issues#158]
Hello, this is a followup to the suggestion I've posted on Uservoice
https://feedback.azure.com/forums/293901-service-fabric/suggestions/16449589-provide-extensibility-points-for-service-fabric-re

I would like to raise the issue of the inability to specify a custom DataContractResolver when using Service Fabric Remoting.  The core need I have is the ability to support known types similarly to what I am able to do in WCF.  I would prefer to not have to decorate every object with a known type attribute and instead provide a customized data contract resolver that can specify the known types that are available.

**Comment by MedAnd** [comment]
Somewhat related, we use the a custom StateSerializer (NewtonSoft Json) within our stateful services but cannot override the default remoting Serializer... only approach seems to be writing a custom ICommunicationListener?

**Comment by VipulM-MSFT** [comment]
The issue 529 is about state serialization whereas this issue is about customizing the remoting/communication serialization. 

The document https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2 describes how to use custom serialization with V2 remoting stack.
