### ISSUE TITLE
Service Fabric not starting (One Node Mode Only)

### ISSUE THREAD

**Issue by Poolitzer80** [Azure/service-fabric-issues#1582]
When i start my applications in One Node Cluster Mode, All my Services start with an error.
In 5 Node Cluster Mode, the applications starts properly. 

I attached my logfiles and traces for Analysis.
`https://1drv.ms/u/s!BPhMLEnrZ0jLlzFj763T3qZgum3t?e=gPpPULov9Euhd1DEoh5ftA&at=9`

**Comment by Poolitzer80** [comment]
https://developercommunity.visualstudio.com/content/problem/713404/cant-start-service-fabric-one-node-only.html?childToView=770164#comment-770164

**Comment by danegsta** [comment]
Tracked down the issue in this thread on Developer Community (https://developercommunity.visualstudio.com/content/problem/713404/cant-start-service-fabric-one-node-only.html). It ended up being an issue with the Get-Content Powershell command defaulting to ASCII encoding unless explicitly overriden with -Encoding UTF8. A couple of the Service Fabric SDK Powershell scripts and modules need to be updated to add -Encoding UTF8 anywhere there's a call to Get-Content in order to properly support paths with Unicode characters in them.

**Comment by dbreshears** [comment]
Closing as this was fixed in the 16.4 release of the tooling
