### ISSUE TITLE
6.5.676.9590 - Cluster Degraded

### ISSUE THREAD

**Issue by bturman15** [Azure/service-fabric-issues#1585]
I recently upgraded a 3-node (bronze tier) cluster to 6.5.676.9590 and now I am presented with an Error: Cluster is degraded because it does not have 5 seed nodes. Is 3 nodes no longer supported or is this a bug in the latest version?  I did not have this issue with 6.5.639.9590.

I have a new cluster that I need to set up and cannot find 6.5.639.9590 available for download now.

Thank you for your help.
![image](https://user-images.githubusercontent.com/56700793/67047577-31d35580-f0f8-11e9-9a22-124581a85b77.png)

**Comment by krawls19** [comment]
I am experiencing the same issue with our lower environments which are Bronze tier as well. The documentation still says Bronze is minimum of 3 VMs, so I assume the clusters are still valid.

**Comment by l2extasy** [comment]
same issue for me, dev clusters provisioned on bronze tier with 3 vms and SF version 6.5.676.9590 getting this error.

**Comment by lironhanania** [comment]
Same issue for me as well. SF version 6.5.676.9590

**Comment by bturman15** [comment]
I was able to find a copy of 6.5.639.9590 from one of my other clusters to get it installed, and I know this issue isn't present there. I do not know if it is on any of the versions in between.

Thank you all for confirming that I am not alone here.

**Comment by lironhanania** [comment]
Hi @bturman15 , did you hear anything from MS about that issue?

**Comment by PeteCos** [comment]
Same issue just occurred for me using Standalone Service Fabric implementation
- upgraded from v6.5.639.9590 to v6.5.676.9590
- Nothing else changed, no issues prior
- 3x Orchestrator Node system
I suspect this is considered a 'Bronze' implementation, but have not  seen any reference to these reliability tier settings up to now - in Standalone Version - sneaked in somewhere along the line.

As said, good to know its not just me...

**Comment by jeffj6123** [comment]
Hello,
With the latest CU released for 6.5 this message was added to point out when running on an unsupported scenario for production workloads on Azure as defined here, https://aka.ms/servicefabric/reliability

The wording and appearance of this message have been misleading and overly alarming and will be changed with 7.0 to be much more clear about it referring to production workload supportability and also being removable instead of a persisted red banner. Additionally it will only show on SFRP clusters.

NOTE: This banner doesn’t reflect the actual cluster health and was meant to be regarded as a recommendation to increase the reliability if the cluster was meant for production workloads.

Sorry for any confusion this banner has created.

**Comment by masnider** [comment]
Hi folks, this should be resolved at this point. Please upgrade and reopen this issue if you are still seeing this incorrect warning. Sorry again for the noise.
