### ISSUE TITLE
Time Service not running on Azure Service Fabric VMs (Windows Server)

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#162]
```
C:\Users\localadmin>net time
Could not locate a time-server.

More help is available by typing NET HELPMSG 3912.


C:\Users\localadmin>w32tm /query /source
The following error occurred: The service has not been started. (0x80070426)
```

I'd expect cluster VMs to sync their clocks with time service, otherwise the clock drifts to much and external to the cluster services start seeing quite some time differences

**Comment by masnider** [comment]
1. If you really need the time server turned on for some reason, then go ahead and do it. [Be careful][1]. Probably a VMSS Extension would be the best way. They're your VMs. 
2. Is the time server enabled on VMSS/Azure VM's Generally? If not then this is not a Service Fabric issue and if you think it should be generally enabled you'd have better luck talking with the folks who manage/deploy Azure VMs directly if you think that should be the default.
3. Service Fabric doesn't do anything special here. We don't use wall clocks/local time much, and only when it doesn't really matter since the data can be wrong even if you have a good NTP server. Most everything inside SF is logical clocks. 


[1]: http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time

**Comment by TarasRoshko** [comment]
We're not using time for anything serious (actually only for logging)

Regarding general setting, It appears to me that `Azure Web App` VMs have it on (though impossible to confirm due to obvious reasons), but regular VMs / VMSS VMs have it off (and hence SF uses VMSS it's also off)

Since the clock drifts pretty badly due to virtualization (we saw as much as couple seconds/day) it becomes an inconvenience even for things like logging. I'd be happy to discuss this with Azure folks, what's the best place to start such discussion?

**Comment by masnider** [comment]
Thanks to this discussion, they now have https://github.com/Azure/vm-scale-set-issues/issues . I'd head over there.

**Comment by TarasRoshko** [comment]
Thanks for the heads up, closing this one!
