### ISSUE TITLE
SF only listens to 19000 on loopback IP

### ISSUE THREAD

**Issue by Leon99** [Azure/service-fabric-issues#1693]
## Expected Behavior
It's possible to connect to the cluster from another machine.

## Current Behavior
SF only listens to :19000 on the loopback but not on other IPs. As a result, it's impossible to connect to the cluster from another machine.
It does listen to 19080 on all IPs though.
It works just fine when the cluster is set up by Visual Studio on the same machine, so it's not a networking/firewall issue (that doesn't help though since ImageStoreService is missing with that setup).

## Steps to Reproduce

1. Install a cluster with `.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.OneNode.json -AcceptEULA`

## Context (Environment)

Just want to access SF remotely, as per documentation.

#### Service Fabric Runtime and SDK Version :
7.1.428.9590

#### Operating System :
Windows Server 2019

#### Cluster Size :
1 node

**Comment by mcurko** [comment]
I observe the same problem.

**Comment by masnider** [comment]
Since your local dev cluster is unsecured we do not allow off-box connection by default. You may be able to make it work with a combination of secure clusters and -UseMachineName, however this is generally not recommended for local dev clusters.

**Comment by mcurko** [comment]
The problem is the lack of proper documentation. I'm reading through whole ASF documentation stack and can't find answers to simple questions like how to install a cluster. Like the exact structure of cluster configuration file, for example. Just a bunch of unconnected and incomplete information. So that's the reason why I'm testing all the options, one after another, to see how it all works. And then after hours lost trying to figure out why I can't connect, I have to use netstat to figure out the problem. Test: try to find "UseMachineName" in MS documentation, and you'll find it just once, related to containers, nothing relating to deploying apps to the cluster...

**Comment by masnider** [comment]
To be clear: that is because, as mentioned, we do not support/recommend the configuration you are trying to achieve, where the local cluster is available off-box. The normal scenarios (use the local cluster manager to set up 1 and 5 node local clusters) is supported and well documented in the getting started scenarios. 

I mentioned this as a potential solution to try to help you out anyway. We do not expect or recommend that people deal with these options, and the tool automates their usage in the supported/recommended patterns.
