### ISSUE TITLE
Can't change partitioning scheme for actors

### ISSUE THREAD

**Issue by KirylZotkin** [Azure/service-fabric-issues#172]
While playing with azure service fabric actors, here is the weird thing I've recently found out about - I can't change the default settings for partitioning. If I try to, say, set Named partitioning or change low/high key for UniformInt64, it gets overwritten each time I build my project in Visual Studio. There is no problem to do this for Statefull Service, it only happens with actors. No errors, no records in Event Log, no nothing... I've found just one single reference about the same problem on the Internet -

https://social.msdn.microsoft.com/Forums/vstudio/en-US/4edbf0a3-307b-489f-b936-43af9a365a0a/applicationmanifestxml-overwritten-on-each-build?forum=AzureServiceFabric

But I haven't found any explanations to that - neither on MSDN, nor in official documentation. I've raised this question on the StackOverflow, and I was told that UniformInt64 is the only scheme that makes sense for Actors . Still it's frustrating that VS silently overrides my settings without giving me any clue on why it does it.

**Comment by VipulM-MSFT** [comment]
The actors are addressed by ActorId. The ActorId can be a GUID, long or string. These actors needs to map to a partition. The range of the partition key for the actors thus is a full int64 range since ActorId can be any string or any guid. Therefore the low and high keys for the actor service is always min and max values of int64 range. In order to prevent the accidental mistakes where the modified range does not result in gaps in the ActorId partition key space, the tool modifies the manifest upon build. 

The full identity of the actor is actor service name (Uri) + Actor Id. However in the code typically the actors are addressed by their interface and id (ActorProxy.Create<IActorInterface>(ActorId)). The runtime derives the full name of the actor service from actor interface name and its code package activation context. The tooling therefore creates the actor service with the same name as default service in the application manifest. You can create another instance of the actor service with different name through runtime APIs or PowerShell commands, but the client would have to use that name for the service when creating the proxy. Please note that this is atypical.

**Comment by vturecek** [comment]
We touch on this briefly in this article: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-platform

I'll mark this as a doc follow-up to elaborate on this topic.

**Comment by KirylZotkin** [comment]
Ok, this makes sense. For what it's worth, having some kind of error message when the tool modifies the manifest would make things clear, since the more cases like this we have, the more funny stuff developers will see.
Anyway, thanks guys!
