### ISSUE TITLE
Expected CPU utilization during backups

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#189]
We're having large CPU spikes after introducing backups using the reliable services API. The spike reaches ~60% on our production instances (5 * Standard_D2_V2) during the backup callback. However, the information I can provide (right now) is from our QA environment using smaller instances.

**Environment**
VMSS: 3 * Standard_A2_V2
Services: 1 service * 32 partitions * 3 replicas
Backup schedule: one minute (incremental where possible)

**Behaviour**
The CPU utilization of the process reaches 100% every one minute. Under profiling, 93% of the utilization is happening inside the function:
`Microsoft.ServiceFabric.Replicator.LogRecord::ReadNextRecordAsync`.

**Expected Behaviour**
I'm not sure... Is this to be expected? Should we be backing up less often? Should we (somehow) try and stagger backups?

![envoy-cpu-utilization](https://cloud.githubusercontent.com/assets/6076697/23776275/5d809e1e-0581-11e7-9ad1-08af189d6c7e.png)
Spikes shown in a profile of over 20 minutes.

![envoy-cpu-utilization-focused](https://cloud.githubusercontent.com/assets/6076697/23779635/b325281c-0595-11e7-85f5-4666cd64710a.png)
Function CPU utilization focused on a specific spike.

**Comment by masnider** [comment]
@mcoskun @sumukhs - please take a look. Do we know about this one?
@NickDarvey can you provide a little more information about the service? How much data is in this given partition, how many collections are there and how are they structured, etc?  Thanks.

**Comment by NickDarvey** [comment]
Ah, yes, that would be useful.
It's incredibly small. Two reliable dictionaries with one record each. One is an offset, the other is a flag to indicate whether it should be running. (This is a processor that pulls messages from Event Hub.)

**Comment by masnider** [comment]
Thanks for the info. Another piece of information (sorry I didn't recognize it before) you asked "Should we be backing up less often?" - How often _are_ you backing up?

**Comment by mcoskun** [comment]
@NickDarvey, thank you for reporting this issue. Backup does consume CPU for serialization. We do this to remove information in the log that is not necessary for restore and hence reducing the log size and saving on the disk IO. I will take a closer look to see if there is anything we can improve.

As you know Reliable Collection use replication (redundancy) to protect against common failures. For example nodes going down or isolated disk failures. Increasing the target replica set size increases the redundancy and hence reduces the chance of data and availability loss. Unlike replication, backup is designed to provide mitigation to disastrous failures: e.g. multiple disks failing simultaneously or a data-center black out. So your backup rate should resemble your service's disaster recovery point objective (RPO): How much data is your service willing to lose in case of a disaster. 

Commonly we expect customer to use 5 - 15 minute frequency for their incremental backup and > 1 hour for their full backup. We do not recommend backup frequencies higher than 1 per minute. Since 1 minute is the at the boundary, we expect customers to run it on machines that can handle the additional load to provide the RPO they need (e.g. running it on enough machines so that number of concurrent replicas backing up on a node is limited and/or choosing nodes with local SSDs and good CPUs).

If I understand your scenario correctly, you have two keys per replica that are being updates every ~1 minute and being backed up once a minute. This means you will at max lose ~2 updates per key in case of disaster. If your application can handle a bigger data loss in case of a disaster like a tornado hitting a data center, I would recommend increasing the backup frequency.

**Comment by mkosieradzki** [comment]
@mcoskun Thanks for the RPO-related write-up! Especially the recommended value ranges. That's really useful information.

**Comment by NickDarvey** [comment]
Thanks @mcoskun, that's super helpful.
Is this:
>We do this to remove information in the log that is not necessary for restore and hence reducing the log size
specific to incremental backups or does it happen for full backups too?
This particular service has a very small amount of data (just an offset that keeps incrementing). Might it be better for us to always to full backups to save CPU utilization?

**Comment by mcoskun** [comment]
@NickDarvey , full backup also does this. I think it would be good to make this optional in future. I will add a tracking work item. Thank you for your feedback.

**Comment by NickDarvey** [comment]
Thanks for letting us know. That'd be great to see, but we'll adjust our RPO for that service for now.

Nick
