### ISSUE TITLE
[Reverse Proxy] Duplicate Date and Server headers

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#216]
Reverse Proxy adds duplicate values to the Date and Server headers.

It should either:
1. always override those headers
2. keep original headers and add those header only if not present

**Comment by cwe1ss** [comment]
I can confirm this bug:

![duplicate-headers](https://cloud.githubusercontent.com/assets/4581460/26035864/09f31d86-38d4-11e7-8d3c-8561ebc24340.PNG)

**Comment by kavyako** [comment]
This will be fixed in our next release, 5.7. The Date and Server header sent by the service will be overwritten and reverse proxy will send its own Date and Server header instead.

**Comment by kahootali** [comment]
@kavyako I want to remove the Server header from Service Fabric Reverse Proxy Response, is there a way?

**Comment by kavyako** [comment]
@kahootali Could you clarify a bit more? do you want the reverse proxy to forward the "Server" header sent by the service as-is instead of adding its own?
You could set the reverse proxy setting [RemoveServiceResponseHeaders](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings#section-name-applicationgatewayhttp)="" to forward all the headers returned by the service as-is. 

For Azure clusters, follow these [steps ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings#customize-cluster-settings-using-resource-manager-templates)to update this setting for your cluster.
For standalone cluster, add the setting to the fabricSettings section of your cluster config json and perform a cluster config upgrade.

Let me know if you have further questions.

**Comment by kahootali** [comment]
Basically, I want to remove the server header from my response. I have removed using my middleware, but Reverse Proxy adds the header again so I want to remove it.

**Comment by kavyako** [comment]
This is a limitation of our current reverse proxy, there is no straightforward way of removing the Server header from the reverse proxy's response. 
The reverse proxy uses HTTP.SYS underneath so one possible workaround is to enable a setting in HTTP.SYS to disable the server header from its responses. This can be accomplished by setting the DisableServerHeader registry key under HKLM\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
to 1. Please see "Server Header" section [here ](https://blogs.msdn.microsoft.com/varunm/2013/04/23/remove-unwanted-http-response-headers/)for more details.
**Note: This is a system wide config, so the Server header will be removed from all services that are using the HTTP.SYS stack. Please ensure you are okay with this before trying out the option.**
