### ISSUE TITLE
[Question] Potential causes for ActorStateManager argument exception during TryGetStateAsync

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#217]
Hi,

We're getting an `An item with the same key has already been added` error and I was wondering if someone could point me in a direction on where to look.

Our first assumption was that it was a bad Data Contract/deserialization (because we do have a dictionary in the state it's getting) but it only occurs intermittently for the same actor and no state has been written during those calls.

I had a look at [the shared source](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/3c8de6a7737f2653ea739f2ad27761ec281f9164/src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateManager.cs#L79) and the only dictionary-related call it makes is to `stateChangeTracker` and it handles the key already existing.

1. Is this stack trace what we'd see during a `TryGetStateAsync` if there was state serialized with a dictionary with a duplicate key (somehow)?
2. Is there any way we can hook into the StateManager to log with more precision?

Kind regards,
Nick

```
Exception:System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at 
Microsoft.ServiceFabric.Actors.Runtime.ActorStateManager.<TryGetStateAsync>d__a`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<Select>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<Select>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<Select>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<Select>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<SelectMany>d__4`3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<Select>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TaskExtensions.<SelectMany>d__4`3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c__DisplayClass1`1.<ContinueWithResult>b__0(Task`1 t) at 
System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<DispatchAsync>b__5(Task`1 t) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at 
System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at 
Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass47.<ActorMethodDispatch>b__46(Task`1 t)
```

**Comment by VipulM-MSFT** [comment]
@harahma can you look at this?

**Comment by harahma** [comment]
Hi Nick,

Based on you description and the stack trace, it looking ActorStateManager in your code is being accessed from multiple thread simultaneously. ActorStateManager is single threaded and should be accessed by only thread at a time. Can you check if your code inside actor spawns multiple thread?

Regarding hooking into StateManager,  you can pass stateManagerFactory to [ActorService](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/3c8de6a7737f2653ea739f2ad27761ec281f9164/src/Microsoft.ServiceFabric.Actors/Runtime/ActorService.cs) constructor when registering your actor. Each time actor runtime will instantiate an actor, it will invoke the passed in stateManagerFactory to create StateManager for the actor. The stateManagerFactory can return any custom implementation of IActorStateManager.

Thanks,
Hasibur

**Comment by NickDarvey** [comment]
Hi Hasibur,

That sounds like the culprit. 

One of our guys created [a simple repro project](https://github.com/NickDarvey/ServiceFabric-StateManagerAccessException) for it.
The repro is one actor calling a method on _n_ other actors and `Task.WhenAll`ing it _and_ only occurs after the service is restarted (perhaps when the actor is being brought into memory?). 

There is a `Task.WhenAll` which (for each item in the cart) gets some details out of the Cart actor's state and then calls the Product actor.

The exception occurs in this method:
```
        private Task<ShoppingItem> GetShoppingItemById(string id) =>
            GetShoppingStateAsync()
                .ContinueWith(task =>
                    task.Result.Items
                    .Where(kv => kv.Key == id)
                    .Select(kv => kv.Value)
                    .FirstOrDefault());
```
https://github.com/NickDarvey/ServiceFabric-StateManagerAccessException/blob/master/ShoppingCartActor/ShoppingCartActor.cs#L46-L52

Does `Task.WhenAll` break the actor's concurrency guarantee? Is that just a no-no?
(I'm not familiar with the magic that is the TPL and if Reliable Actors exerts any control to avoid developers spawning threads using things like `Task.WhenAll` and `Task.Run`.)

Is it safe to use `Task.WhenAll` if we're _not_ accessing the actors state? Like when we're fanning out and invoking methods on other actors and want to execute those requests in parallel?

Thanks,
Nick

**Comment by harahma** [comment]
Adding @amanbha

Hi Nick,

I looked at the code. ActorStateManager is getting accessed from multiple threads in parallel.

When you try to list the items in ShoppingCartActor, ListItems(IEnumerable<string> ids) spawns multiple threads using Task.WhenAll() which sends request to other N actors in parallel. When these requests finish they come back and access shopping state with key 'ShoppingItemsStateKey' in parallel.

private async Task<ShoppingItemsState> GetShoppingStateAsync()
 {
            **var state = await this.StateManager.TryGetStateAsync<ShoppingItemsState>(ShoppingItemsStateKey);**
            return state.HasValue ? state.Value: new ShoppingItemsState();
}

When you create your actor service and populate items for first time, the shopping state gets cached in ActorStateManager (as it acts as a write through cache). After this when you try to list the item, even though TryGetStateAsync<ShoppingItemsState>() gets accessed in parallel, things work fine because shopping state is already cached in ActorStateManager.

Now when you restart the partition, all the replicas are restarted and a new replica becomes primary which does not have any active actor and no state in memory. Now when you try to list items again, multiple threads will try to access ActorStateManager. However, this time ActorStateManager does not have shopping state in cache. So it may happen that multiple threads will check if state exists in cache simultaneously and will then go the ActorStateProvider to load the state and add to cache. However only one of the threads will succeed in adding the state to cache and others will fail with exception that you are seeing.

Other thing you should pay attention to is not to store a whole dictionary as a single state in the actor. This is bad for performance reasons. Even when you modify only one key in your dictionary, you will end up serializing and replicating whole dictionary and as the dictionary size will grow with time it will get worse.

The ActorStateManager has dictionary like interface and you can directly use it to store your keys. This will ensure that when you modify a key you only serialize and replicate that key and get better performance.

Thanks,
Hasibur

**Comment by NickDarvey** [comment]
Hi Hasibur,

That makes sense---so is the guidance not to use `Task.WhenAll` inside actors? What about if we're not touching the actor's state?

(Understood RE: making use of the ActorStateManager dictionary interface. Good advice.)

Nick

**Comment by NickDarvey** [comment]
Understood, thank you for the clarification.
