### ISSUE TITLE
Cluster upgrade from 5.4.164.9494 to 5.5.219.0 fails

### ISSUE THREAD

**Issue by LeroyK** [Azure/service-fabric-issues#221]
Upgrading our dev cluster from Service Fabric 5.4.164.9494 to 5.5.219.0 fails. The first node went down.

By looking at the event log my guess is that it is caused by the windows service being updated to use an incorrect path. The FabricHostSvc service points to: "C:\Program Files\Windows Fabric\bin\FabricHost.exe". However this folder doesn't exist. SF seems to be installed in "C:\Program Files\Microsoft Service Fabric".

Event Log entry:
> Error: System.InvalidOperationException: Cannot start service FabricHostSvc on computer '.'. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified

**Comment by chrissie926** [comment]
Hi once the rollback succeeds, you can try the upgrade again. If the issue persists, you can uninstall the MSI from the node and reinstall it. By the way, what kind of service fabric deployment are you using? SFRP or Standalone?

**Comment by masnider** [comment]
@LeroyK - hi there. Were you ever able to get this working? If you could provide the information @chrissie926 asked for we could probably help you figure this out. Have you tried this with a more recent release (5.6 or 5.7)?

Since this is so old and since we don't have any more information, I'm going to close this down. If you find out after that that you're still having problems or have more questions, please feel free to reopen it or to file a new issue.
