### ISSUE TITLE
ServiceProxy for RandomSecondaryReplica

### ISSUE THREAD

**Issue by silvioboehme** [Azure/service-fabric-issues#228]
Hi!

Normaly I can create a Service Proxy with TargetReplicaSelector.RandomSecondaryReplica to get a secondary readonly replica for some uncritical read operations.

I simulated a DataLoss to test my backup/restore logic. But after all replicas are up again, I receive the following error, if I try to connect to a secondary replica:

"No endpoint found for the service 'fabric:/TestApp/TestService' partition '...id...' that matches the specified TargetReplicaSelector : 'RandomSecondaryReplica'"

The Primary replica works fine. In Service fabric Explorer there are all replicas up (1 Primary, 2 secondary) and all replicas have a configured endpoint.

Maybe there is an issue with the naming Service? If i restart the whole Cluster everything is working as expected.

Fabric Version is 5.5.216
Tested with a local 5 node cluster

**Comment by suchiagicha** [comment]
I have few questions for you.

When you say "after all replicas are up again" , did   you checked if all replica status was  "Ready" before issuing call through service proxy.
Since during backup-restore , there might be case where primary replica is up but still restoring the secondary's. There won't be any secondary for a duration.

Also if you retry after some time were you still seeing the error?

**Comment by silvioboehme** [comment]
Yes, the replica status was "Ready" for all replicas. Also about 10-15 minutes, the error still occurs.
The only way was to restart the whole cluster.

**Comment by suchiagicha** [comment]
@silvioboehme  
In order to investigate  this issue, could you provide us the SF logs and time you simulated dataloss and  time you sent request to secondary?

For local box cluster , SF logs location can found at the following registry key 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric \FabricLogRoot . 

LogLocation will have the Traces folder , you can zip it and then share with us.

**Comment by VipulM-MSFT** [comment]
@silvioboehme - we hope that you were able to resolve the issue. Because of inactivity on this thread we are going to close this issue. If this is still an issue please provide us the traces to investigate with any additional information.
