### ISSUE TITLE
ServicePartitionClient and InvokeWithRetryAsync huge overhead when resolving

### ISSUE THREAD

**Issue by coonmoo** [Azure/service-fabric-issues#251]
Hello,

since I didn't found a solution yet, I'll report this as an issue within the Service Fabric SDK.

According to the documentation it's best practice to recreate the ServicePartitionClient. If you make use of partitions this is essential, because the ServicePartitionClient resolves the Partition according to the partition key.

So since we are recreating the ServicePartitionClient on every call, the InvokeWithRetryAsync method **always** seems to resolve the partitions and not using a cache.

When using a fast communication transport like TCP, the overhead of InvokeWithRetryAsync is not acceptable.

See also: http://stackoverflow.com/questions/41790829/azure-service-fabric-invokewithretryasync-huge-overhead

I would love to see a fix, where InvokeWithRetryAsync could make use of cached resolved partitions.

Thank you

**Comment by coonmoo** [comment]
Is there anything I can help you with diagnosing this issue?

**Comment by VipulM-MSFT** [comment]
Are you recreating the factory as well? Could you post code snippet? You can look at how remoting and WCF clients uses the ServicePartitionResolver https://github.com/Azure/service-fabric-services-and-actors-dotnet/tree/develop/src.

**Comment by tarynt** [comment]
I ran into this too.

Digging through the source it seems that a new ServicePartitionClient will always hit FabricClient.ServiceManagementClient.ResolveServicePartitionAsync for the first request. This is required because the underlying factory cache uses PartitionId as a key rather than making use of the extra information provided in ServicePartitionInformation (Singleton, Named & Int64Range).

The mandatory resolve could be removed if the cache was changed to work with a separate bucket for each of the partition kinds, each having a different strategy for retrieval. For example, when the factory resolves an Int64Range partition, it could cache on Uri + LowKey/HighKey, then it would only require a single resolve per partition rather than one for every possible key value.

That or speed up ResolveServicePartitionAsync somehow :)

**Comment by VipulM-MSFT** [comment]
The communication factory uses ServicePartitionResolver which in turn uses FabricClient to achieve the resolution. The partition information is cached in native implementation of FabricClient. There is an inbuilt resolution cache in the native FabricClient along with the partition description cache. So unless a new FabricClient is created on every request for some reason (normally this is cached as well in the ServicePartitionResolver), the cost at that point should be an interop call and not the actual request going over the wire.

**Comment by Lynk5** [comment]
Hi,
Here are some benchmarks for "cached" partitions resolution:

**Comment by Lynk5** [comment]
Created my own Int64 partition resolver which is able to resolve the same partitions from any hashed ID approximately 100x faster than the one provided by SF.

Hope that there will be some explanation about the subject as I can't find the code of the Resolver (Underlying Manager) which is maybe somewhere I haven't found yet.

Best

**Comment by gitsparty** [comment]
@Lynk5  what change did you make the gain the perf improvement? Do you know if that change is still needed?
