### ISSUE TITLE
Updating config or scaling seems to take a very long time

### ISSUE THREAD

**Issue by wayne-o** [Azure/service-fabric-issues#263]
I tried scaling my clustrer lastnight because they had ran out of disk space (weird as i don't do any disk ops - any advice here would be good also) and I gave up after waiting for well over an hour - went home and it was still going 2 hours later.

This morning I deleted the cluster out of frustration and now I get an application error. Because my endpoint uses custom domain + ssl i have to register my cert thumb as an admin cert. Fine... Now an hour later I am still sat here waiting for the "Updating user configuration" message to go! 

Everything I do seems to take hours and I am blocked until the settings have taken hold. Is this normal? Surely this length of time is not acceptable?

**Comment by Mardoxx** [comment]
What VM size are you using?

**Comment by wayne-o** [comment]
standard d2 v2 (2 cores 7gb)

**Comment by Mardoxx** [comment]
I updated my reply.

I had issues when using A0 VMs, and everything took ages, but the main problem was because ACL on my cluster certificates wasn't set up properly for NETWORK_SERVICE. Cluster got stuck in `Updating user configuration`. I also notice that when I was prating around with ARM templates and deleting/creating clusters -- it seemed that my account got rate limited some how. Provisioning new clusters took well over 80mins, where as on my colleague's account (same ARM template) it took less than half of that.

**Comment by CassandraDied** [comment]
Had experienced the same thing too. Updating certificates takes huge amount of time, more than an hour. In the end, everything finished successfully, but it is easier and faster to just recreate everything from scratch than update configuration. D2V2 machines in 3 nodes cluster.

**Comment by nrandell** [comment]
I'm seeing something very similar - is there any way to debug and understand what is happening?

**Comment by mebarron** [comment]
Updating client admin certs on 6 node cluster is taking about ~2 hours

**Comment by infact** [comment]
Same here  Updating client admin certs on 5 node cluster is taking about ~2 hours  with a message "Cluster is updating user configuration."

**Comment by abhay777** [comment]
Certificate upgrade is multiphase upgrade, in case you have 5 nodes in a cluster and they most likely will fall into 5 separate UDs 
There are couple of upgrade parameters, that dictate how long the upgrade will take.  

HealthCheckWaitDuration : The time to wait after the upgrade has finished on the upgrade domain before Service Fabric evaluates the health. If the health check passes, the upgrade process proceeds to the next upgrade domain.  If the health check fails, Service Fabric waits for an interval (the UpgradeHealthCheckInterval) before retrying the health check again until the HealthCheckRetryTimeout is reached. 

HealthCheckStableDuration:  The duration to verify that the application is stable before moving to the next upgrade domain or completing the upgrade. This wait duration is used to prevent undetected changes of health right after the health check is performed. 

Default value for these parameters are 5 min each, so for each upgrade domain 
 
t min(time to upgrade) + 10 min (5 heathcheckwait duration + 5 health check stable duration) 
so with 5 UDs it will be 5* (t+10) ~ 50+5t min 
since cert upgrade is multi phase upgrade it doubles this time. hence it takes ~2 hr. 

You can always update these values for cluster in portal 

FabricUpgrades > Advance upgrade settings 

But it is good to have minimum 5 min so upgrade can rollback if health deteriorates.

**Comment by masnider** [comment]
There have been many improvements to VM scale time and operations. The values suggested by Abhay also would help.
