### ISSUE TITLE
Service Fabric and HTTP/2

### ISSUE THREAD

**Issue by Jakkob** [Azure/service-fabric-issues#282]
I'm interested in using [Google's gRPC](http://www.grpc.io/) for remote procedure calls both within and outside of my Service Fabric cluster, but it is dependent on HTTP/2 to function.

Is Service Fabric compatible with HTTP/2, and if not, is it on the team's radar at all?

**Comment by mholo65** [comment]
@Jakkob I made a small PoC for a `gRPC` Communication Listener here https://github.com/mholo65/service-fabric-grpc-playground

**Comment by Jakkob** [comment]
@mholo65 Hey, awesome! Have you had any issues with your implementation yet?

**Comment by mholo65** [comment]
If youd like to use `gRPC` in service/actor remoting, it's probably doable, but would require some more work.
See example for WCF replacement here https://github.com/Azure/service-fabric-services-and-actors-dotnet/tree/develop/src/Microsoft.ServiceFabric.Actors.Wcf

Regarding the HTTP/2 it doesn't seem to be an issue as `gRPC` seems to implement HTTP/2 protocol itself and doesn't rely on .NET. I made this assumption since gRPC targets `net45` and HTTP/2 is available in `net46`.

**Comment by mholo65** [comment]
@Jakkob 
> Have you had any issues with your implementation yet?

Honestly, haven't tested it. Got inspired by this issue and decided to throw it together :smile:

**Comment by Jakkob** [comment]
Well damn. That's spectacular news.

**Comment by Jakkob** [comment]
Thanks for reaching out and sharing!

**Comment by mholo65** [comment]
@Jakkob I also created a quick PoC for `CommunicationClientFactory` and `CommunicationClient` [here](https://github.com/mholo65/service-fabric-grpc-playground/tree/master/ServiceFabric.Services.Grpc/Communication/Client)

It simplifies consumption of gRPC services as can be seen [here](https://github.com/mholo65/service-fabric-grpc-playground/blob/master/ServiceFabric.Grpc.Client/Client.cs#L48).

**Comment by vturecek** [comment]
Service Fabric is protocol-agnostic. You can use any version of HTTP (or whatever) as long the web stack your services are using supports it. For example WebListener in ASP.NET Core on Windows Server 2016 supports HTTP 2, so if you're using that, then you can do HTTP 2 today. There's an issue open for HTTP 2 support in Kestrel too: aspnet/KestrelHttpServer#73

**Comment by Harmonickey** [comment]
Do you know how I might be able to get it to connect via grpc from a node.js app to the service fabric deployed grpc-playground application?

This is a piece of code from my node js application that calls the grpc endpoint deployed into service fabric.

I keep getting an ERR_EMPTY_RESPONSE (after waiting quite a while for it to timeout).  The service appears to be deployed correctly, and I didn't modify any of the playground code.

```javascript
import config from 'config';
import grpc from 'grpc';
import grpcPromise from 'grpc-promise';
const PROTO_PATH = `${__dirname}/../../../proto/helloworld.proto`;
const greeterService = grpc.load(PROTO_PATH).helloworld;
const myip = "<replace your ip here>";
const greeter = new greeterService.Greeter(myip + ":19081/ServiceFabric.Grpc_Playground/Service", grpc.credentials.createInsecure());
grpcPromise.promisifyAll(greeter);

const HelloWorld = {
    greeter() {
        return greeter.sayHello()
            .sendMessage({
                name: "alex"
            })
            .then(res => {
                console.log(res);
                return res;
            });
    }
};

HelloWorld.greeter()
```

**Comment by kinglionsoft** [comment]
Any updates?

**Comment by masnider** [comment]
As @vturecek mentioned above:
 
> Service Fabric is protocol-agnostic. You can use any version of HTTP as long the web stack your services are using supports it. For example WebListener in ASP.NET Core on Windows Server 2016 supports HTTP 2, so if you're using that, then you can do HTTP 2 today. There's an issue open for HTTP 2 support in Kestrel too: aspnet/KestrelHttpServer#73

If you are having issues connecting to a service using http2/grpc then it is something with the communication stack the service is using or an error in usage. 

FWIW, AspNet/Kestrel has supported this for some time https://github.com/aspnet/AspNetCore/issues/4782 

It looks like the issue above is actually that you're trying to route the call through the ReverseProxy rather than communicating with the service directly. The reverse proxy does not support http/2 at this time. This issue is tracked via https://github.com/Azure/service-fabric-issues/issues/827 

I'll close down this issue and we can follow up there. Thanks for the discussion!
