### ISSUE TITLE
Fabricclient uncatchable com exception

### ISSUE THREAD

**Issue by aL3891** [Azure/service-fabric-issues#283]
Hello, I have an odd problem with FabricClient.QueryManager.GetPartitionListAsync(). First of all I am positive that the service exist, I can see it in the service fabric explorer, yet this method _most of the time_  throws a _Service not found_ exception. I know that it sometimes work however, I've observed this with a debugger, making it even more puzzling.  What is more though, I'm not able to catch this exception, it instantly terminates the process, causing the service to fail over.

I strongly suspect that fabric client is not able to find some other system service, not the service i'm asking for, but how can I debug this? also, why can't this exception be caught? I assume its a native exception, it comes via com, but then am I using FabricClient  incorrectly? The docs said to share fabric client instances as much as possible, witch I did initially, but even if I make new instances I get this problem. 

If you can provide any hints as to what's going on that'd be great.

I'm running on a 5 node local cluster using version 5.6.204.9494, I've also observed this on an azure cluster, witch is the reason i'm debugging it in the first place

**Comment by aL3891** [comment]
Could this be a threading issue? are there any particular threading considerations with FabricClient?

**Comment by aL3891** [comment]
Is there any way to bypass fabric client and directly call the system services over rest to get hold of this information?

**Comment by oanapl** [comment]
Yes, we expose REST for GetPartitionListAsync, see [Get Partition Info List](https://docs.microsoft.com/rest/api/servicefabric/sfclient-api-getpartitioninfolist).

There is no locking issue with fabric client. Get partition list goes to multiple components in the system, aggregates the information and returns it back to the client. Sharing fabric clients is the right thing to do and should have no impact on the results of the query. 
If the service is not there, you should get the same error with FabricClient, Powershell or REST since internally they call the same code.
Is it possible that the exception you see in debugger is a first chance exception that the debugger is configured to catch? Can you let the process continue? What do you see if the debugger is not attached?

Are all your system services healthy in fabric explorer?

If you keep hitting this issue, you can send us the traces so we can take a look.

**Comment by aL3891** [comment]
Hello, thanks ro your reply.

No its not just a first chance exception, the process immediately terminates after it and we see this even when not attached. this happens contiounsly on one of out test environments, it essetially tries perpetually to resume a restore, and thus tries to enumerate all the partitions. we've seen it fail over and over for atleast a day, so it should not be a transient issue. 
Yes, system services report that they are healthy. 

From what i've been able to gather this exception is thrown on a threadpool thread and thus goes uncaught and brings down the process. it also looks like the exception originates from unmanaged code, but i'm not too sure about that. 

My best theory is that there's some value that is cached, perhaps on one of the system services, and that this cache never gets invalidated. when i've had this issue locally, reseting the cluster has helped, but after a while the problem has returned.

i'm sorry i can't provide better information, but if you like me to do something to collect more data for you, please tell me

**Comment by oanapl** [comment]
Can you provide more detail about the process that hits this exception? Is it a service fabric service or just a process using the service fabric SDK? You mention a stack trace, do you happen to have it or a dump of the process crash? And are you sure that the exception happens on get partition list, or later, when you do your next operation (you mention resume restore)?
Have you tried running get-servicefabricpartition at the time this error happens continuously and see whether Powershell from the same environment fails (assuming the client is outside the cluster)?
If this happened only on a backup/restore scenario, @mcoskun may be able to help you more.

**Comment by aL3891** [comment]
We basically have  a stateless service fabric service (using the sdk) that we call a method on to invoke a restore on a bunch of other stateless services, mostly actors. this service makes up list of services to restore, loops through it, tries to get all the partitions for each service and invokes a data loss on each one.

Each of these services derive from a baselass we've made that derives from actor service, that listens to the ondataloss event and goes out to blob storage to download a backup and hand the folder to the statefull service recovery system.

where it fails is when the restore service tries to get the partitions for each service to restore. again it does work sometimes but mostly it fails, crashing the restore service, causing it to fail over to another replica. The restore service remembers that it was doing a restore, so it tries again, fails, and failsover.
What is strange is that we're not able to catch this exception, the process just terminates, although i am able to see the first chance exception in the debugger, but immediately after continuing after that, the process terminates. 

perhaps this is unrelated, but i thought i'd mention it, when we deploy a new cluster we have a script that deploys all out apps concurrently,  to save time, could this be causing a problem? seems like a long shot but since its a bit custom it might be useful to know

**Comment by oanapl** [comment]
Since you can repro this, can you change your code to catch exceptions and get more information? The callstack would be very helpful.
Can you paste a snippet of the code that calls the query and invokes data loss?

How is your stateless service configured - one instance? If more instances, are they all trying to invoke data loss or is some logic to select only one? 

Assuming you have one instance, is it possible that the following happens: 
1. Instance1 enumerates the partitions and starts invoking data loss. In the middle of invoking data loss, there's an exception and the service goes down. 
2. Some services have data loss invoked on, so they go on and do their thing - does that bring them down by any chance?
2. Instance2 is started for the service that enumerates, and this one starts allover. While it enumerates, some of the services that have invoked data loss may not be there, so there are exceptions again, and the cycle continues.

Or to rephrase, is invoking data loss logic in your code idempotent? is it ok to invoke the same from the new instance without keeping track of the progress of the previous instance?

**Comment by aL3891** [comment]
I'll try and get an exact call stack but in the meantime i can tell you that it's only one instance running and when we do see this issue, it happens before data loss can be invoked at all. The restore service fails to enumerate partitions for a service in the first place so data loss is never invoked. 

To be clear, its not the services that are being restored that have a problem, its the restore service that tries to get all the partitions and then invoke data loss. That first step is what fails.

**Comment by aL3891** [comment]
This is what the code in our restore service looks like:

				List<Uri> backedUpServicesUris = new List<Uri>();
				foreach (var application in await fabricClient.QueryManager.GetApplicationListAsync())
					foreach (var service in await fabricClient.QueryManager.GetServiceListAsync(application.ApplicationName))
						if (await IsBackupableService(service))
							backedUpServicesUris.Add(service.ServiceName);


				var tasks = new List<Task>();
				foreach (var bs in backedUpServicesUris)
				{
					foreach (var p in await fabricClient.QueryManager.GetPartitionListAsync(bs))
					{
						tasks.Add(BackupRestoreUtil.PerformDataLoss(bs, p.PartitionInformation.Id));
					}
				}

when we see this issue, the line `foreach (var p in await fabricClient.QueryManager.GetPartitionListAsync(bs))` throws an exception that we can't catch, seemingly because its thrown on a different thread.

**Comment by aL3891** [comment]
I've done some more investigation into the exception we're getting, as i suspected it does come from a worker pool thread that is not observed witch is why the process dies, however it does seem to come from our own code and not from the fabric client itself. Basically, the "service" the exception says does not exist is not the one i thought, but one referenced in an earlier, improperly awaited async call. It just happened to very frequently coincide with the call to GetPartitions, leading me down the wrong path.

I will verify this more carefully on Monday and then close, sorry for wasting your time @oanapl :/

**Comment by oanapl** [comment]
No problem, glad you found more info and got unblocked.
