### ISSUE TITLE
Deploying a service fabric application within an Azure Runbook

### ISSUE THREAD

**Issue by TVDKoni** [Azure/service-fabric-issues#288]
Hi all

I like to deploy a service fabric application within a Azure runbook or other Azure only solution. The problem is, that the runbook env does not know the Service Fabric SDK cmdlts needed from Deploy-FabricApplication.ps1. Does one has any idea, how I'm able to deploy a service fabric application in Azure only, without a developer client?

Best regards
Konrad

**Comment by masnider** [comment]
I don't know a good way to modify the Runbook's environment in order to make the SDK available (we can investigate that), but one option is to use the HTTP apis for interacting with the cluster. All the management capabilities are exposed over HTTP. More info [here](https://docs.microsoft.com/en-us/rest/api/servicefabric/).

**Comment by masnider** [comment]
@TVDKoni - We haven't heard back from you in a while about whether the http APIs were sufficient for you. If you can let us know, that'd be great. If we don't hear back from you in a while, we'll close this issue. You can reopen it if you have further questions. Thanks!

**Comment by TVDKoni** [comment]
Hi

 

We solved the issue by creating a VM and deploying from there. So please close.

 

Herzliche Grüsse / Kind regards

Koni / Konrad Brunner
