### ISSUE TITLE
Logging is far too hard to view

### ISSUE THREAD

**Issue by bklooste** [Azure/service-fabric-issues#294]
The logging is way to hard for on boarding new devs especially for cross machine cluster related issues. 

1) Very few people outside of Microsoft uses ETW logs or is familiar with how to use them. This will get worse with Linux logs. eg .NET Core use Microsoft.Extentions.Logging etc.
2) The logs are stored on the cluster which means you need to RDP in which can be tricky ( ie painfull) especially on large prod clusters behind a 3rd party load balancer.
3) There should be something so in a few clicks  / keystrokes possibly in the management app where you can see the logs is human readable format . eg No scripts. 
4) Logs should be available outside the cluster eg app insights or an Azure table again with a few clicks eg more like Raygun 

Eg logging into mulitple machines running collectGuestLogs and downloading 500 meg zip files is not easy... we  have some success with app insights logging but doesnt help much around crashes or before the service runs. 

eg easy would be add an appinsights key on the cluster and all nodes send the traces to AI  or go to the management app and see all events not just the last 5, 

Eventflow is not easy either,.

**Comment by qrli** [comment]
I have gone through the same pain, and settled on app insights in the end. AI's ready-to-use dashboard and easy query/metric is the big win, though the library and document is a bit messed up over various versions.

One thing to note is that: Microsoft.Extentions.Logging and Azure table is a really bad combination. The result table is not query-able/usable at all.

IMO, Eventflow is an abstraction which solves nothing.

Ideally, I'd hope something like logspout but use AI as the transmission target. I understand console output is not the good solution for Windows for performance and encoding reasons, but it could use ETW for windows executables/containers and standard output for linux containers.

**Comment by nrandell** [comment]
I don't know if you've tried looking at serilog/seq (https://getseq.net). I've been using this for some time and find that it really helps. I've got some libraries created at https://github.com/sceneskope/service-fabric that provide services with support for logging built in.

**Comment by dkkapur** [comment]
@bklooste, here's a few notes on your points:
1. https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-generation-app shows how to use EventSource, Extensions.Logging, and Serilog as a few examples for writing logs. I would appreciate any further feedback you have on what you found to be difficult so we can improve the overall experience for devs. SF is agnostic to the logging provider we choose to use, so you can use pretty much anything you are comfortable with. 
2. Setting up the cluster with Diagnostics turned on (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad) should automatically start aggregating your events from your cluster and putting them in an Azure storage table, so you shouldn't have to RDP into your nodes. 
3. This is interesting, and we've been thinking about this as well so would appreciate any further thoughts you have. For now, however, Application Insights, OMS, or any other similar platform (ELK, Splunk, Dynatrace, etc.) do a decent job of showing SF cluster and app level logs in an environment that is more readable and can be queried.
4. https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-analysis-appinsights goes over how to send monitoring data to AppInsights both from the cluster level (via WAD) and application / service level (EventFlow).

Generally it seems like you could consider setting up the WAD to AI sink as described in the last article linked, since it will allow you to see your cluster level events in AI instead of the storage tables that were not preferable.

Let me know if you have any further questions!

**Comment by bklooste** [comment]
@nrandell We do have in process logging via Extentions.Logging which flows to App Insights and Raygun but the problem is I need the out of process and just before you crash logs ( which you often loose with AI but i get them now with Raygun) 

@dkkapur I had a bit of a fit last week figuring out why a process kept restarting on the live cluster .. 3 would be really useful.    I will see how 4) goes when build the new cluster...I dont recall that option being there when we build the cluster.

I also had a look at event flow but I don't think event flow will get me the out of process logging  , in addition its a bit hard to set up and did they really need to write providers when they could have just fed it into Extentions.Logging.

**Comment by qrli** [comment]
For containers, I'd guess all the out-of-process logging solutions above will not work, right?

**Comment by MikkelHegn** [comment]
@qrli: Current docker stats can be forwarded by WAD if running in Azure. We are working on enabling docker logs as well.

**Comment by dkkapur** [comment]
@qrli you can add docker stats to your WadCfg in a cluster by adding the following code in the "DiagnosticMonitorConfiguration":
```
"DockerSources": {
    "Stats": {
        "enabled": true,
        "sampleRate": "PT1M"
    }
},
```

**Comment by qrli** [comment]
@MikkelHegn @dkkapur Thanks for the info. I'm glad to hear that, though I care more about docker logs than stats.

Yet, a related issue with WadCfg: How can I update them for a running cluster easily?
We have quite a few clusters, with vnet-peering/nsg/gateway, as well as many other customization/integration. Re-provisioning a cluster is too costly even for a testing setup. Is there a way to modify WadCfg without re-provisioning?

**Comment by MikkelHegn** [comment]
@qrli If you deploy an update template in incremental deployment mode, with only the WadCfg changes, then only Wad will be reconfigured. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy#incremental-and-complete-deployments

There is also the "behind-the-scenes" portal aka Azure Resource Explorer: https://resources.azure.com

**Comment by qrli** [comment]
@MikkelHegn Our cluster was created by the old "service fabric cmdlets in SDK" rather than the "service fabric ARM cmdlets" which was announced recently. Does that "incremental" deployment mode still apply?

For https://resources.azure.com, I don't see providers for service fabric. I guess it is not ready yet?

**Comment by MikkelHegn** [comment]
@qrli: Yes incremental deploy mode still applies. For resources - go through the Resource Group Node to find the resource provider for your cluster.

**Comment by bklooste** [comment]
We updated the templates and the AI logging work fine   .. Though at a default rate of 4K entries per minute. We just missed the new option an issue with templates vs the UI.  Im happy that its closed the other discussion seems to be more on resource templates and future support for containers.

**Comment by qrli** [comment]
@bklooste I'm interested in your experience with the AI logging. Can you share a bit detail?

I've also considered that approach because it requires less work on application side, but I saw SF itself keeps generating huge amount of events. AI has some upper limits on data transfer rate, and the price raises with data volume. In the SF case, 95% of the events is useless to me, but they are necessary if I need to open a support ticket for MS to investigate. So, I'm not quite sure that's a better way. 

Would be better if I can send only application events to AI but still pipe SF system events to Azure storage...

**Comment by dkkapur** [comment]
@qrli, how have you currently set up AI? What data is being sent from the cluster and how? 

What you suggested about sending app events to AI and system logs to Storage is definitely possible. For your cluster, enable Diagnostics (or add the WadCfg to your ARM template if deploying via a template) as shown [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad). This will send all [infrastructure level events ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-generation-infra)to an Azure storage table. 
Now all you have to do is set up your applications to send their events to AI. If your apps are written in .NET, this is extremely easy either via [EventFlow ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-eventflow) or[ AI SDK](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-analysis-appinsights#aisdk). If you are deploying containers, .exe's, or other types of applications, then it depends more on the logging library you use, but EventFlow generally does a very good job handling different types of events/logs (see the "Inputs" in the [EventFlow docs](https://github.com/Azure/diagnostics-eventflow)), and can send them to AI.

**Comment by qrli** [comment]
@dkkapur What we did is basically the same as what you described. We config infrastructure level events to Azure storage and use in-process AI nuget packages to send application events to AI.

My curiosity is about the WAD->AI feature which does out-of-process events collection. It looks like a cleaner solution for application side, but I'm concerning its cons.

**Comment by bklooste** [comment]
@qrli were a big company so the AI costs are small ( less than another VM).  We are planning to watch it and will look at warning and error only later ( it looks possible in the file)  .. I spend a lot of time on trying to get it in process but it misses key startup and shutdown issues so i need something out of process.. I think it will be a dev or dev ops time synch to pull logs off which would probably cost a lot more.. it would need to be installed on the cluster nodes as well.   AI cost is $2.93 per GB ... if rather it in AI than on disks of the VM..  At a quick look its about 1-1.5 G per day for 3 nodes and the 5 Node test cluser which was unused was probably 500 Meg per day..

**Comment by qrli** [comment]
@bklooste Thanks for sharing.
I remember its doc said there is a bandwidth limit for a single AI resource, but I cannot find it now. Maybe that limitation is already resolved. So it could be a via choice now...

**Comment by bklooste** [comment]
@dkkapur is there anyway of limiting the logs send to Azure eg warning/Error only .. Also is it possible to get the logs deleted after 48 hours of the disk ? I suspect its rolling already but did not find the doc,

**Comment by dkkapur** [comment]
@bklooste sorry for missing this earlier - 

1. Re limiting logs being stored in Azure storage: modify the `"scheduledTransferLogLevelFilter": "Information"` parameter in your WadCfg (assuming you are using a Windows Cluster) to have a value of "Warning", Error", or "Critical" (https://msdn.microsoft.com/en-us/library/azure/microsoft.windowsazure.diagnostics.loglevel.aspx). 

2. Re reducing the time for retaining logs: yes it is! I'll be adding these instructions to docs soon, but so that you don't have to wait for that, here goes:
In your cluster's template, edit the "fabricSettings" section to include the following sections, parameters, and set your custom value for them:
SectionName, ParameterName
AzureBlobServiceFabricCrashDump, DataDeletionAgeInDays
AzureBlobServiceFabricEtw, DataDeletionAgeInDays
AzureBlobServiceFabricPerfCounter, DataDeletionAgeInDays
AzureTableServiceFabricEtwQueryable, DataDeletionAgeInDays

Here's an example for setting them for 2 days as per your question:

```json
"fabricSettings":[
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureBlobServiceFabricCrashDump"
    },
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureBlobServiceFabricEtw"
    },
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureBlobServiceFabricPerfCounter"
    },
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureTableServiceFabricEtwQueryable"
    } 
]
```

**Comment by mattrowmsft** [comment]
For Linux
```
"fabricSettings":[
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureWinFabCrashDump"
    },
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureWinFabCsv"
    },
    {
        "parameters": [
            {
                "name": "DataDeletionAgeInDays",
                "value": 2
            }
        ],
        "name": "AzureTableWinFabEtwQueryable"
    } 
]
```
