### ISSUE TITLE
Connecting my local Client to a Service Fabric application deployed in Azure - Invalid URI

### ISSUE THREAD

**Issue by valcs007** [Azure/service-fabric-issues#304]
Hi,

I have set up a local cluster. I wrote a microservice with Remotinglisteners in VS IDE 2015 and everything works great.

**My Code Snippet:** I invoke my service using Service proxy

ICustService masterService = ServiceProxy.Create(new Uri("fabric:/Customer_Service_Fabric/CustService"));

custList = await masterService.GetCustList() 

I deployed my service fabric app to Azure and deployment was successful.

I changed the client code as below

ICustService masterService = ServiceProxy.Create(new Uri("http://testAzure.westcentralus.cloudapp.azure.com:19000/Customer_Service_Fabric/CustService"));

custList = await masterService.GetCustList() 

When it tries to connect to my service, it throws me **Invalid URI** exception

**Configuration in Azure Portal:**
My clientEndPoint : http://testAzure.westcentralus.cloudapp.azure.com:19000
My Custom EndPoints: 80,8081, 8083,8084

I have couple of questions.

1. RemotingListener doesn't work when we connect local client to Azure Service fabric apps? If it works, please let me know what might be the issue
2. I tried to replace Remotinglistener with WCFlistener but i am not able add a service reference in my client project using AutoDiscovery option and it says "No Services found in the solution".
**PS:** I observed that output type of a  regular WCF project wis a class library but microservice project output type was a console.

Please give me some code sample for using RemotingListener as well as WCF communication listener (My local client need to talk to service fabric app in Azure)

Thanks,
Valliappan

**Comment by Mardoxx** [comment]
Not an answer to your question however.. Your cluster is unsecured. Anyone could do anything to this.

**Comment by MikkelHegn** [comment]
If your client is another service in the cluster you don't have to change anything in the code. If not take a look here for external communication to services in a cluster: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services#service-fabric-in-azure

For WCF specifically see here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-wcf

**Comment by valcs007** [comment]
I already referred that article but it doesn't answer my question.

My Client is an external WPF client which is not in cluster.  Can we use the built in Remoting listener for connecting my external client to a  service running in cluster? 

If yes, is thew below code snippet in my external call right?

ICustService masterService = ServiceProxy.Create(new Uri("http://testAzure.westcentralus.cloudapp.azure.com:8081/Customer_Service_Fabric/CustService"));

custList = await masterService.GetCustList()

When it tries to connect to my service, it throws me **## Invalid URI exception**

**Comment by masnider** [comment]
Hi @valcs007 . First thing - service proxy takes a _service name_ - not an http address of the cluster. So that's the first thing you're going to have to fix. (it would still look like the name you had in your first code snippet: fabric:/Customer_Service_Fabric/CustService - that was correct. This doesn't change based on where the cluster is)

The second thing is that you probably won't be able to connect directly to your service anyway, since it is really listening behind the Azure Load Balancer on an internal IP address. So the "resolution" step that happens gives you an IP address like "10.w.x.y" which the client can't route to. 

There's a few ways to make Remoting work across that network boundary, but they're complicated (the service could lie and say that it was listening at the DNS name of the cluster on the port , for example). We should be able to get the WCF remoting one working as well. I've added some folks who can help provide that sample code. The WCF one should be almost exactly what you've done before - the WCF proxy _would_ point just at the dns address of the cluster.

**Comment by AsValeO** [comment]
I've got exactly the same question. 
Using standard Service Fabric **Remoting**
`new ServiceInstanceListener(this.CreateServiceRemotingListener)`
WPF - a client. How can it access service deployed in cloud?

Or is **Remoting** is not suitable in this case? If so, what kind of endpoind I should use to call service methods from WPF through the internet.

**Comment by VipulM-MSFT** [comment]
Yes remoting is not suitable. You can use a stateless service exposing WCF endpoint deployed with (-1 instance count) and then connect through a normal load balanced public endpoint. In the WCF service, use ServiceProxy to connect to the service inside the cluster.

**Comment by Zonciu** [comment]
Is that means the build-in listeners (like FabricTransportServiceRemotingListener) only work for communication within the same cluster?

My issue is when I debug a service(Call ServiceA) which is need to connect the SF service, I have to publish the ServiceA to SF cluster, then use remote debugging. What should I do to run the service locally and connect to the SF service?

**Comment by aplocher** [comment]
Does the Wcf Endpoint only work with .NET Framework Stateless Services?  Is there a way to remotely communicate with a .NET Core Stateless Service?  Thank you
