### ISSUE TITLE
CRM and MasterCrm ETW traces filling up Application Insights

### ISSUE THREAD

**Issue by doverton51** [Azure/service-fabric-issues#307]
I'm currently attempting to get application insights working against Service Fabric Owin Web APIs. The normal request logging is working absolutely fine, but I'm seeing a very high volume of extraneous ETW logs going into app insights, which would use up our data cap almost immediately. I need to find out how to stop these messages being logged out to Application Insights from the service fabric cluster. 

This is happening when running against the Service Fabric Local Cluster, or when deploying to a cluster on Azure.

All of the requests have a Taskname of 'CRM' or 'MasterCrm' and a source of 'AzureDiag_ETW'. From doing some searching I've found that these were mentioned as a 'Known Issue' in the release notes for Service Fabric SDK 2.2.207 (https://servicefabricsdkstorage.blob.core.windows.net/public-release-notes/Microsoft%20Azure%20Service%20Fabric%20Release%20Notes%20-%20SDK%202.2.207%20-%20Runtime%205.2.207.docx), but they still occur with SDK version 2.6.210.  Example trace:

![image](https://user-images.githubusercontent.com/846955/26869060-f51432c8-4b62-11e7-9408-bfeda0a20c04.png)

I've tried various things in the ApplicationInsights.config file, and turning down the logging level of the cluster, but nothing seems to make a difference.

Does anyone know how I can turn the CRM \ MasterCrm traces off?

**Comment by MikkelHegn** [comment]
@doverton51 this part of your Wad configuration is the event stream emitting these events:
                "EtwManifestProviderConfiguration": [
                {
                    "provider": "cbd93bc2-71e5-4566-b3a7-595d8eeca6e8",
                    "scheduledTransferLogLevelFilter": "Information",
                    "scheduledTransferKeywordFilter": "4611686018427387904",
                    "scheduledTransferPeriod": "PT5M",
                    "DefaultEvents": {
                    "eventDestination": "ServiceFabricSystemEventTable"
                    }
                }

Can you verify you have the  "scheduledTransferKeywordFilter" set to "4611686018427387904"? This filter is intended to give you only actionable event in the stream.

You can verify by doing remote trace streaming from your cluster using Cloud Explorer in Visual Studio. The default filter in the Diagnostics Events Viewer in VS sets this via a hex value to: Microsoft-ServiceFabric:4:0x4000000000000000 (the equivalent of the decimal filter value in the wad config).

The event you posted says that a placement was scheduled because of new replicas, whereas the issue you've pointed to in our earlier SDK was emitting events were no placements were scheduled. Please check if all the events you see are indicating placement of replicas or not. It could be that your cluster is continuously moving replicas around for some reason you need to look in to.

**Comment by masnider** [comment]
@doverton51 - was Mikkel's advice useful, or can you let us know if you're still having problems? I'm also adding some folks who can offer other ways to tune and control the amount of information coming out of the clusters.

**Comment by dkkapur** [comment]
@doverton51 if you update your cluster to the latest [Service Fabric version (5.6.220)](https://blogs.msdn.microsoft.com/azureservicefabric/2017/06/20/release-of-sdk-2-6-220-and-runtime-5-6-220-refresh-for-windows/) this should no longer be as much of an issue, since we have reorganized our log channels.

**Comment by masnider** [comment]
@doverton51 - Hi there! It's been a couple releases since we fixed this. If you could get back to us and let us know if this has been resolved to your satisfaction that'd be great! If we don't hear back from you soon, we'll consider this closed.

**Comment by doverton51** [comment]
@masnider - apologies but I'm no longer working on the Service Fabric project I was on at the time, so I've no way of verifying. From my side of things please consider it closed if you believe you've fixed it.

**Comment by masnider** [comment]
@doverton51 thanks for getting back to us. We'll close it down. If other people see this they can reopen or file a new issue.
