### ISSUE TITLE
Error provisioning new 5.6 cluster: missing WRPSettings.xml

### ISSUE THREAD

**Issue by njtrentacoste** [Azure/service-fabric-issues#318]
I'm trying to provision a new cluster using the 5.6 standalone package and I receive the following error:

**Standalone package dependent files not found. Check package structure. Error: System.IO.FileNotFoundException: Cannot find Fabric resource file WRPSettings.xml in C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code C:\Windows\Microsoft.Net\assembly\GAC_64\Microsoft.ServiceFabric.DeploymentManager\v4.0_5.0.0.0__31bf3856ad364e35.**

Here's the contents of the trace log.:

```
2017/06/16-14:05:14.412,Info,4520,SystemFabricDeployer.SFDeployer,Running Best Practices Analyzer...
2017/06/16-14:05:14.412,Verbose,4520,SystemFabricDeployer.SFDeployer,Validating executing user is an Administrator.
2017/06/16-14:05:14.412,Verbose,4520,SystemFabricDeployer.SFDeployer,Converting JSON config to model.
2017/06/16-14:05:14.865,Error,4520,SystemFabricDeployer.SFDeployer,Standalone package dependent files not found. Check package structure. Error: System.IO.FileNotFoundException: Cannot find Fabric resource file WRPSettings.xml in C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code C:\Windows\Microsoft.Net\assembly\GAC_64\Microsoft.ServiceFabric.DeploymentManager\v4.0_5.0.0.0__31bf3856ad364e35.
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.FindFabricResourceFile(String filename)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator.PullRequiredWrpSettings(SettingsType& wrpSettings, IDictionary`2& requiredParameters)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator..ctor(StandAloneInstallerJsonModelBase inputConfiguration)
	   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, Boolean throwIfError).
2017/06/16-14:05:14.865,Verbose,4520,SystemFabricDeployer.SFDeployer,Validating CAB file is valid at C:\users\ntrentacoste\Desktop\ServiceFabricv5.6\DeploymentRuntimePackages\MicrosoftAzureServiceFabric.5.6.220.9494.cab.
2017/06/16-14:05:15.912,Error,4520,SystemFabricDeployer.SFDeployer,Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.
2017/06/16-14:05:15.912,Error,4520,SystemFabricDeployer.SFDeployer,Cluster Setup cancelled due to validation error(s) found by Best Practices Analyzer. Inspect details in DeploymentTraces log folder local to executing location.
```

This is a brand new installation, not an upgrade from a 5.5- cluster.  Any help is greatly appreciated.

Thanks,
    Nick

**Comment by njtrentacoste** [comment]
Just an update, this appears to be some conflict with having the SDK installed.  I uninstalled the SDK and testing succeeded.  I'm trying to use a single machine (not part of the cluster) for both provisioning as well as app deployment.  For deployment I need the SDK.  I read that the SDK should not be installed on a cluster node but have read nothing about it being a conflict with the standalone setup package.  Any guidance is greatly appreciated.

Thanks

**Comment by dkkapur** [comment]
@njtrentacoste thanks for bringing this up. The conflict between the SDK and the standalone setup package is a known issue that we are trying to resolve in the next few months. In terms of the current situation, what did you end up doing to get around this issue? We sometimes see people deploying the cluster from one of the machines in the cluster, and then deploying their apps to the cluster from a separate machine.

**Comment by njtrentacoste** [comment]
If I recall correctly, what I did was uninstall the SDK.  Then I provisioned the cluster, then reinstalled the SDK and deployed my app.  Again, if memory serves me correctly, the only conflict I have is on the first provision.  I don't think I have any conflicts after that.  Though, the only interaction I have via powershell after the cluster is provisioned (not included app deployment) is performing a Cluster Configuration Update.  And I don't recall having issues with that.

I hope that helps.  If I can remember anything else I post another comment.  If you have further questions I'd be happy to answer as best I can.  Thanks for your help.

**Comment by sivesind** [comment]
Hi!

Love the work on Service Fabric for on-prem, I've been testing it for the last two weeks. I ran into the same problem today, I encourage you to fix it :-) It's a bit annoying to use two different machines for provision , and deploy.

Regards,
Lars

**Comment by dkkapur** [comment]
@njtrentacoste when you say on the "first provision," just to confirm, you mean initially when you tried to provision the cluster while you still had the SDK deployed correct? It worked fine once you provisioned without the SDK, and then reinstalled the SDK for app installs and updates. Also appreciate the additional data point on being able to do cluster config updates without going through the remove/reinstall process for the SDK. 

@sivesind Lars, yes - I agree! We're on it :) will not be an immediate fix because of how we chose to prioritize some of the upcoming work, but I will keep you posted on progress in the coming months.

**Comment by elscript** [comment]
@dkkapur Uninstalling SDK does not help, when I try to validate configuration file, any ideas? Error message is the same: 
Standalone package dependent files not found. Check package structure. Error: System.IO.FileNotFoundException: Cannot fi
nd Fabric resource file WRPSettings.xml in C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code C:\Windows\M
icrosoft.Net\assembly\GAC_64\Microsoft.ServiceFabric.DeploymentManager\v4.0_5.0.0.0__31bf3856ad364e35.
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.FindFabricResourceFile(String filename)
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator.PullRequiredWrpSettings(SettingsType&
 wrpSettings, IDictionary`2& requiredParameters)
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator..ctor(StandAloneInstallerJsonModelBas
e inputConfiguration)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJson
ModelBase config, Boolean throwIfError).
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces fo
lder.

**Comment by njtrentacoste** [comment]
@dkkapur Yes, that's what I meant.

**Comment by maburlik** [comment]
To clarify - today our SDK installation installs two entries in Windows ARP: Microsoft Service Fabric (the runtime) & Microsoft Service Fabric SDK. When we suggest to uninstall the SDK we mean to uninstall both MSIs. Is this what you have done? The runtime installation places those assemblies in GAC.

The reason this is conflicting is because the GACed assemblies don't have necessary resource files placed locally in order to deploy the standalone cluster, and since GACed assemblies are loaded first, the resource files are not found locally when executing cluster deployment using the standalone package from the same machine. For this reason until we improve the experience, SF must be completely uninstalled from the machine.

Thanks,
Max

**Comment by njtrentacoste** [comment]
@maburlik Yes, when I say uninstalling the SDK fixed the issue, I mean uninstalling both the SDK as well as the Runtime.  Sorry for any prior confusion.

**Comment by sivesind** [comment]
@maburlik: The GAC is the root of almost all dependency evil 😉 I hope you
stop using it.

/Lars

Den tor. 27. jul. 2017, 21:34 skrev Nicholas J Trentacoste <
notifications@github.com>:

**Comment by elscript** [comment]
For addition: are you going to do something with this situation? This is very inconvenient to install/uninstall SDK every time I need to create the cluster/upgrade and so on

**Comment by elscript** [comment]
And one more thing: during cluster create, I've faced with the fact, that nowhere mentioned required vc++ 2015 redist. SF intaller service simply doesn't start on node without vc++ 2015

**Comment by maburlik** [comment]
Thank you for your comments and suggestions. We value your feedback and have items tracking the changes.

RE: The GAC is the root of almost all dependency evil 
We are in the process of migrating our code to use CoreCLR across the codebase and will at some point move away from using GAC :)

RE: automatic uninstall does not clear GAC as we expect.
Uninstallation works with best-effort so as not to block the removal scenario or break existing user workflows, so we don't forcefully remove resources if they are being used. It's likely the assemblies were left in GAC because there were open handles to these at the time of uninstallation. To safely and reliably remove installation artifacts, make sure when uninstalling to close any processes that will causes such conflicts such as powershell sessions, event viewer, Visual Studio, and Service Fabric tools. We are working to improve this experience.

RE: This is very inconvenient to install/uninstall SDK every time I need to create the cluster/upgrade and so on
As of SF SDK v 2.8.219 we have moved the standalone installation tools into the SDK toolset, so these operations should work. Please follow up if you hit any issues.
