### ISSUE TITLE
Reverse Proxy Load Balancer Health Check

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#333]
Hey guys,

we have a three node cluster and we want to use the service fabric reverse proxy.
We also have an API Gateway where we proxy the requests to our upstream services.

In the gateway it would be good to have some sort or load balancing and failure detection when proxying to the reverse proxies of our three nodes, therefore we want to deploy a load balancer in between.

Is there some sort or health check endpoint within service fabric so the load balancer can exclude down nodes from it's list? Of cause we can deploy a health service within service fabric but if this service fails the whole node would be handled as "down".

**Comment by VipulM-MSFT** [comment]
On every node you should simply forward the requests to the local reverse proxy, as most likely the requests coming to your API gateway are already load balanced. Reverse proxy gets a notification whenever an endpoint goes offline due to node being down, process being down or movement caused by upgrade and load balancing. @kavyako and @BharatNarasimman if they have better suggestion.
