### ISSUE TITLE
Name resolution (case-sensitivity) with Naming Service and Reverse Proxy

### ISSUE THREAD

**Issue by ShelbyZ** [Azure/service-fabric-issues#339]
We are using the Reverse Proxy to take requests at a single externally exposed location and route them through the system to our internal components.  We end up with the following addresses:

> **Reverse Proxy**
> https://www.example.com:9999/$fabricAddress/$serviceName

> **Internal Service**
> $fabricAddress - fabric:/FrontEnd.Service
> $serviceName - TestService
> https://localhost:6666/callback

So we could expect a request to https://www.example.com:9999/FrontEnd.Service/TestService/callback to get routed through the Reverse Proxy to our internal service (assuming correct setup of the Reverse Proxy).  When hooking up to a third party provider (responsible for talking to our internal service), we noticed that they were making requests to https://www.example.com:9999/FrontEnd.Service/testservice/callback which resulted in a 404 Not Found.

With further digging it appears that the naming service is case-sensitive when handling service resolution:

```csharp
string address = @"fabric:/FrontEnd.Service/TestService";
string badAddress = @"fabric:/FrontEnd.Service/testservice";

var resolver = ServicePartitionResolver.GetDefault();
var resolved = resolver.ResolveAsync(new Uri(address), ...).Result;
var badResolved = resolver.ResolveAsync(new Uri(badAddress), ...).Result;
```

In the above code, I would find that resolved points to our service, but badResolved does not find any matching service.  With this casing issue it becomes difficult to correctly route requests, this behavior is different than a typical exposed web service/site, and puts an additional requirement on third-party actors.

**Comment by kavyako** [comment]
As it stands today, name resolution is case sensitive, due to some internal limitations. We are looking at options or workarounds for this.
Would something like this help your case:
If **all the services are created with lower case names**, we could expose an option in the resolve paths(Reverse Proxy/ServicePartitionResolver) to operate in case insensitive mode.

**Comment by ShelbyZ** [comment]
It would be a step in the direction we are looking for.  It might be as simple as having the registration of the service changed to lower case and the key comparison on the internal storage also lower case.

**Comment by Mardoxx** [comment]
[URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.](https://www.w3.org/TR/WD-html40-970708/htmlweb.html)

**Comment by ajeetcoolkarni** [comment]
@ShelbyZ or anyone out here, can you guys please tell me how to use naming service? I don't see any sample code available on google. Also, this [https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy](url) example is theoretical, can anyone please tell me how to create reverse proxy service in SF? Thanks.

**Comment by sridmad** [comment]
@ajeetcoolkarni ,

Thanks for the feedback on the docs. We are working on improving them this month. In the mean time following should help you make progress.

Enabling Reverse Proxy: Since Reverse Proxy is a built in service it has to be enabled either at Cluster creation time or through upgrade. 

**Enabling through portal on Cluster creation:** The setting to enable it is under node configuration. See image below.
![image](https://user-images.githubusercontent.com/7445097/33688856-e8f243ea-da91-11e7-865d-3cf51f3d5a14.png)

**Sample ARM templates to enable Reverse Proxy.**
https://github.com/ChackDan/Service-Fabric/tree/master/ARM%20Templates/ReverseProxySecureSample#configure-https-reverse-proxy-in-a-secure-cluster has sample templates that can be used as starting point for setting up Reverse Proxy in a secure cluster.

Thanks,
-sridhar

**Comment by kavyako** [comment]
We will not be changing this behavior in the immediate future. 
Closing the issue.
