### ISSUE TITLE
Update ETW settings

### ISSUE THREAD

**Issue by silvioboehme** [Azure/service-fabric-issues#355]
Hi!

Is there a prefered/working way to change some ETW settings after a Service Fabric application is deployed?

1.) add some ETW logs to the Service fabric code....something like this
`private const int ServiceActionExecutionSuccessId = 20;`

`[Event(ServiceActionExecutionSuccessId, Level = EventLevel.Informational, Message = "{4}", Keywords = Keywords.ServiceActionExecutions)]`
```
public void ServiceActionExecutionSuccess(string serviceName, long replicaOrInstanceId, Guid partitionId, string nodeName, string message, string action, long milliseconds, string request, string response) =>
            this.WriteEvent(ServiceActionExecutionSuccessId, serviceName, replicaOrInstanceId, partitionId, nodeName, message, action, milliseconds, request, response);

```

2) logging works as expected

3) just change the EventId
`private const int ServiceActionExecutionSuccessId = 30;`

4) this Event is now never logged neither with Id 20 or 30.
Updating the whole application (increased all manifest versions) doesn't work.

How can I change or update a running Service Fabric Cluster to accept new ETW settings?

**Comment by silvioboehme** [comment]
Also I found some Information to add the "Version" property to the EventAttribute and increase this if there are some changes.

But the result ist: Event is logged, but all fields are empty.
This is really annoying.

**Comment by qrli** [comment]
Though my own investigation, it is an issue of ETW rather than anything else.
To put it simple: ETW does not like schema changes.
 
As long as the ETW schema is registered, all following ETW events of the same provider will use the same schema, even though the there is a updated version. You need to restart the VM so that the new schema is registered.

My solution is to avoid using EventSource directly. Instead, use a stable abstraction layer, e.g. Microsoft.Extensions.Logging, NLog, Service Fabric's logging API, etc.

**Comment by silvioboehme** [comment]
Ok. Thanks. Currently I'm migrating to use EventFlow, because the combination of ETW/EventSource/AzureDiagnostics/OMS is absolutely not useable.
It works maybe 30% of the time, and if it stops working you don't know why,because there  is no error or hint....just nothing.

Please Close this issue.

**Comment by masnider** [comment]
@silvioboehme - ok! Adding a couple people FYI so that maybe we can work this into our guidance/recommendations.

**Comment by mattrowmsft** [comment]
@silvioboehme  can you give more info on your setup?  I'm imagining app with EventSource class, WAD configured to listen to EventSource provider name and then OMS hooked up to read WAD's tables.

You aren't allowed to make breaking changes between versions of an EventSource.  Your example of changing an event's Id isn't allowed for example.  You always have to add fields rather than subtract etc.

The big advantage in using something like EventFlow is that configuration for the logs lives with the app itself.   I think this makes a lot of sense for those going the microservice route.
