### ISSUE TITLE
TCP endpoint not added to Windows' reserved ports (HTTP endpoints are)

### ISSUE THREAD

**Issue by hravnaas** [Azure/service-fabric-issues#368]
I am unsure whether this is an issue or not, so wanted to flag it just in case.

When a service starts, SF seems to allocate a port from the "applicationPorts" range and add it to Windows as an excluded port. I can see this by running "netsh int ipv4 show excludedportrange tcp" on the node in question.

My service has 3 endpoints, 2 HTTP and 1 TCP. Both HTTP endpoints' ports are listed as excluded, but the TCP port does NOT get added to the excluded list. The TCP endpoint has its port dynamically allocated by SF. Is this omission intentional? Endpoint from the service manifest:

`<Endpoint Name="PipelineComponentTcpEndpoint" Protocol="tcp" />`

My concern is that as the TCP port is not excluded, Windows might snag it for use by another app and cause a conflict down the road. So far I have not hit this to my knowledge.

Thanks,
Hans

**Comment by VipulM-MSFT** [comment]
We modify the ephemeral range on the machine so that it excludes the ports we manage. You can check the range using "netsh int ipv4 show dynamicport tcp" 

So as you have notice it will not conflict with the dynamic ports used by other application unless used explicitly by some app. I am going to close this issue, if you have more questions feel free to open it.
