### ISSUE TITLE
What is the right size for the disk space when creating the Service Fabric cluster?

### ISSUE THREAD

**Issue by rogertong** [Azure/service-fabric-issues#370]
What is the right size for the disk space when creating the Service Fabric cluster?

**Comment by ChackDan** [comment]
Please review this doc - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity#primary-node-type---capacity-guidance

**Comment by vturecek** [comment]
@rogertong There's a minimum requirement which is specified in the doc @ChackDan linked to. The *right* size depends on how much data you're planning to store in the cluster with stateful services. Keep in mind that you will have at least 3 copies of that data for high-availability, and you should always plan for *at least* 20% additional overhead space so that there is room for data when a node fails or is being updated. In general, my advice would be to give yourself plenty of room so you don't risk running out of space.

**Comment by masnider** [comment]
@rogertong you can also see some more of our thinking on this in my answer [here](https://stackoverflow.com/questions/36684805/azure-service-fabric-reliable-collections-and-memory/36752442#36752442) on StackOverflow
