### ISSUE TITLE
When removing a service from an sfproj via Visual Studio, not all references to it are deleted

### ISSUE THREAD

**Issue by ohadschn** [Azure/service-fabric-issues#376]
The service is removed from the `sfproj` itself, but not from the application manifest (`ApplicationManifest.xml`) nor from the application parameter files (`Cloud.xml`, `Local.1Node.xml`, `Local.5Node.xml`). 

To clarify, I'm talking about deleting a service from the _Services_ folder in a Visual Studio 2017 (15.2 26430.16) `sfproj`.

**Comment by vturecek** [comment]
@dbreshears Might be good to at least remove ServiceManifestImports and any default service definitions when a service is removed. Parameters might be trickier, given that a parameter is not always 1:1 to a specific service.

**Comment by dbreshears** [comment]
If you have multiple services and remove one of them we do clean up the application manifest and parameter files by calling C:\Program Files\Microsoft SDKs\Service Fabric\\Tools\AppManifestCleanupUtil\AppManifestCleanupUtil.exe  from our targets/build task the next time you build.    @ohadschn, are you not seeing this behavior once you build the next time?   If you remove the last Service reference I don't believe we will cleanup the manifest because the target doesn't get called,  presumably due to the app project containing zero references to service projects.

**Comment by ohadschn** [comment]
I may have not rebuilt. It is a bit counter-intuitive to be honest, this is something I would expect to happen at design time (just like the sfproj is updated at design time).

**Comment by masnider** [comment]
@ohadschn  - were you able to confirm this one way or the other?

**Comment by masnider** [comment]
@dbreshears - is this something we're considering improving in the tooling?

**Comment by dbreshears** [comment]
The utilities that update the manifests are installed by the SDK  (FABActUtil / AppManifestCleanup) and we invoke them via our build targets/tasks based on references from the SFApp project.    I will agree removing and not updating the manifest until build it is a bit counter-intuitive , however we don't have plans currently to implement this in the VS  design time experience.
