### ISSUE TITLE
Trying to compress application package without coping to service fabric

### ISSUE THREAD

**Issue by lurock** [Azure/service-fabric-issues#382]
The documentation shows you can compress a package without copying it to the service fabric but when I try I get the error message below.

Here is the docs like: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-package-apps

**Running command:** 
Copy-ServiceFabricApplicationPackage -ApplicationPackagePath .\MyApplicationType -CompressPackage -SkipCopy

**throws an error:** 
Either ImageStoreConnectionString must be provided explicitly or connect to the cluster to attempt automatically fetching the value.

**Comment by Mardoxx** [comment]
Did you run `Connect-ServiceFabricCluster` before hand?

**Comment by lurock** [comment]
No but I shouldn't have to when I am just trying to compress the package and not trying to copy it.  I am wanting to do this on the build server so that when I am ready to deploy the package it is already compressed.

**Comment by shlomcoh** [comment]
No sure what is the purpose of you compression but you can try using Microsoft ServiceFabricSDK and create a sfpkg file with "New-ServiceFabricApplicationPackage", you don't need to be connected to the cluster and you can easily deploy it later with  "Publish-NewServiceFabricApplication" or "Publish-upgradedServiceFabricApplication"

**Comment by oanapl** [comment]
@lurock, this is a known issue. Unfortunately, the fix didn't make it in our incoming release, but was fixed already in our next one.
You are correct, you shouldn't need to connect to the cluster to compress the package. As a workaround until the fix comes out, you can provide a ImageStoreConnectionString in the copy application package cmdlet (any one will work, even a bogus string).

@shlomcoh the purpose of compression is to reduce the size of the package and the number of files so that copy to cluster, provision and unprovision can be faster. The sfpkg is orthogonal with the compression - it's simply a zip around the initial package, which could be compressed or uncompressed. Internally, we don't copy that one single file (though the scripts make it look so), but we unpack it as we need to get metadata from it. We have a planned feature to add support for copy that one file all the way into the cluster.

**Comment by oanapl** [comment]
This fix is in our latest release.
