### ISSUE TITLE
'Partition is below target replica or instance count' error seen with new dev cluster

### ISSUE THREAD

**Issue by BrendanBrolly** [Azure/service-fabric-issues#39]
I'm trying to just go through the service fabric samples and have created my empty stateful service. I'm unable to deploy it however as I am getting an error with my cluster. If I look in Service Fabric explorer I see that the issue is with fabric:/System/FaultAnalysisService and the bottom most error is:

Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count. 

I also see a warning on a replica of:

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open. Error =System.Fabric.FabricException (0)
An error occurred during this operation.  Please check the trace logs for more details.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Data.Log.LogManager.d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

The replica also has an 'in build' status which doesn't appear to be changing.
I get this error irrespective of whether I have tried deploying a service to the cluster. I've tried resetting the cluster, deleting it and creating a new one and rebooting my machine. Any suggestions for what the issue may be? I'm not sure where to look for more information - I can't see anything in the log directory that would help.
Apologies if this is something that's already been covered in previous threads. I didn't spot anything but may have missed it.
Thanks a lot

Brendan

**Comment by mkosieradzki** [comment]
Have you checked your disk space as in: #15 ?

**Comment by BrendanBrolly** [comment]
Yes. I've about 2.5G which should be enough. I've moved my cluster to another disk though with a bit more space and to a location the runtime virus checker ignores. One or the other fixed it.
Thanks for your help.

Brendan

**Comment by wingfeng** [comment]
I got the same error even I setup a empty dev cluster.

**Comment by stan-dcip** [comment]
Why was this closed?  How did you fix it?  Same problem here.

**Comment by BrendanBrolly** [comment]
As I mentioned, it just went away when I switched the location of the cluster on disk. Not sure whether it was disk space or runtime virus checker.

**Comment by caokennedy** [comment]
I got the same error when I set up an empty dev cluster too. Initially I had 'Warning' health status which then changed to 'Error' without me changing anything.
Has anyone got further information on this issue and whether it is a disk space issue or possibly a network/port configuration issue?

**Comment by oanapl** [comment]
@caokennedy , the report "Partition is below target replica or instance count" can happen in many situations. There is no single root cause for all cases. It may be a bug in the service code that prevents replicas from starting up, it may be a configuration error (for example, you ask for more replicas than the number of nodes in the local cluster), an environment error (like disk space).
See [more information about the partition health reports](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-understand-and-troubleshoot-with-system-health-reports#partition-system-health-reports). 
Next steps are to check replicas health for that partition (to see if replicas are recycled frequently, in which case they crash in a loop, or if there are replicas in warning/error states - maybe replication is slow and it takes longer to build the replicas etc). You can also check the event log to see if there are any entries related to that partition from service fabric.

**Comment by caokennedy** [comment]
Hi @oanapl , 
Thank you for your help. I am still having issues with this. 
When you refer to the service code to you mean the application code? And "it may be a configuration error (for example, you ask for more replicas than the number of nodes in the local cluster)", does this refer to the ApplicationManifest.xml and ServiceManifest.xml files? Where are do you ask for replica's? 
Thanks

**Comment by zachChilders** [comment]
I just got this error following the docs here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers

Is there any guidance in decoding this error?  I wish it was more specific to what my problem was, and that the official docs didn't repro this issue.

**Comment by oanapl** [comment]
@zachChilders , please open a new issue so we can properly follow up.
