### ISSUE TITLE
Azure portal not showing nodes and applications

### ISSUE THREAD

**Issue by lurock** [Azure/service-fabric-issues#390]
My NSG looks like this as far as allowing incoming connections:

![image](https://user-images.githubusercontent.com/12436542/29035426-67e5e8e2-7b50-11e7-97b3-76319e065cb2.png)

When I go to look at the Service Fabric settings the Azure portal shows no nodes or applications yet all the nodes and applications in the Service Fabric are there and functioning properly.  How do I make it so the Azure portal can see the nodes and applications.  I know if I change the incoming rule on 19080 to any for the source it fixes the issue, but I only want to allow my IP address to that external port, but I still want the Azure portal to show the nodes and applications.
![image](https://user-images.githubusercontent.com/12436542/29035606-1149d998-7b51-11e7-83f1-62b201ef7db9.png)

**Comment by jjcollinge** [comment]
The Service Fabric Azure Resource Provider requires public access to that endpoint in order to report the nodes/apps in the portal as documented here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patterns-networking. I don't believe Azure publishes Resource Provider IP ranges - just datacenter IP ranges.

You can secure the endpoint with client certificates or Azure Active Directory. If you simply don't want that endpoint exposed then AFAIK you'll have to live with the unpopulated portal (at least for now). Hopefully, somebody from the team can clarify.

**Comment by mkosieradzki** [comment]
That's not true.

It is enough if your cluster is able to long poll the SFRP (`https://<region>.servicefabric.azure.com/runtime/clusters/`)

**Comment by jpoon** [comment]
In addition to exposing the `19000` and `19080` ports through the NSG, make sure the management endpoint is configured correctly:

```
        "managementEndpoint": "[concat('http://',reference(variables('public-ip-name')).dnsSettings.fqdn, ':',variables('nt0fabricHttpGatewayPort'))]",
```

for an insecure cluster or a `https` prefix for a secure one.

**Comment by jpoon** [comment]
What do you mean by "long poll"?

**Comment by mkosieradzki** [comment]
I mean that Cluster initiates communication to the SFRP using long polling (https://en.wikipedia.org/wiki/Push_technology#Long_polling) and when SFRP wants to query the cluster it just uses the connection from Cluster to perform the query.

Basically I am using clusters with 19080 and 19000 hidden deep behind the firewalls and SFRP works correctly (I see all my apps and nodes). If I remember correctly that was added around version 5.7.

**Comment by jpoon** [comment]
My understanding was that the SFRP initiates communication to the Cluster (hence why 19000/19080) needed to be open). If it's the other way as you state, then yes, these ports don't need to be exposed.

**Comment by mkosieradzki** [comment]
It was true before version 5.5 (I have checked the exact version number). @ChackDan can confirm this.

**Comment by vaishnavk** [comment]
SFPR first uses the long poll channel to send queries to the cluster. If that fails, we fallback to the original model of making an outbound connection from SFRP to the cluster (this was mainly done for supporting queries on clusters older than 5.5 version, but is occasionally helpful with long poll channel encounters any failure.

**Comment by 4deeptech** [comment]
I thought I would add that the cluster certificate has to be updated with the resource provider to match that of the one used in the cluster.  I had a cluster tank due to an invalid primary cert and an expired secondary and manually had to fix this on each node in the scale set, however, updating the certificate for the resource provider appears to be something that only MS support can do...I believe.  At least according to this:  https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Security/Fix%20Expired%20Cluster%20Certificate%20Automated%20Script.md in step 6 NOTE 2.  I got my cluster back up and running but the portal looks like the screenshot from @lurock where it has Not Found messages.  Also the Security tab still shows the wrong certs and the Upgrade service indicates SFRP errors....most likely related to the same thing.

**Comment by sharma-the-karma** [comment]
I have verified the cluster cert is matching, I am creating a new Cluster and I am facing the same issue with. This is Ubuntu, when deploying Windows Cluster I don't see this issue. Any pointers what is causing this?
Service Fabric Version is 7.1.418.1

![image](https://user-images.githubusercontent.com/35385560/85817466-e8291900-b722-11ea-9dad-047bfc7ca31b.png)
