### ISSUE TITLE
Unregister-ServiceFabricApplicationType : Operation timed out

### ISSUE THREAD

**Issue by 0shi** [Azure/service-fabric-issues#398]
Similar to the issue encountered in [347](https://github.com/Azure/service-fabric-issues/issues/347), but we are encountering an issue where Unregister-ServiceFabricApplicationType times out occasionally (Twice this week in two different builds so far, we've seen it more intermittently in the past) when performing upgrades with the Unregister Unused Versions flag.

I have not found any documentation regarding the default timeout of this cmdlet, but looking at our failed builds, it appears to be a 2 minute timeout (With our deployment model I would not expect there to be more than one unused version of the application on the cluster at a time). Looking at our successful builds, we are frequently in the 1 - 1.5 minute range for this operation, and would rather not be that close to the timeout.

Our deployments are done through VSO agents using the default steps ([Service Fabric Deploy](https://www.visualstudio.com/en-us/docs/build/steps/deploy/service-fabric-deploy)) so even if we were comfortable with it, changing the values in Publish-UpgradedServiceFabricApplication.ps1 to increase the timeout for this ourselves will not be effective or maintainable across multiple deployment environments.

Is there any chance of adding an input parameter to the Publish-UpgradedServiceFabricApplication script for this timeout along the lines of CopyPackageTimeoutSec and RegisterPackageTimeoutSec?

**Comment by ahofman** [comment]
Hi @masnider and @MikkelHegn ,

This issue is significantly impacting our continuous deployment pipeline. Can we get an update here? Would you accept a PR to make the unregister timeout configurable?

(I work in the same team as @0shi ).

**Comment by MikkelHegn** [comment]
Filed enhancement in our backlog - sorry for the long delay...

**Comment by 0shi** [comment]
This one hasn't hit us for a while, but much appreciated.
Cheers.

**Comment by am11** [comment]
This one is hitting us as well. In VSTS-task repo they have added `RegisterPackageTimeoutSec` in those scripts (e.g. [Microsoft/vsts-tasks/Tasks/ServiceFabricDeploy/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1#L97](https://github.com/Microsoft/vsts-tasks/blob/9e119331e/Tasks/ServiceFabricDeploy/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1#L97)). I wired it up in our deploy script and made a copy of `Public-{New,Update}ServiceFabricApplication.ps1` from SDK directory, that `Deploy-FabricApplication` calls in order to fix the VisualStudio F5 experience.

Would be nice to have `RegisterPackageTimeoutSec` argument in Deploy and Publish script OOTB in upcoming revisions of SDK. :)

**Comment by amanbha** [comment]
Scripts shipping with SF SDK will expose timeouts for Register and Unregister Application Type, the fix will be in 6.2 release.
