### ISSUE TITLE
Service Fabric Reverse Proxy times out when targeting Kestrel

### ISSUE THREAD

**Issue by thomashjorslev** [Azure/service-fabric-issues#40]
I am new to Service Fabric and so far experimenting with different ways to use it.

I have created a Service Fabric application called ServiceFabricApp2 in VS 2015. I have created two services, using the VS templates; "Stateless Web API" and "ASP.NET Core -> Web API". I just let the templates generate the default ValuesController and I can successfully invoke both services on [http://localhost:8391/api/values](http://localhost:8391/api/values) and [http://localhost:8776/api/values](http://localhost:8776/api/values) I can see both these URLs in the Service Fabric interface.

However, when I try to access the services using the Reverse Proxy, on [http://localhost:19081/ServiceFabricApp2/WebApi1/api/values](http://localhost:19081/ServiceFabricApp2/WebApi1/api/values) and [http://localhost:19081/ServiceFabricApp2/Web1/api/values](http://localhost:19081/ServiceFabricApp2/Web1/api/values) only the first one (the one not using Kestrel) works. The last one times out after some time (a minute I guess, but I can check if it is important).

The difference seems to be that the Kestrel uses `Transfer-Encoding:chunked`. I have found some references to Kestrel having problems with RPs but they should be fixed in 1.0.0.

If I set a breakpoint in the API method, it gets hit immediately, but the response never reaches the client. The code of the API method is:
```
// GET api/values
[HttpGet]
public IEnumerable<string> Get()
{
    return new string[] { "value1", "value2" };
}
```

This is from `project.json`:
``` 
"dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.ServiceFabric": "5.1.163",
    "Microsoft.ServiceFabric.Data": "2.1.163",
    "Microsoft.ServiceFabric.Services": "2.1.163"
  },```

**Comment by qrli** [comment]
I'm facing the same issue too.

Adding a little more info: client side actually received HTTP response header through the reverse proxy, but not the body.  Chrome waits for the body until timeout, while IE immediately treats it as failed.
From the ASP.NET Core log, the request finished in milliseconds. So it looks like the reverse proxy does not handled the later chunks.

**Comment by masnider** [comment]
Hi @thomashjorslev and @qrli - can you guys confirm the version of the Service Fabric runtime and SDK that you are working with? As far as we know this should be fixed in the latest version of SF which we released a few weeks ago (5.2 runtime, 2.2 SDK). Previously we did not support chunked encoding which Kestrel required.  If you're still on 5.1, then upgrading your local environment and the nuget packages and trying again is your best option, but if you're still having problems with 5.2/2.2 then let us know.

**Comment by qrli** [comment]
@masnider Thanks. Glad to hear that.
To be accurate, I'm not using the SDK runtime. I'm using the standalone runtime for Windows Server, because I found it more similar to the Azure version, more features (e.g. custom node types, reverse proxy) supported, and fit better for our testing machines (e.g. 3 nodes for single machine setup as well as local cluster support).

Does it also have a new release? If so, I will try out after holiday.

**Comment by masnider** [comment]
It reached General Availability last week https://blogs.msdn.microsoft.com/azureservicefabric/2016/09/27/general-availability-of-service-fabric-standalone-installer-for-windows-server-and-public-preview-of-service-fabric-on-linux/

But they're really the same bits, there's no features different - the "On Premises" version includes some additional commands for setting up and manually managing a cluster, but that's it. In terms of multiple node types, support for the proxy, etc, those are all the same.

**Comment by qrli** [comment]
Verified on latest version. It works.

**Comment by masnider** [comment]
Great! Thanks for confirming!
