### ISSUE TITLE
Object pooling pattern to optimize for high throughput with reliable collections

### ISSUE THREAD

**Issue by juho-hanhimaki** [Azure/service-fabric-issues#414]
The guidance is to make reference types immutable.

However in some high throughput cases it would make sense to use object pooling pattern to reuse old unneeded objects.

When can the object be returned to the pool for later reuse? Is it safe to reuse the object after it has been removed from collection and the transaction has been committed?

See example:

            var myDictionary = await this.StateManager.GetOrAddAsync<IReliableDictionary<string, MyLargeObject>>("myDictionary");
            using (var tx = StateManager.CreateTransaction())
            {
                var newObject = ObjectPool.Instance.Rent<MyLargeObject>();
                newObject.Edit(values);

                MyLargeObject oldObject = null;

                await myDictionary.AddOrUpdateAsync(tx, "key", newObject,
                    (key, oldObj) =>
                    {
                        oldObject = oldObj;
                        return newObject;
                    });

                await tx.CommitAsync();

                if (oldObject != null)
                {
                    ObjectPool.Instance.Return(oldObject);
                }
            }

**Comment by preethasubbarayalu** [comment]
Sorry for the delay in my response. The example you have above will not work since we will checkpoint at some point in the background. Even though you have updated the value, we might still have the old value since we maintain multiple versions of the value to support snapshot reads. So mutating the value will affect correctness. There are customers who have asked for this feature. We are looking into exposing ways when you can safely mutate it.
