### ISSUE TITLE
Service Fabric SDK download link is broken in Chrome

### ISSUE THREAD

**Issue by erinknight242** [Azure/service-fabric-issues#425]
I am unable to download the SDK from this page using Chrome: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started

When I click either "Install the Microsoft Azure Service Fabric SDK" link, it redirects to login.live.com (blank screen), and then to https://www.microsoft.com/en-us/worldwide.aspx?f=255&MSPPError=-2147198344

When I try the same link in Firefox, it downloads the .exe properly.

Possibly I'm not logged in on Chrome, but it never loads a login page.

**Comment by masnider** [comment]
@erinknight242 I just tried this in chrome and was successful. Can you try it again? Looks like a transient thing with MS download center.

**Comment by erinknight242** [comment]
Strange; it still happened for me after exiting Chrome and starting a new session, but when I opened an incognito window, it worked there.

**Comment by erinknight242** [comment]
I have profiles set up and switched to a different Person, and it worked there. It still does not work for my main account, though.

**Comment by masnider** [comment]
It may be somehow logged in on Chrome with some weird live/msa id that's causing weird redirects?

**Comment by masnider** [comment]
Fire up fiddler :)

**Comment by erinknight242** [comment]
Yeah that looks like it; I went to login.live.com and signed out, and then the link worked. I signed back in and it worked still.

So, I don't have an answer for why, but that looks like it took care of it. Thanks!

**Comment by masnider** [comment]
No problem. Glad it was minor!

**Comment by navilwayne** [comment]
Trying to install Service fabric Tools & SDK  for VS2015, but getting error **This product did not install successfully: This product requires Service Fabric Runtime version 5.7.198.9494 to be installed**.

@MikkelHegn recommended me to put question here. Can  (@masnider)  you please help me to resolve issue. 
Downloading Set Up from below link
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started

Please Find Attached logs file
[webpi27.txt](https://github.com/Azure/service-fabric-issues/files/1280493/webpi27.txt)

**Comment by MikkelHegn** [comment]
@taxiatms

**Comment by FeodorFitsner** [comment]
@navilwayne I've got it installed after getting the same error.

* Download [full release notes for Azure Service Fabric SDk 2.7](https://servicefabricsdkstorage.blob.core.windows.net/public-release-notes/Microsoft%20Azure%20Service%20Fabric%20Release%20Notes%20-%20SDK%202.7.198%20-%20Runtime%205.7.198.docx)
* Scroll the document to the bottom - Section "Microsoft Download Center Links" contains download links for individual components.
* Download Runtime, open command prompt, go to download folder and run runtime installation with:

    MicrosoftServiceFabric.5.7.198.9494.exe /AcceptEULA

* Navigate to [Prepare your development environment](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started) and finish with standard installation link from that document.

Hope that helps.

**Comment by taxiatms** [comment]
@navilwayne The error from reading your log shows that your runtime installation has failed. You can try what @FeodorFitsner suggests, download the runtime directly and run with the command arguments "/AcceptEULA". Sorry the exe cannot be run directly because of the EULA agreement. 
If there is still anything wrong, you can post the error here and I'll reply as soon as I see the error output. 
Thanks.

**Comment by navilwayne** [comment]
@taxiatms @FeodorFitsner 

I followed above steps , i am getting below error after doing with admin rights:

08-09-2017 11:00:41 running: **Powershell.exe Get-ExecutionPolicy -Scope CurrentUser**
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.StartProcess(String processName, String commandLineArgs, Boolean redirectOutput)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TrySetPowershellExecutionPolicy()
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)

**Comment by taxiatms** [comment]
@navilwayne Installing Service Fabric needs to set powershell execution policy and of course running powershell scripts. The error is stating it can't find powershell.exe, or something wrong with powershell. I'm not familiar with this error. But any chance you have some change on the powershell.exe?

**Comment by navilwayne** [comment]
@taxiatms  No.

My power-shell running fine. No issue i found related to power-shell in my machine. 
Can anyone suggest here.

**Comment by taxiatms** [comment]
@navilwayne 
Is it possible you can try to execute "Powershell.exe Get-ExecutionPolicy -Scope CurrentUser" in a **cmd** window with admin rights and see if passes or prints out error message?

**Comment by navilwayne** [comment]
I already tried to execute above commands in : 
-CMD window "O/P : 'Powershell.exe' is not recognized as an internal or external command,
operable program or batch file. "
-  Powershell window command run - Get-ExecutionPolicy -Scope CurrentUser "O/P : Undefined",
But no luck :(

**Comment by taxiatms** [comment]
@navilwayne , I think the problem is because you can't start powershell.exe from a cmd window. You may be missing a environment variable. You can take a look at this post here https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr , or you can search for related topic to solve this issue.

**Comment by AdusumilliSridhar** [comment]
Getting below error while updating Service Fabric.

![capture](https://user-images.githubusercontent.com/24927123/33096634-92f5f6f6-cf6c-11e7-9f46-332b1ed1b14d.JPG)

**Comment by taxiatms** [comment]
@AdusumilliSridhar Can you paste the contents f the runtime installation log? THanks.

**Comment by AdusumilliSridhar** [comment]
Hi taxiatms,

PF below log file.

DownloadManager Information: 0 : Loading product xml from: https://go.microsoft.com/?linkid=9842185
DownloadManager Information: 0 : https://go.microsoft.com/?linkid=9842185 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Location: https://www.microsoft.com/web/webpi/5.0/webproductlist.xml
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content-Length: 175
Date: Wed, 22 Nov 2017 04:08:07 GMT
Connection: keep-alive


DownloadManager Information: 0 : https://www.microsoft.com/web/webpi/5.0/webproductlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
Content-Type: text/xml
Last-Modified: Tue, 14 Nov 2017 19:06:25 GMT
ETag: "1dde0aa7b5dd31:0"
Cache-Control: max-age=797
Date: Wed, 22 Nov 2017 04:08:08 GMT
Connection: keep-alive


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\1343597488.xml.temp
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Resource Provider
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Terawe
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webapplicationlist
DownloadManager Information: 0 : https://aka.ms/webapplicationlist responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Location: https://webgallery.microsoft.com/feed/webapplicationlist.xml
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content-Length: 177
Date: Wed, 22 Nov 2017 04:08:11 GMT
Connection: keep-alive


DownloadManager Information: 0 : https://webgallery.microsoft.com/feed/webapplicationlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
ETag: "05e987d561d31:0"
Date: Wed, 22 Nov 2017 04:08:15 GMT


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\-966730450.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webapplicationlist' after preprocessing, location on disk: 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-966730450.xml'
DownloadManager Information: 0 : Loading product xml from: https://www.microsoft.com/web/webpi/5.0/mediaproductlist.xml
DownloadManager Information: 0 : https://www.microsoft.com/web/webpi/5.0/mediaproductlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
Content-Type: text/xml
Last-Modified: Thu, 08 May 2014 18:42:31 GMT
ETag: "26a51545ed6acf1:0"
Cache-Control: max-age=833
Date: Wed, 22 Nov 2017 04:08:15 GMT
Connection: keep-alive


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\-230948881.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://www.microsoft.com/web/webpi/5.0/mediaproductlist.xml' after preprocessing, location on disk: 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-230948881.xml'
DownloadManager Information: 0 : Loading product xml from: https://www.microsoft.com/web/webpi/5.0/ToolsProductList.xml
DownloadManager Information: 0 : https://www.microsoft.com/web/webpi/5.0/ToolsProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
Content-Type: text/xml
Last-Modified: Wed, 09 Dec 2015 19:05:52 GMT
ETag: "9fc99b9fb432d11:0"
Cache-Control: max-age=499
Date: Wed, 22 Nov 2017 04:08:15 GMT
Connection: keep-alive


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\-1135381691.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://www.microsoft.com/web/webpi/5.0/ToolsProductList.xml' after preprocessing, location on disk: 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-1135381691.xml'
DownloadManager Information: 0 : Loading product xml from: https://www.microsoft.com/web/webpi/5.0/enterpriseproductlist.xml
DownloadManager Information: 0 : https://www.microsoft.com/web/webpi/5.0/enterpriseproductlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
Content-Type: text/xml
Last-Modified: Thu, 08 May 2014 18:42:32 GMT
ETag: "8285645ed6acf1:0"
Cache-Control: max-age=900
Date: Wed, 22 Nov 2017 04:08:16 GMT
Connection: keep-alive


DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\-1877981721.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://www.microsoft.com/web/webpi/5.0/enterpriseproductlist.xml' after preprocessing, location on disk: 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-1877981721.xml'
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://go.microsoft.com/?linkid=9842185' after preprocessing, location on disk: 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\preprocessor\1343597488.xml'
DownloadManager Information: 0 : Getting ratings file from http://go.microsoft.com/?linkid=9752395
DownloadManager Information: 0 : http://go.microsoft.com/?linkid=9752395 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Location: http://www.microsoft.com/web/handlers/WebPI.ashx?command=getatomfeedwithavgratingquery
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content-Length: 203
Date: Wed, 22 Nov 2017 04:08:16 GMT
Connection: keep-alive


DownloadManager Information: 0 : Content-Encoding header: 'gzip'
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '25190'
DownloadManager Information: 0 : Number of bytes after possible decompression: '82063'
DownloadManager Warning: 0 : Error getting last-modified header, error code: 12150
DownloadManager Warning: 0 : HttpQueryInfoWithRetry for HTTP_QUERY_LAST_MODIFIED failed.
DownloadManager Information: 0 : Ratings file loaded successfully
DownloadManager Information: 0 : Adding product Microsoft Azure Service Fabric SDK - 2.8.232 (MicrosoftAzure-ServiceFabric-CoreSDK) to cart
DownloadManager Information: 0 : Adding product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricSDK_2_8_CU2
DownloadManager Information: 0 : Setting current install to 1
DownloadManager Information: 0 : Starting install sequence
DownloadManager Information: 0 : Using cached file at C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_2_8_CU2\5EC84D34F57159D750A8AD41D517EA64A738DB3A\MicrosoftServiceFabricSDK.2.8.232.msi instead of downloading from https://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi
DownloadManager Information: 0 : Starting MSI install for msi 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_2_8_CU2\5EC84D34F57159D750A8AD41D517EA64A738DB3A\MicrosoftServiceFabricSDK.2.8.232.msi', commandline: 'STARTUPTYPE=disabled IACCEPTEULA=yes PRINCIPALUSER="Sridhar" PRINCIPALDOMAIN=NZADMIN ACTION=INSTALL REBOOT=ReallySuppress'
DownloadManager Information: 0 : MSI install return value for product 'Microsoft Azure Service Fabric SDK - 2.8.232' is '1603'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric SDK - 2.8.232' is Failure (Fatal error during installation.)
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 2.8.232 done install completed
DownloadManager Information: 0 : Increasing current install to 2
DownloadManager Information: 0 : Microsoft Azure Service Fabric SDK - 2.8.232 installation log: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\logs\install\2017-11-22T17.08.31\MicrosoftServiceFabricSDK.2.8.232.txt
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 2.8.232'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 2.8.232 had a dependency fail. Increasing install product to 3
DownloadManager Information: 0 : Product: ServiceFabricSDK_2_8_CU2, Install Status: InstallCompleted-Failure, Install Time: 00:00:03.6343103
DownloadManager Information: 0 : Product: MicrosoftAzure-ServiceFabric-CoreSDK, Install Status: DependencyFailed-None, Install Time: 00:00:00
DownloadManager Information: 0 : Clearing cart
DownloadManager Information: 0 : Adding product Microsoft Azure Service Fabric SDK - 2.8.232 (MicrosoftAzure-ServiceFabric-CoreSDK) to cart
DownloadManager Information: 0 : Adding product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricSDK_2_8_CU2
DownloadManager Information: 0 : Setting current install to 1
DownloadManager Information: 0 : Starting install sequence
DownloadManager Information: 0 : Using cached file at C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_2_8_CU2\5EC84D34F57159D750A8AD41D517EA64A738DB3A\MicrosoftServiceFabricSDK.2.8.232.msi instead of downloading from https://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi
DownloadManager Information: 0 : Starting MSI install for msi 'C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_2_8_CU2\5EC84D34F57159D750A8AD41D517EA64A738DB3A\MicrosoftServiceFabricSDK.2.8.232.msi', commandline: 'STARTUPTYPE=disabled IACCEPTEULA=yes PRINCIPALUSER="Sridhar" PRINCIPALDOMAIN=NZADMIN ACTION=INSTALL REBOOT=ReallySuppress'
DownloadManager Information: 0 : MSI install return value for product 'Microsoft Azure Service Fabric SDK - 2.8.232' is '1603'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric SDK - 2.8.232' is Failure (Fatal error during installation.)
DownloadManager Information: 0 : Microsoft Azure Service Fabric SDK - 2.8.232 installation log: C:\Users\Sridhar\AppData\Local\Microsoft\Web Platform Installer\logs\install\2017-11-22T17.27.12\MicrosoftServiceFabricSDK.2.8.232.txt
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 2.8.232'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 2.8.232 done install completed
DownloadManager Information: 0 : Increasing current install to 2
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 2.8.232 had a dependency fail. Increasing install product to 3
DownloadManager Information: 0 : Product: ServiceFabricSDK_2_8_CU2, Install Status: InstallCompleted-Failure, Install Time: 00:00:05.6628112
DownloadManager Information: 0 : Product: MicrosoftAzure-ServiceFabric-CoreSDK, Install Status: DependencyFailed-None, Install Time: 00:00:00

**Comment by AdusumilliSridhar** [comment]
Hi, The issue has been resolved. It was because of local admin rights. Our system Admin ran the exe using his credentials and it worked. Hope this would help someone. Cheers.
