### ISSUE TITLE
Issue publishing updated version of service - FABRIC_E_FILE_NOT_FOUND: File not found

### ISSUE THREAD

**Issue by DenisPitcher** [Azure/service-fabric-issues#426]
I had my service fabric up and running with a couple services.  I then tried renaming a service to a different type and name so that it was more compatible for use with the reverse proxy.

On attempting to publish a new version of my service from visual studio I encounter the following error

2>New-ServiceFabricApplication : Operation timed out.
2>At C:\Program Files\Microsoft SDKs\Service 
2>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:286 char:9

When checking the service fabric explorer, my application type page shows a status of failed and the following message is presented:
FABRIC_E_FILE_NOT_FOUND: File not found --> COMException: Exception from HRESULT: 0x80071C00

Deploying locally works perfectly ok.  I've tried deploying a another separate service I've never deployed to this SF instance before and have encountered the same issue.

I've tried unprovisioning and deleting the application and that didn't help.  How else can I figure out what file is missing and how to resolve this issue?

**Comment by navyahmed** [comment]
Hi Denis,
can you please provide specific steps you took to rename the package?

**Comment by DenisPitcher** [comment]
Hello,

Apologies for the delay in following up on this.   Unfortunately it has been a while so I can't recall the exact steps.

I think I renamed the application and project files in visual studio by right clicking on them and clicking rename.  I adjusted the assembly and namespaces in the properties window.  Then I adjusted the name in the various config files.

I tried renaming everything back the way it was but that didn't work.  It would be helpful to have more detail presented in the error message so that I would at least know what file is not being found.

**Comment by oanapl** [comment]
@DenisPitcher, looks like registering the application type didn't succeed because of a missing file. Can you check your application package and see that it has all files - manifests, code/config/data packages?
You can run [Test-ServiceFabricApplicationPackage](https://docs.microsoft.com/en-us/powershell/module/servicefabric/test-servicefabricapplicationpackage?view=azureservicefabricps). You can use the target cluster to verify against existing versions (if any).

If deploying locally works, it may be that a file is not copied in the package folder. Maybe a static file or a reference that is present locally so local deployment works.

You mentioned that the problem persists even if you retry the steps. Did you unprovision the type (which should make it go away from the list of application types), remove previous copied package, then tried the script again?

**Comment by oanapl** [comment]
There hasn't been a response for a while. I am closing the issue. Please re-open if needed.
