### ISSUE TITLE
NotifyDictionaryItemUpdatedEventArgs does not include pre change value

### ISSUE THREAD

**Issue by bklooste** [Azure/service-fabric-issues#432]
We have an in memory index , however when the collection changes we don't have the original value so the only way we can update the index is via a brute force key scan to remove and read the item.

**Comment by mcoskun** [comment]
I assume you are using Reliable Collections and Reliable Collection notifications to keep your in-memory secondary index up to date.

As you noted, Reliable Collection notifications do not contain the previous TValue because of two reasons: 
- Previous notification on the key has already provided the relevant old TValue
- Providing the old TValue may require disk IO since it may have been sweeped out of memory.

If you need the old value, we recommend keeping it when you receive the notification.

For future, we are considering adding new notifications that will provide the old TValue. This way, customers who are willing to incur additional IO in their write paths, can use this API.

**Comment by bklooste** [comment]
@mcoskun  "If you need the old value, we recommend keeping it when you receive the notification."  . 

For an index that's the same as saying keep the whole reliable collection in memory  ...or immutable data and versioning the collection which is a LOT more IO.

Looking forward to those changes  under consideration, Is there something eg a milestone I can track this on  ?
