### ISSUE TITLE
Certificate No Longer Working For Cluster Authentication

### ISSUE THREAD

**Issue by awcab** [Azure/service-fabric-issues#433]
I have a certificate that expires in May 2018 that I used to create my cluster.  It has been working fine since this past May.  However, it suddenly stopped working last week for no apparent reason.  I can no longer deploy or access the cluster with that certificate.  I've checked it several ways and it does not appear to be revoked or invalidated. I've tried both from VS and powershell with the same results.

The cloud explorer in VS gives this error:

> Cloud Explorer could not connect to cluster 'my-cluster':
> An error occurred while sending the request.
> The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

In VSTS I get this:

> FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

Changing to the secondary certificate appears to be working for now.  I'm concerned that there is no indication as to why this has stopped working or how to fix it apart from just getting a new certificate each time.

**Comment by Liphi** [comment]
The best practice is to start cert roll over before certs expire. And a health warning has been implemented in recent service fabric versions to automatically detect and remind before certs expire.

**Comment by awcab** [comment]
Hey @Liphi  did you notice my first sentence where the certificate doesn't expire until May of next year?  Is it typical to close issues in this manner?

cc: @masnider

**Comment by Liphi** [comment]
Ah, overlooked that. So, ur cluster is on Azure, right? Cert expiration may not be the only reason to cause cert loading failure. Maybe the cert is somehow not installed or ACLed correctly when VM gets recreated and nodes get moved. Could u upgrade ur cluster to the latest Service Fabric version? In recent versions we've implemented detection and health warning for cert loading failure.

**Comment by awcab** [comment]
Hi @Liphi , as I mentioned, this has been functioning well for months, so I believe it to be installed correctly.  It is installed the same way as the secondary certificate that is now working.  The cluster is on the latest version.  I am not getting any health warnings.

**Comment by Liphi** [comment]
Since the deployment is on Azure, Azure may move nodes to other VMs if it needs, which is transparent to user. Usually such move should correctly install/ ACL the certs. For us to further diagnose, trace logs are needed, and I can check with the guy implementing the health warnings to see why ur case is not covered.

**Comment by awcab** [comment]
Ok - lmk if the logs would be helpful and from where I can pull them.

**Comment by Liphi** [comment]
One more question... u mentioned that after the issue happened u 'switched' to the secondary cert. I assume this 'switch' happened on the client side, not cluster side? If so, may I know when that secondary cert is added to the cluster config, before or after the issue happened? And is its expiration date before or after the primary cert?

**Comment by awcab** [comment]
That's correct, I just changed to the secondary cert on the client side.  The secondary cert was added before the issue happened and at the same time the cluster was created, just like the primary cert.  They both expire in May 2018.

**Comment by Liphi** [comment]
Which cert expires later?

**Comment by awcab** [comment]
The secondary expires 2 days after the primary.

**Comment by leikong** [comment]
This is the default behavior now, primary and secondary are both checked, whichever has a later expiration will be used on the server side. This change is done so that you don't need to explicitly swap primary and secondary during certificate rollover.

During the time period a newer secondary is added, cluster nodes may be using primary or secondary, on the client side, you can specify both the primary and secondary in "-ServerCertThumbprint" (this is an array), so that either one is accepted by the client.

The other option is to revert back to the old behavior of preferring primary, please add the following to fabricSettings:

{
        "name": "Security",
        "parameters": [
          {
            "name": "UseSecondaryIfNewer",
            "value": "false"
          }
        ]
      }
