### ISSUE TITLE
ParseServiceManifest and CreateFileW failed event log warnings

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#441]
What does these two event log warnings mean:

Event ID: 257
CreateFileW failed: file=\\?\D:\SvcFab\_BackEnd_0\Fabric\work\ImageCache\Store\[NAMESPACE]\[Service]Pkg.Manifest.1.35.1709041.xml error=2

Event ID: 28161
ParseServiceManifest: ErrorCode=E_FAIL, FileName=D:\\SvcFab\_BackEnd_0\Fabric\work\ImageCache\Store\[NAMESPACE]\[Service]Pkg.Manifest.1.35.1709041.xml

Seeing those in the "Microsoft-Service-Fabric" logs in all clusters, both on Azure and locally.

**Comment by lumiao** [comment]
The Event ID 28161 indicates that the parsing service manifest file was failed during activation. Since the service manifest file was already validated during the provision; It's most likely that the file was corrupted somehow during downloading from the image store. Hosting will retry it. 

The Event ID 257 generally indicates opening file failed. I'm not quite sure about the error 2; it probably means "path not found"; In most cases, it's retry-able in the upper level. 

If there's any issue, It should be reflected in the component level trace.

**Comment by tugup** [comment]
This is fixed as part of release 6.2.
