### ISSUE TITLE
Error deploying with Deploy Service Fabric Application task using Update Service Fabric App Versions

### ISSUE THREAD

**Issue by jricke** [Azure/service-fabric-issues#444]
Similar issue that was closed with no resolution:
https://github.com/Azure/service-fabric-issues/issues/214

When trying to deploy a service fabric application built with the Update Service Fabric App Versions task and the Update only when changed flag set, the following error occurs:

The content in CodePackage Name:Code and Version:0.1.20170829.4 in Service Manifest 'Sem.ServiceFabric.ChromePkg' has changed, but the version number is the same.

Screen shot of the diff from the last version to the current version:

![image](https://user-images.githubusercontent.com/11906948/30180993-68d3dd28-93d7-11e7-829e-23b38d51bb05.png)

Screen shot of build that removes pdb's which are not deterministic:

![image](https://user-images.githubusercontent.com/11906948/30181050-9cf3f818-93d7-11e7-83d8-079af7a810c1.png)

Screen shot of release process:

![image](https://user-images.githubusercontent.com/11906948/30181129-dcae4760-93d7-11e7-87d9-e4461667eaa2.png)

Any help is appreciated.
Jason

**Comment by ConX-Ryan** [comment]
In the Update Service Fabric App Versions Tasks try untick the "Update only if changed option"

**Comment by jricke** [comment]
I'd to only update services that changed instead of the entire application. Is that possible with the Update only if changed option?

**Comment by MikkelHegn** [comment]
@ConX-Ryan @jricke The "Update only if changed" option can be used to only update the version if the packages are not identical - https://github.com/Microsoft/vsts-tasks/blob/1c95a5203fa62a5c1471dae09dd0566f0a2d96ce/Tasks/ServiceFabricUpdateManifests/Update-ApplicationVersions.psm1#L34 - If this is ticked all versions will be updated without comparing the content of the packages.

As I understand this issue, the packages are identical and therefore the version not changed by the task. However, the cluster concludes otherwise when the package is being deployed.

@oanapl - I see package compression is enabled could that be a factor?

**Comment by jricke** [comment]
@MikkelHegn Thanks for your response. You are correct in your understanding.

**Comment by oanapl** [comment]
@MikkelHegn , I don't know how VSTS determines whether it needs to generate new version for compressed application packages. The script you pointed to doesn't have specific compression code.
One thing to take care with compression - changing the last modified timestamp of a compressed package contents results in changing the package checksum.

**Comment by MikkelHegn** [comment]
It seems the problem is that the check happens at build (where nothing has change and therefore the version does not change), but when you compress the package (at deployment time), the checksum of the compressed package is now different because of the timestamp change.

On top of my head I have no good solution to this (other than turn off compressed packages as a workaround for now).

This should be solved as part of the VSTS tasks / usage, hence opening an issue here for this: https://github.com/Microsoft/vsts-tasks/issues/5537

**Comment by jricke** [comment]
Thanks @MikkelHegn, it seems to be working without compression.

If you could look at https://github.com/Microsoft/vsts-tasks/pull/5287 it would help speed up the build process when there are multiple applications being built in the same build template.

Closing this issue since the workaround appears to be working.
