### ISSUE TITLE
copying files to cluster with ImageStoreConnectionString fabric:ImageStore, files are not showing up in image store and application type not being provisioned

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Azure/service-fabric-issues#464]
I am trying to figure out what could cause this? I had it working yesterday where the files were being added to the image store, and for some reason when it was working there was no entry for ImageStoreService in the service fabric explorer. 

Today I booted up my pc, and noticed after using sfctl to copy files to the image store (verified I am getting 200's from the api PUT requests with --debug flag of sfctl) that the files are not there. Then when I take next step to provision, the application type does not exists. Also all of the sudden ImageStoreService is in my service fabric explorer. 

Any ideas how all of this is related and resulting in no files being dropped in the image store? What steps could I take to find out more about what is happening in the api?

**Comment by PTC-JoshuaMatthews** [comment]
Also noticed the following error in my event log, sounds like it could be related 

GetSequenceStreamProgress failed with FABRIC_E_NO_WRITE_QORUM

**Comment by PTC-JoshuaMatthews** [comment]
Finally found the store files, I though they should be in c:\SfDevCluster\Data\ImageStoreShare, but actually now the package is for some reason sitting on node 1 c:\SfDevCluster\Data\_App\_Node_1\__FabricSystem_App4294967295\work\Store\131503957881915015

**Comment by oanapl** [comment]
Can you paste the commands you ran?

"GetSequenceStreamProgress failed with FABRIC_E_NO_WRITE_QORUM" - this indicates that the ClusterManager system service is reconfiguring. When this occurred, did you happen to look at the health of the cluster? It's possible the ImageStoreService had the same issue (not enough replicas) and couldn't copy the package.

Is the cluster healthy now? If so, have you retried the provision operation?
And before retry, can you make sure you remove any previously uploaded packages?

**Comment by PTC-JoshuaMatthews** [comment]
At some point it started working. I think I needed to enable the image store service in the cluster template, by default it was false. Once I did that it started working, although images are stored on the nodes instead of ImageStoreShare

**Comment by oanapl** [comment]
@PTC-JoshuaMatthews, I am not sure what configurations you used, but image store service must be enabled for testing these scenarios.

Here's how flow should look like:
- When you copy the application package, it will appear in ImageStoreShare folder.
- When you register the type in that application package, it will also appear in Store folder.
- When you create services, the application package will be copied on nodes as needed. For example, if a service of a service type contained in your application type is placed on _Node_1, you will see a folder for the expanded package in _Apps\_Node_1.
- When you remove application package, it will disappear from ImageStoreShare folder.

In your case, since you don't see it in ImageStoreShare folder, you could have removed the package.
Since I am not clear on what steps you took to enable the image store service, it can also be possible that one of those steps made it disappear.

**Comment by oanapl** [comment]
@PTC-JoshuaMatthews, we haven't heard back from you. Looks like you are unblocked. I will close this issue, please reopen if that's not the case.
