### ISSUE TITLE
Services do not start with custom ReliableStateManagerReplicatorSettings.

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#471]
We are initiating state in stateful services, by letting them download data from blob storage.
This results in hitting the secondary replication queue operation size, which makes at least one secondary replica stay InBuild and never recovering (you would assume it should eventually recover). Anyway, it drops messages when queue is full as I've understood, so we cannot let it fill regardless.

Locally this is working fine with same amount of data, so, it's the cloud VMs that are not able to handle that load. So, we have the options of trying to slow down the data transfer from blob into the stateful services, or change the replicator settings. 

We prefer the latter, but when trying to start services with custom ReliableStateManagerReplicatorSettings, the secondary replicas simply won't get past InBuild status. I.e. they never start.

Is there anything wrong with these settings?

```
ServiceRuntime.RegisterServiceAsync("ProjectionsType",
                    context => new Projections(context,
                        new ReliableStateManager(context,
                            new ReliableStateManagerConfiguration(
                                new ReliableStateManagerReplicatorSettings()
                                {
                                    BatchAcknowledgementInterval = TimeSpan.FromMilliseconds(100),
                                    MaxSecondaryReplicationQueueSize = 65536,
                                    MaxReplicationMessageSize = 1073741824
                                })))).GetAwaiter().GetResult();
```

We did try only increasing queue size, but wasn't able to get the services to start then either.

When not using custom settings services do start without problem, so we can be fairly certain the problem is related to the above code snippet.

**Comment by sumukhs** [comment]
Hi @zeodamian ,
When setting custom reliable state manager replicator settings in the code, you must also specify the "ReplicatorAddress" configuration as it is needed for the Idle replicas to talk to the primary replica.

The replicator address is a string in the format - "IP:Port".
The IP address of the current node can be obtained from the ServiceContext that is provided. The port number can be obtained from the code package activation context that retrieves the port resource defined in the service manifest.

A simpler approach rather than going through the above workflow is to instead specify the settings you want to modify in the "settings.xml" file as a bunch of key value pairs in the config package of the service and remove the above code that overrides the values.

Can you give this a try and see if it works for you? The name of the configs to specify in the settings.xml and its units are defined in this URL:

[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration](url)

**Comment by zeodamian** [comment]
Thanks a lot for the reply. Yes, the settings.xml approach works absolutely fine.
