### ISSUE TITLE
Seems to have crashed on my Windows 10 x64

### ISSUE THREAD

**Issue by TonyHenrique** [Azure/service-fabric-issues#475]
OK, I am new to this, but on my first clicks, something appear to have crashed.

I did not even put any of my service on it, 
I just installed it, then entered on this url

http://localhost:19080/Explorer/index.html#/node/_Node_0

then clicked
Deactivate (Pause),
Deactivate (Restart),
Restart

in sequence, quickly.

See logs: 
Traces.zip
https://drive.google.com/open?id=0B5d9oJc6UeFKYTdheUpqUlY5d2s

**Comment by msingiresu** [comment]
@TonyHenrique  Thank you for posting the question and providing the traces.

I looked at the traces and looks like there was only one node in the cluster which was attempted to be deactivated. Since this node is also seed node (used for bootstrapping other nodes to join cluster) FailoverManager component blocked this deactivate request.

To know more about deactivate (pause/restart) you can refer to this post
https://stackoverflow.com/questions/34308701/service-fabric-deactivate-pause-vs-deactivate-restart

Can you describe more details of what crashed?

**Comment by msingiresu** [comment]
hey didn't hear back from you. If you or anyone else is still experiencing this issue, then please reopen this issue or create a new one.
