### ISSUE TITLE
All projects referencing WorkflowService.csproj must install nuget package Microsoft.Bcl.Build.

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/service-fabric-issues#49]
Anyone else getting this error when building their .sfproj? This is all with the latest SF nuget packages and SDK installed. Seems innocuous, but curious why this is occurring?

2>E:\Projects\Candela Onboarding PaaS\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing WorkflowService.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.

**Comment by johnkattenhorn** [comment]
Yep, we get this all the time, sometime we also get this

```NuGet Package restore failed for project 0. Common\MKopa.M2M.ServiceFabric: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process.```

It only started recently though

**Comment by ravipal** [comment]
All projects referencing WorkflowService.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.

The above issue happens in 5.1 too. So this is not new in 5.2.

**Comment by ravipal** [comment]
NuGet package installation supposed to import the following to the application project. Please manually add the following (with appropriate path) to the *.sfproj and see if that fixes the issue.

  <Import Project="..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets')" />

**Comment by csdahlberg** [comment]
My team has been seeing these errors in the build output since the `Microsoft.Bcl.Build` package was introduced as a dependency in our solution.

Manually adding that Import to the `.sfproj` files avoided the original warnings, but resulted in several new warnings about needing assembly binding redirects. I was able to manually add an `App.config` file with those assembly binding redirects, but both of those changes are very fragile and will likely be broken every time we update any of the relevant NuGet packages..

Hopefully there will be a better way to avoid those errors.

**Comment by mthalman-msft** [comment]
This warning is coming from the Microsoft.Bcl.Build.targets file.  In that file, it has a description of the validation being done here:

>This target validates that any Nuget packages installed in the current project are also installed in projects referencing the current project.    
>This is necessary because Nuget packages contain more than just simple references.  Installing the package ensures
&nbsp;&nbsp;1. The right set of references for the target framework are added
&nbsp;&nbsp;2. Config file transforms are applied
&nbsp;&nbsp;3. Project installation scripts are run
       
>For all packages listed as installed for the current project in packages config, if the package ID matches one specified in @(ValidatePackages), ensure that the same package is installed in the referencing project. 
    
>This target can be disabled for a project reference by setting SkipValidatePackageReferences=true for the reference:
&nbsp;&nbsp;&lt;ProjectReference Include="..\pcl\pcl.csproj"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;Project&gt;{664a9e98-fac7-4567-a046-0dde95fddb48}&lt;/Project&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;Name&gt;pcl&lt;/Name&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;Properties&gt;SkipValidatePackageReferences=true&lt;/Properties&gt;
&nbsp;&nbsp;&lt;/ProjectReference&gt;
    
>This target can be disabled for all references to a project by adding the following:
&nbsp;&nbsp;&lt;PropertyGroup&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;SkipValidatePackageReferences&gt;true&lt;/SkipValidatePackageReferences&gt;
&nbsp;&nbsp;&lt;/PropertyGroup&gt;

In the case of Service Fabric, there's no need to have this NuGet package configured for the Application project itself since it's just a container/deployment project.  So I think the proper way to handle this is to to go with the first option by setting SkipValidatePackageReferences on the project reference in your .sfproj file.

**Comment by MikkelHegn** [comment]
Thanks Matt,

Is this something we can incorporate in our template – or is there no problem in a default setup?

--
Mikkel

**Comment by mthalman-msft** [comment]
This would not happen in our shipped templates by default.  It only occurs if the Microsoft.Bcl.Build package is added to a service project.  This is specific to the usage of BCL and they provide a mechanism to handle this.  So I don't think any change is necessary in Service Fabric tooling.

**Comment by BrainSlugs83** [comment]
This absolutely happens in the current sfproj template. -- As soon as ANY service (i.e. csproj) references Microsoft.Bcl.Build (which lots of Azure stuff pulls in as a dependency), you will see this message on the sfproject as well.

The posted workarounds do not work.  (i.e. `SkipValidatePackageReferences` is completely ignored in either location.)
