### ISSUE TITLE
 Deploy SF App VSTS task with same version skip upgrade

### ISSUE THREAD

**Issue by makar-sasha** [Azure/service-fabric-issues#548]
Hello

maybe somebody could answer me:
when I deploy from VSTS task with checked "Skip upgrade for same Type and Version" I always get error `The content in CodePackage Name:Code and Version:1.0.44.05 in Service Manifest 'BrandApiPkg' has changed, but the version number is the same.`
Is it correct that this problem service with existed version on cloud should be skipped without error?  

Thank you!

**Comment by oanapl** [comment]
There is a known issue when using compressed packages. Can you confirm that you are using compression?
See https://github.com/Azure/service-fabric-issues/issues/444 for more info.

**Comment by makar-sasha** [comment]
yes, compression is enabled. will disable and test. 
Thanks!

**Comment by makar-sasha** [comment]
unfortunately the same error. 
I have deployed fresh app with no compression and have tried to update 1 of the services. my settings [https://i.snag.gy/xINt0b.jpg](url) 
should I try to reproduce on small and simple example?

Thanks,
Alex

**Comment by oanapl** [comment]
@dbreshears, can you help with VSTS settings?

**Comment by dbreshears** [comment]
@makar-sasha ,  maybe a simple example would help,  a few questions,   

Are you updating the  application version along with the service? , I can't tell by the error message which version this is referring too. 

Or, are you using our Update Service Fabric Manifests task as part of your build definition with "Update only if changed" option and then using  /p:Deterministic=true flag when building?

**Comment by makar-sasha** [comment]
hello
@dbreshears could you please check this info

1. I have added new SF app with 2 default stateless services (latest sdk). Everything with ver 1.0
2. VSTS _build with Visual Studio_ Build task to create SF package
3. VSTS _Deploy Service Fabric Application_ without advanced settings (so no compression)

Everything was deployed successfully. After this I have updated cluster version and one of services to version 2.0. So I want to update only this stuff. To achieve this I checked:

- Skip upgrade for same Type and Version
- Skip package validation
- Overide All Publish Profile Upgrade Settings
- Upgrade the Application

As a result service with not updated version prevents app upgrade with `The content in ConfigPackage Name:Config and Version:1.0 in Service Manifest 'Stateless1Pkg' has changed, but the version number is the same`

Am I using the deployment task correctly? Also I'm not using Upgrade Versions task as I need to manage versions manually.

**Comment by dbreshears** [comment]
So the option you are selecting  "Skip Upgrade for same Type and Version" is not the option you need.  This option will basically ignore an upgrade if the Application type name and the Version are the same.    You are changing the app version and one of the service versions and code intentionally so that doesn't apply, but the other service that you are not updating appears to be different according to the cluster.  This is what seems to be going on from what I can tell.   

This could be the result of a PDB file or not using deterministic build.   Did you create the Build Definition from our Azure Service Fabric Application template?  This by default will use deterministic build and delete the PDB files from the package.   Here is a screen shot

![image](https://user-images.githubusercontent.com/3432571/31797521-84fafbd0-b4e3-11e7-8cb3-2c7bf5429528.png)

**Comment by makar-sasha** [comment]
@dbreshears , thanks for your comment and time. But it is still not obvious for me.
I have added the default template + default Service Fabric Application Deployment task (and use default SF app).

- When I run first time it install the app.
- When I run it just for testing again with "**Upgrade the Application**" checked
-- "**Update Service Fabric Manifests**" task says "**Found no changes**"
-- but "**Service Fabric Application Deployment**" task results in `The content in CodePackage Name:Code and Version:1.0.0.20171020.1 in Service Manifest 'Stateless1Pkg' has changed, but the version number is the same.`

If I update one of the services
- "**Update Service Fabric Manifests**" task correctly update version for modified service
- "**Service Fabric Application Deployment**" task has the same error for not modified service `The content in CodePackage Name:Code and Version:1.0.0.20171020.1 in Service Manifest 'Stateless2Pkg' has changed, but the version number is the same.`

Is it by design?
Thanks again for your help.

**Comment by dbreshears** [comment]
@makar-sasha   Can you export your build and release definitions as json, zip them up and attach them here please.

**Comment by makar-sasha** [comment]
Of course @dbreshears 
I also have attached the solution (but it is default VS 2017 starter SF template)

Thanks, Alex

[Keystone-Azure Service Fabric Application-CI.zip](https://github.com/Azure/service-fabric-issues/files/1409896/Keystone-Azure.Service.Fabric.Application-CI.zip)
[deployetest.zip](https://github.com/Azure/service-fabric-issues/files/1409899/deployetest.zip)

**Comment by dbreshears** [comment]
@makar-sasha ,   I found the issue,   the Cloud.xml Publlsh Profile specifies the "CompressPackage = true" which is getting used even though it is unchecked in the task because we honor the settings in the publish profile (accept for upgrade settings which is being overridden).   You will need to set to false for now in the publish profile referenced by the task until we get the bug fixed.

**Comment by makar-sasha** [comment]
@dbreshears @oanapl thank you so much!
