### ISSUE TITLE
TargetReplicaSetSize and MinReplicaSetSize on stateful services documentation

### ISSUE THREAD

**Issue by juho-hanhimaki** [Azure/service-fabric-issues#562]
I find it difficult to find information about the TargetReplicasetSize and MinReplicaSetSize.

A lot of examples use for example TargetReplicaSetSize=5 and MinReplicaSetSize=3.

As per documentation (https://msdn.microsoft.com/en-us/library/system.fabric.description.statefulservicedescription.minreplicasetsize.aspx) the above scenario would support 3 simultaneous failures and still maintain quorum and write capability.

Is it true that going for TargetReplicaSetSize=4 and MinReplicaSetSize=3 would instead support 2 simultaneous failures while maintaining quorum?

Is it totally okay to have TargetReplicaSetSize (or MinReplicaSetSize) that is even number? Are there any downsides to having even number TargetReplicaSetSize?

**Comment by MikkelHegn** [comment]
@masnider

**Comment by masnider** [comment]
When target is 5 you can support at most 2 simultaneous failures and keep your original quorum of 3. In general I would just keep Min = Target since it makes it easier to reason about what is going on.

Minimum reliability is actually determined as Quorum(MinReplicaSetSize), so if you did have things set to 5/3, then you could suffer up to 3 total failures, since SF would downshift to 3 replicas, with a quorum of 2, of which 2 are still up. However, this isn't really that safe :)

4/3 Still only supports 2 failures (vs. 5/3, which supports 3, since you have that additional replica).

Even numbers don't specifically matter except that figuring out quorum can be harder :)

Hope this all helped and sorry for the late reply.

**Comment by juho-hanhimaki** [comment]
`Even numbers don't specifically matter except that figuring out quorum can be harder :)`

In what sense figuring out the quorum can be harder? Is there performance difference?

Let's say I am perfectly happy with supporting only two simultaneous failures and run my services at 4/3. Is there any performance penalty compared to running 5/3 (odd number of replicas in normal cluster health state).
