### ISSUE TITLE
DNS service and DNS suffixes

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#565]
When a computer has DNS suffixes defined (e.g. on domain-joined machines), the Fabric DNS service doesn't resolve addresses unless you specify the suffix in the `ServiceDnsName`. Is this behavior by design?

For example, if the suffix is `.corp.com`, **registering** a service with the DNS name `myservice` wouldn't work:

    > ping myservice
    Ping request could not find host myservice

Whereas `myservice.corp.com` would work.

**Comment by MikkelHegn** [comment]
@mani-ramaswamy

**Comment by milvuko** [comment]
Hi @aelij, 
appending the DNS suffixes to the unqualified name is done by the client, in this case ping. Behind the scenes, ping attaches a suffix from the DNS suffix list before sending the query to the DNS server.
Based on your post, the suffixes are not appended to the unqualified name. You should check the DNS suffix list on you machine/container and if appending of DNS suffixes is enabled.

Thanks

**Comment by mani-ramaswamy** [comment]
Some links to help move things along, but meanwhile closing the issue since there doesn't seem to be any action needed from SF on this. If you feel there is some action needed from us, please reopen this issue. 

https://social.technet.microsoft.com/Forums/en-US/b1d1d329-fe9f-447d-b069-41bb0320b16b/what-is-the-primary-dns-suffix-and-where-do-i-find-it-please?forum=win10itprogeneral

https://serverfault.com/questions/213523/how-do-i-get-a-linux-terminal-to-show-me-the-dns-domain-suffix-of-a-machine

https://www.linuxquestions.org/questions/slackware-14/append-dns-suffix-in-linux-604678/

**Comment by aelij** [comment]
@milvuko  @mani-ramaswamy 

The question is not about DNS suffixes in general, but how the Fabric handles a situation where suffixes are added (specifically on a Windows Server joined to an AD domain). I'll try to explain again:

```powershell
New-ServiceFabricService ... -SeviceDnsName myservice

ping myservice
Ping request could not find host myservice

New-ServiceFabricService ... -SeviceDnsName myservice.corp.com

ping myservice
Pinging myservice [10.0.0.1] ...
```

So my question is - should I always add `.corp.com` when using the Fabric DNS on a domain network, or is this something you can fix somehow?

**Comment by milvuko** [comment]
Recommendation is to use FQDNs. DNS clients usually consider domain name that contains a dot as being fully qualified. Note that ServiceFabric allows hostnames (single label) to be specified as ServiceDnsName. However, most clients will append DNS suffix to the hostname before sending out the query to the DNS server **and will never send the raw hostname**. Ping behaves like that. Adding a trailing dot to the hostname converts the hostname into the FQDN, the following query will work:
`ping myservice.`
