### ISSUE TITLE
ApplicationParameters/Cloud.xml over written on Build

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#572]
Hi,

I am using VS2017 15.4.1
SF SDK  2.8.219

I am getting my cloud.xml file nuked on build event or when the solution is opened in visual studio, am I missing something or is this an issue?

---UPDATE 
It appears that the publish profile wizard has something to do with this, If i copy a *.xml file through here it seems to have stopped. previously i had copied the file thru solution explorer

**Comment by masnider** [comment]
@ConX-Ryan I've added some folks to help take a look. But if you could provide a repro in a gist or somewhere and the exact steps you're following, that'd be great.

**Comment by dbreshears** [comment]
@ConX-Ryan ,   I took a quick look at copying in Solution Explorer as well as in publish dialog but haven't hit anything.   A long, long time ago we had an weird copy issue going on with the profiles / parameters.    Definitely would be helpful to get a list of repro steps to investigate further to see if something  we need to fix.

**Comment by ConX-Ryan** [comment]
Ill work on defining better steps to reproduce 
thanks team

**Comment by ConX-Ryan** [comment]
I have been unable to determine steps to reproduce this issue but i can say it still exists intermittently.
I have altered the standard application parameter files, and/or added additional files any can be effected.

What i have noted is that once the symptom exists it will (66% of the time) be resolved by saving the profile with the publish profile wizard, also I note that most (not all) of the time it will overwrite the last file i edited (sometimes 2 edited files are overwritten).

This occurrence is not limited to one solution, multiple solutions have this symptom.

Sorry I cant be more explicit at this time i will continue to try and get definitive steps.

**Comment by dbreshears** [comment]
There is a utility (AppManifestCleanupUtil.exe) in SDK tools folder that runs as part of build to keep the manifest / parameters file in-sync.  It will cleanup unused service manifest references as well as unused  parameter values from the app manifest and parameters files.     This may be what you are hitting.     To avoid auto-updating of manifests you can add this to the .sfproj file
 <UpdateServiceFabricApplicationManifestEnabled>false</UpdateServiceFabricApplicationManifestEnabled

More info is in #53

**Comment by ConX-Ryan** [comment]
I think i spotted the trigger here. its like dbreshears said

When my application manifest has got an empty <ConfigOverrides/> tag it will nuke all settings files on Build or Solution open

**Comment by MikkelHegn** [comment]
@dbreshears @amanbha Do we have this logged against the AppManifestCleanupUtil.exe?

**Comment by amanbha** [comment]
Parameter values specified in Local1.Node.xml or Cloud.xml are used for overriding parameters defined in ApplicationManifest when you deploy the application. If the parameter is not defined in the ApplicationManifest, its removed. For its value to be preserved in the xmls, It must be defined in ApplicationManifest’s parameters section.

**Comment by ConX-Ryan** [comment]
Personally I'd rather the error at runtime over a tool nuking my file changes.

**Comment by amanbha** [comment]
@ConX-Ryan I understand your preference to error at runtime, but there was lot of feedback in the past with deployment failing because of exact same reason and this feature was added.to avoid all those errors. So I am sorry this request will not be taken. Also you will have to remove those params anyhow when your deployment will fail.

**Comment by mikanyg** [comment]
Couldn't it be a MSBuild property for the .sfproj to indicate whether to fail during build/publish due to messed up config or manifest or to nuke it? I have been bidden by this behaviour several times, and would prefer to have a build/publish error rather than nuking the manifest sections and parameter files.

**Comment by amanbha** [comment]
@mikanyg Makes sense, I will wait for @dbreshears response to see if there is a way to disable running of AppManifestClenupUtil as that should handle your scenarios, If there is no such way then we can look into adding a MSBuild property which will make AppManifestUtil to fail if there are extra params in parameter files if extra params are found.

**Comment by dbreshears** [comment]
@amanbha , yes the UpdateServiceFabricApplicationManifestEnabled property set to true in the .sfproj will avoid running the AppManifestCleanupUtil as well.

**Comment by dbreshears** [comment]
@mikanyg, edited my previous comment, the property needs to be set to "false" and we will not touch the manifests during build with either fabactutil.exe or AppManifestCleanupUtil.exe

**Comment by mikanyg** [comment]
@dbreshears but will it result in build or package error when set to false? Or will it result in runtime errors?

**Comment by dbreshears** [comment]
@mikanyg,   this may result in runtime errors but I would not expect anything in build/packaging.  This property is there to disable the automatic updating of the manifests that the tooling provides for Actor projects as well as servicemanifest imports that may have been orphaned in the app manifest.    If you disable this in the tooling you will then ( based on any service, parameters or app changes), will need to keep the manifests manually updated appropriately.    It was primarily created to workaround to a bug / issue in the tooling where certain SCC providers such as TFS would auto checkout the manifest files on every build due to the external exe's touching the files.

**Comment by MikkelHegn** [comment]
Suggest closing this issue.
