### ISSUE TITLE
Running isolated Service fabric Service

### ISSUE THREAD

**Issue by TaiAivaras** [Azure/service-fabric-issues#578]
Hey,

I was wondering what are some common practices to debugging standalone Service fabric services, without publishing to the cluster. 

I'd like to be able to spin up the service in isolation so I can test the service end to end before creating the service package and deploying it as part of an application.

Do i need to implement separate hosting solution or are there better approaches?

Thanks.

**Comment by VipulM-MSFT** [comment]
The single node development environment provides an easy inner dev loop. The local development cluster runs the same set of bits (not an emulator). The recommendation is once you do testing with single node, switch to using the five nodes to eliminate any assumption about the services being on the same machine.

**Comment by TaiAivaras** [comment]
I had something else in mind - most of The examples i've come across recomend storing all The services along with service fabric application in one project, one repository, having them all tightly coupled. I may be missing some important reasoning, but that doesn't seem like The best setup from debuging/deployment perspective. Surely someone has tried a more granular approach (separate solutions/repositories) to service fabric. It would be interesting to know if there are some common practices for ir.

**Comment by VipulM-MSFT** [comment]
If the services are loosely coupled then may be they are part of different applications. If they need to be in one application, you can probably create fakes or mocks of the interfaces that other services implement and then combine everything in a packaging repository.

**Comment by masnider** [comment]
There's an [open source][0] Mocks [package][1] that can help you to do normal unit testing with Service Fabric, and several of our [samples][2] show a similar pattern with mocks and unit testing. 

Mocking out the interactions between your service and other services and doing unit testing of logic outside of a SF cluster but you'll want the cluster in order to do things like testing upgrades, rollbacks, and [chaos][3].

Separately you point out that having everything in one repo isn't ideal since it encourages coupling. We've seen that before - and yeah that's the way that the tooling points you by default in VS. However SF has no such requirement - we really think about the code packages (that represent the service types) as the independent units that can be recombined into different applications and independently upgraded. As an [example][4] of that thinking I have this basic sample which shows how you could combine the output of a bunch of builds of services packages into a separate/different application package. 

[0]: https://github.com/loekd/ServiceFabric.Mocks
[1]: https://www.nuget.org/packages/ServiceFabric.Mocks/
[2]: https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/tree/master/ReferenceApp 
[3]: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-controlled-chaos
[4]: https://github.com/masnider/SFAppPackageGenerator

**Comment by masnider** [comment]
@TaiAivaras - did these pointers and advice help you? We haven't heard back from you at this point, so we're going to close out the issue. If you have other comments or questions then just comment here or reopen the issue. Thanks!
