### ISSUE TITLE
Package compression: SetupEntryPoint error when startup executable not in root folder

### ISSUE THREAD

**Issue by RichardSirny** [Azure/service-fabric-issues#581]
My startup scripts are located in *code-package/Startup* folder. The setup entry point then looks like this and works like a charm:

```xml
<SetupEntryPoint> 
  <ExeHost>
    <Program>Startup/setup.cmd</Program>
    <WorkingFolder>CodePackage</WorkingFolder>
  </ExeHost> 
</SetupEntryPoint>
```
However, when I try to publish into SF cluster with enabled package compression, I get an exception from Register-ServiceFabricApplicationType command saying that "The EntryPoint Startup/setup.cmd is not found". Workaround is to move the *setup.cmd* into code root folder.

Is this expected behavior or a bug?

minimal repro: [SetupWhenCompressed.zip](https://github.com/Azure/service-fabric-issues/files/1422062/SetupWhenCompressed.zip)

**Comment by suhuruli** [comment]
@RichardSirny  - this looks like an issue and I have tagged @alexwun who can help you with this.

**Comment by oanapl** [comment]
@RichardSirny, thank you for reporting this! 
For compressed packages we optimize our copying and processing operations by keeping the zipped files in image store. We only unpack the zip files on the nodes where the replicas need to run. This is the reason provision fails with entry point not found, because we don't look for it inside the zipped package.
We have an internal enhancement to add support for this scenario.

**Comment by oanapl** [comment]
@RichardSirny , can you try the following to see if it fixes your problem?

```xml
<Program>Startup/setup.cmd</Program>
```

change to 

```xml
<Program>Startup\setup.cmd</Program>
```
(see slash converted into backslash).

**Comment by RichardSirny** [comment]
Thanks, it works on the repro!

2017-11-28 18:43 GMT+01:00 Oana Platon <notifications@github.com>:

**Comment by oanapl** [comment]
Perfect! I will keep tracking the original issue (<Program>Startup/setup.cmd</Program>).

**Comment by oanapl** [comment]
This has been fixed in the latest release.
