### ISSUE TITLE
Insufficient documentation on fabric:ImageStore

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/service-fabric-issues#6]
I'm going through learning of SF and find that information on `fabric:ImageStore` is insufficient.

1. it's provided as part of a scenario here and there, but not explained thoroughly. Example: [automating deployments](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-automate-powershell/#task-deploy-a-service-fabric-application)
1. [one of the responses on SO](http://stackoverflow.com/a/34886586/59563) mentions that `fabric:ImageStore` could point to locations other than a local file (blob storage?), but that information is nowhere to easily find (perhaps I'm missing something obvious)?
1. MSDN documentation is close to useless ([FabricClient.ApplicationManagementClient.CopyApplicationPackage()](https://msdn.microsoft.com/en-us/library/system.fabric.fabricclient.applicationmanagementclient.copyapplicationpackage.aspx))

Personally, I'd love to see the Blob example, since dev cluster is defaulting to the file system where in production that is not always be the case.

**Comment by SeanFeldman** [comment]
Anyone? Thank you.

**Comment by masnider** [comment]
fabric:ImageStore specifically refers to the image store service provided as a system service in the cluster by default. The local development doesn't use this and instead points to local file storage as a performance improvement for developer scenarios (don't need to replicate your application package 5 times on your one hard drive). We don't support today running your Azure hosted Service Fabric cluster using Azure Blob Storage as the image store - in practice this introduced an additional dependency and was a source of potential error (people had to clean the image store if they ever reset their cluster - with the ImageStoreService this is automatic). So in production you're almost always going to be running with the service, and the "fabric:ImageStore" syntax will be correct.

**Comment by SeanFeldman** [comment]
@masnider this should be documented. I have to admit that even after reading, I'm not entirely sure how to go about using `fabric:ImageStore` with the development cluster. 

Also, I'm somewhat confused by the syntax. I'd expect to refer to the image store service as `fabric:`*/*`ImageStore`.

**Comment by masnider** [comment]
The syntax I specified is correct. For your dev vs. azure clusters you can check it out by looking inside of a running cluster via Get-ServiceFabricClusterManifest and looking at whatever is currently configured. For example:

``` xml
 <Section Name="Management">
      <Parameter Name="ImageStoreConnectionString" Value="file:C:\SfDevCluster\Data\ImageStoreShare" />

```

We're happy to document these things, but it is still not clear what problem you're actually hitting. Is the question just what to specify when you need to copy? In that case today the default for the local cluster is "file:C:\SfDevCluster\Data\ImageStoreShare" and the default for a cluster in Azure is "fabric:ImageStore".  FYI we've also got a bug filed where we would only require the parameter if you wanted to point the operations at a cluster other than the one you are currently connected to (for some reason).

**Comment by SeanFeldman** [comment]
@masnider I'll try to approach it from a different perspective. I'm using [.NET API documentation](https://msdn.microsoft.com/en-us/library/system.fabric.fabricclient.applicationmanagementclient.copyapplicationpackage.aspx) and trying to understand what/when should be used and how it works.

> Uploads an application package to the Image Store in preparation for provisioning a new application type.

Great, let's have a look at the parameters

> imageStoreConnectionString
> Type: System.String
> The connection string for the Image Store as specified in the Cluster Manifest.

_"The connection string for the Image Store as specified in the Cluster Manifest."_ The documentation as dry as only MSDN can be. No reference to `fabric:ImageStore` and it what cases I should be using it as you've described in [your comment](https://github.com/Azure/service-fabric-issues/issues/6#issuecomment-223089235). The code will be running either locally or in the cluster. Does that mean I have to change the parameter value based on the environment or the environment will do that. This kind of information is a essential for a useful documentation. .NET API should focus on explanation for a code-centric approach. 

I hope you see the point I'm trying to convey. Thank you.

**Comment by masnider** [comment]
I completely agree that the documentation is incomplete, and we'll go and improve the docs, but my real goal is to make this irrelevant to you, the user. Today yes you do have to know and specify, and the simplest way to find out dynamically is to look at the cluster manifest of the cluster your are connecting to, or have some other way of discovering that. This said - this today is only different between your local environment and production. I will also follow up to see if we can add back in the image store service for local development, but this was discussed at length previously and developers preferred the quicker local turnaround. Personally I preferred the consistency, so I doubt there is any real "right" answer.

**Comment by SeanFeldman** [comment]
I completely support the idea of consistency. The code should not be different based on environment. And if there's not way to do it otherwise, documentation should elaborate.
You got my vote for consistency :) (if there's an issue, I'll chime in).
Thank you @masnider

**Comment by tully32** [comment]
IT'S BEEN LIKE 7 MONTHS. WHERE IS THE NON CRAP DOCUMENTATION?

**Comment by masnider** [comment]
@tully32 Yelling certainly won't help you. The team is going through the docs to try to improve all the parameters documentation in particular which is sparse on MSDN. You may also notice that it's not MSDN anymore (well not quite, docs.msft.com) which was a change outside our control which unfortunately caused a whole bunch of work that doesn't materially improve the docs themselves. So now that that is done, we're working on improving the content. In the meantime if you're looking at a conceptual doc that doesn't get it right or which you feel needs more work, you can always a) comment and b) submit a PR and we can all work to improve things.  But all caps screaming in here isn't going to accomplish anything.

**Comment by oanapl** [comment]
@tully32, thank you for the feedback. Like @masnider said, we appreciate feedback on specific things that you find inadequate.
We have an internal hackadoc in our team coming soon. Improving this topic is a top priority on our list.

**Comment by theMichaelB** [comment]
While I'm not particular one to shout, it does concern me that in seven months even the basic parameters documentation isn't improved. While it might not accomplish anything, I am sure that as engineers you have experienced the frustration that bad documentation produces, and as it stands, Service Fabric documentation is very sub-standard. While a lot of the documentation for docs is improved via PRs, it is exceptionally difficult to write parameter documentation without having good knowledge of what those parameters do in the background. As for commenting, this thread is seven months old, and the specific item that it is commenting about hasn't changed. So it seems that neither of those things actually accomplish anything. 

Which I imagine, more than anything, is what leads people to ALL CAPS SCREAM. 

That we need to wait for your hackadoc day before you will improve documentation for this, suggests it might not be at the very top of your priority list. 

What is actually needed is the Service Fabric team to put actual time into writing documentation that helps the people who are using the thing to do so. That needs to be addressed as an explicit body of work, rather than the occasional special day's mini-effort. 

I do realise that Service Fabric is being heavily developed, but what use are new features if we can't even understand how the old features work?

**Comment by oanapl** [comment]
@theMichaelB, thank you for the feedback. We understand your pain and frustration. 
This is not an excuse, just an explanation: we, the engineers in the team, are writing documentation for the features we own. We have improved some of our existing documentation, but there is so much new work coming in that we focused more on adding documentation for that.
The hachadoc I mentioned is intended to raise awareness in the team about the documentation that needs attention, as well as teach us how to write better documentation in general. It's not intended to fix all the problem documentation areas in one day - this simply can't happen. We want to improve what we can at hackadoc and then each owner should continue to improve his/her area.
Please continue to give feedback on unsatisfactory documentation.

**Comment by tully32** [comment]
@oanapl Sure thing. Let's begin.

1. What are the purposes of S_FSSUserffffffff and P_FSSUserffffffff in the FSSGroupffffffff group?
2. How do they interact with the Network Service User?
3. What are the required system wide permissions for a non-AD service fabric installation, both clustered and local, to function including default settings you probably think are irrelevant?
4. What are the required AD permissions for a service fabric installation, both clustered and local?
5. What is the proper setup for a ClusterIdentity and what does that actually look like in AD in regards to Service Fabric? 
6. Are x509 and Windows security settings mutually exclusive or not? 
7. What is the proper policy to put in the "Access this computer from the network" GPO for service fabric to function? "Everyone" and "Authenticated Users" seems just a bit too broad. 
8. Have you documented any recurring issues and their resolution? What happens when there's only one node in the ImageStore Service and the cluster errors out? (hint: see question 7. Your policy is misconfigured for service fabric due to no documentation) What happens when the UpgradeOrchestration service rotates out primary and secondary nodes in a failed state repeatedly? (hint: see question 7. Your policy is misconfigured for service fabric due to no documentation)
9. How do you change Service Fabric from creating the local users and groups and instead use AD users or groups? 
10. Where's a step by step guide to setting up a service fabric cluster in conjunction with Active Directory? 

Why is this not priority #1? I can't, in good conscience, recommend service fabric to anyone due to the glaring lack of documentation and lack of proper error reporting. I understand that you may feel like I am trying to crap all over your hard work, but your hard work isn't useful unless people can understand it. One hackadoc day isn't going to solve these issues either. You need to document the entirety of service fabric. The mere fact that I can't find proper documentation on how to properly integrate it with Active Directory, which almost every major IT Org is probably using if they're considering service fabric, screams of misjudged priorities. I shouldn't have to spend over a week of my time digging through permission after permission when the only information I have to go off of is the fact that a service is failing and I see security audit failures for an undocumented user in my event viewer. 

Rectify all of the above and you'll have documented service fabric in a meaningful manner.

**Comment by oanapl** [comment]
We have added [Understand image store connection string](https://docs.microsoft.com/azure/service-fabric/service-fabric-image-store-connection-string).
We have improved the documentation for C# API CopyApplicationPackage, will be available when our next release is available.
We will continue to improve our documentation. We have involved the right owners to address your points above.
Again, thank you for the feedback and be assured we will be applying it.

**Comment by SeanFeldman** [comment]
@oanapl ❤️ for the image store article. So needed it 6 months ago :)
C# API doco - thanks you!

**Comment by SeanFeldman** [comment]
@oanapl follow up - image store connection string document is not linked to the main menu. Google search doesn't rank it either. So this gem will be buried unless linked properly. Thanks.

**Comment by oanapl** [comment]
@SeanFeldman , thanks for the feedback, will follow up.

**Comment by SeanFeldman** [comment]
@oanapl The article is showing in the menu now. Thanks.

**Comment by oanapl** [comment]
Yes, thank you to @rwike77, he worked his magic :)
And as a heads up, we made improvements to the image store related APIs and Powershell cmdlets documentation. They will come online when we release (really soon now).

**Comment by Jose-CF** [comment]
Hello,

I have gone through the `Understand image store connection string.` however I am sorry but still this is not clear.

In particular, I am copying an application to my local cluster using the azure xplat cli and it really does not matter what I write in the store connection string, all the files get copied always in `C:\SfDevCluster\Data` and all files get random names, like generated from a hash or something similar. They do not get into subfolders.

It is extremely difficult to debug this if I do not know what the image store connection string is doing.
Could you give some hints? Why my files get there? The default storage is supposed to be `C:\SfDevCluster\Data\ImageStoreShare` , right? But my files end up in `C:\SfDevCluster\Data\` without extension and randomly generated names. I can still recognize they are my files because they have same size and I can see they are created when I copy them using azure xplat cli.

Anyone can shade some light in this?
So if my store connection string is `file:C:\SfDevCluster\Data\ImageStoreShare` my files should end up in that path? If I set it to `C:\mytest` should they end up there?

In my cluster manifest it is set to `C:\SfDevCluster\Data\ImageStoreShare` but no clue what is failing.

**Comment by oanapl** [comment]
If your cluster is configured with c:\SFDevCluster\Data\ImageStoreShare, then yes, the app package should end up inside that folder.
Here is an example from my local cluster (i am on Windows, using Powershell with service fabric module, not azure cli).

```powershell
PS C:\WINDOWS\system32> Copy-ServiceFabricApplicationPackage -ApplicationPackagePath E:\pkg\CalculatorApp -ImageStoreConnectionString:"file:C:\SfDevCluster\Data\ImageStoreShare" 
Copy application package succeeded

PS C:\WINDOWS\system32> tree C:\sfdevcluster\data\ImageStoreShare
Folder PATH listing for volume OSDisk
Volume serial number is 000000B8 A234:36A1
C:\SFDEVCLUSTER\DATA\IMAGESTORESHARE
 CalculatorApp
    CalculatorServicePackage
        CalculatorService.Code
        CalculatorService.Config
        CalculatorService.Data

PS C:\WINDOWS\system32> Copy-ServiceFabricApplicationPackage -ApplicationPackagePath E:\pkg\CalculatorApp -ImageStoreConnectionString:"file:C:\SfDevCluster\Data\ImageStoreShare"  -ApplicationPackagePathInImageStore C1
Copy application package succeeded

PS C:\WINDOWS\system32> tree C:\sfdevcluster\data\ImageStoreShare
Folder PATH listing for volume OSDisk
Volume serial number is 000000B0 A234:36A1
C:\SFDEVCLUSTER\DATA\IMAGESTORESHARE
 C1
   CalculatorServicePackage
       CalculatorService.Code
       CalculatorService.Config
       CalculatorService.Data
CalculatorApp
    CalculatorServicePackage
        CalculatorService.Code
        CalculatorService.Config
        CalculatorService.Data
```
Can you paste the exact command you tried and the layout of the directory where you see the files being copied?

**Comment by oanapl** [comment]
@Jose-CF, this looks like a bug in our CLI cmdlet, it doesn't work for file share based image store. Can you re-create the cluster using native image store and run the same command?

**Comment by Jose-CF** [comment]
Thank you a lot for your feedback!

Sure I tried that already. I should set the store connection string in the manifest to "fabric:ImageStore" ? 

It is the local cluster in Windows. When I try to do that and start the cluster, the cluster says the image store connection string is still `file:C:\SfDevCluster\Data\ImageStoreShare`. So, I set myself the string in the manifest to `fabric:ImageStore` and start the cluster. Go to the HTTP cluster administration website and look at the manifest of the cluster, it says store connection string is  `file:C:\SfDevCluster\Data\ImageStoreShare`. Either way it keeps putting the files randomly in `C:\SfDevCluster\Data` without extension and hashed names.

If I use the PowerShell API it works file, i.e. it copies the files to `C:\SfDevCluster\Data\ImageStoreShare` properly. Notice that, the Powershell `Copy-ServiceFabricApplicationPackage` to copy the files to the store HAS AN EXTRA option not available in xplat CLI (`ApplicationPackagePathInImageStore`). I am afraid this option might have to be set but xplat cli might be not supporting it.

Another thing that I did was to sniff the network packets in my local interface when running the `Copy-ServiceFabricApplicationPackage ` PowerShell command but I could only see TCP packages that do not assemble into HTTP messages. Is that normal? I understood from the documentation of servicefabric REST API that there is indeed an HTTP interface available. Tried to make some simple queries to that REST API but did not get a reply.

Any ideas on how can I configure the local cluster to copy properly the servicefabric packages fine with xplat cli?

**Comment by oanapl** [comment]
Thanks for the details.
Copy package in Windows with Azure CLI is not working for share based image store. This is a preview feature, we are going to fix it.

Re. local cluster to use native image store: you can't change your cluster manifest on the fly. You need to change the cluster manifest in templates we provide and re-create the cluster. 
One way to do this is to create the local cluster using the script we provide at 
```powershell
"$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1"
```

Which Service Fabric version do you have? A while back, you could specify the image store connection string as a parameter in the script. Check the script help and if it allows it, pass the connection string "fabric:ImageStore" when you call the script. 

If that's not allowed, you can manually change the cluster manifest template you are using (eg. for 5 nodes unsecured cluster, change C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\NonSecure\FiveNode\ClusterManifestTemplate.xml). Search for the section Management, entry ImageStoreConnectionString and change it to fabric:ImageStore.
Should look like this:

```xml
    <Section Name="Management">
      <Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
```
Then re-create the cluster by calling DevClusterSetup.ps1.

Once the cluster is re-created, you can check the cluster manifest to see the new option is set correctly.

**Comment by Jose-CF** [comment]
Thank you for your feedback.

I think there is something a bit fishy going on here.

I tried the first solution. So I went to the template and changed the `ImageStoreConnectionString` value to `fabric:ImageStore`. This obviously cannot succeed because the script that deploys the local cluster is expecting the token `ImageStoreConnectionStringPlaceHolder` in the template to replace it with the connection string. (see `ClusterSetupUtilities.psm1`).
Fine.
So in addition to set the connection string in the template to `fabric:ImageStore` I commented out from `ClusterSetupUtilities.psm1` script that line
`FindAndReplace -filePath $manifestFile -toReplace "ImageStoreConnectionStringPlaceHolder" -newString $imageStoreConnectionString`

Deploy the cluster... succeeds... but.... SURPRISE! The manifest STILL says the connection string is `C:\SfDevCluster\Data\ImageStoreShare`

How is that possible? Is there a ghost in my machine?

Ok so in a desperated try I activated again the line to replace the token `ImageStoreConnectionStringPlaceHolder` but now with a fixed value:

`FindAndReplace -filePath $manifestFile -toReplace "ImageStoreConnectionStringPlaceHolder" -newString "fabric:ImageStore"`

Deploy cluster.... and .... surprise, the manifest still says the store connection string is `file:C:\SfDevCluster\Data\ImageStoreShare`

Another try... stop the cluster. Go to the clusterManifest.xml and to FabricHostSettings.xml... set in both the connection string to `fabric:ImageStore`. Restart the cluster....
The explorer keeps saying the connection string is `file:C:\SfDevCluster\Data\ImageStoreShare`


So it means to me clearly that neither the deployment script, nor the template is really setting this value, i.e. this is kind of hardcoded, isn't it? I think it is technically impossible to change this value.

But then, it means we agree that it is technically impossible to use azure xplat cli to copy application packages to service fabric cluster implementation in Windows. 

Please confirm.

**Comment by oanapl** [comment]
I didn't have an issue with replacing ImageStoreConnectionStringPlaceHolder: since it doesn't exist, the ClusterSetupUtilities script doesn't replace anything. These steps on my Windows cluster with 5.5.216.0 installed.

Can you try this: Service Fabric Local Cluster Manager -> Remove Local Cluster. Call Powershell script .\CleanCluster.ps1 -> check that the c:\SfDevCluster\Data is cleaned up. You can delete c:\SfDevCluster.

Undo all your changes to the cluster manifests and scripts.
Go to the right manifest file (in my case, I did 5 nodes, non-secure, non-win7, since I have a Win10 machine). Make sure you look at the correct manifest (5 nodes vs. 1 node, secure vs. non-secure, win7 etc). Open the file as admin, otherwise you won't be able to change it.
Just as before, change the connection string:

```xml
<Section Name="Management">
      <Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
```

Make sure you have a section for ImageStoreService. I already had it, in case you don't, please add it:

```xml
    <Section Name="ImageStoreService">
      <Parameter Name="TargetReplicaSetSize" Value="3" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
    </Section>
```

Save the manifest file, close it.

Call DevClusterSetup script again. Once done, check the image store with 
```powershell
PS C:\> Get-ServiceFabricClusterManifest
```

**Comment by Jose-CF** [comment]
Hello,

Thank you for the feedback.
The steps you mention are the one that I already did when I wrote my previous message.
I tried again, uninstalled and installed everything (including servicefabric + sdk).


The point is, why do you say you do not have `ImageStoreConnectionStringPlaceHolder`? If I go to:
`c:/Program Files/Microsoft SDKs/Service Fabric/ClusterSetup/NonSecure/OneNode` I have two .xml templates. Both of them contain this line:
`<Parameter Name="ImageStoreConnectionString" Value="ImageStoreConnectionStringPlaceHolder" />`
Same thing for 5 nodes.

Your installation does not contain that line? According to servicefabric documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started) I am using the latest version. And this template comes like that with a fresh installation.

For the local cluster in linux, I can see the template contains this line:
`<Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />`

That's why it works fine, I guess.

But let me please insist once more again. The local cluster I get with my fresh installation of service fabric has this line in all templates:
`<Parameter Name="ImageStoreConnectionString" Value="ImageStoreConnectionStringPlaceHolder" />`
And even after creating the cluster it does not matter what value I set in that, no matter if I set it in the template before creating the cluster or in the manifest once the cluster is created. No matter if I restart or what I try, if I query the manifest of the cluster he will always say the connection string of the image store is: `file:C:\SfDevCluster\Data\ImageStoreShare` . What makes me thing... this might be hardcoded somewhere. No clue.

In any case, I am really curious how your local cluster template does not have the `ImageStoreConnectionStringPlaceHolder` and mine yes.

Using Microsoft Azure Service Fabric 5.5.216.0
Using Microsoft Azure Service Fabric SDK 2.5.216.0

**Comment by oanapl** [comment]
@Jose-CF, I am sorry your experience is so frustrating. I used the same versions and I had no issues changing the image store. Let me review your questions: I *do* have the place holder in the template. 
Initially,
```xml
<Parameter Name="ImageStoreConnectionString" Value="ImageStoreConnectionStringPlaceHolder" />
```
Then I change this to:
```xml
<Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
```
I change this before creating the cluster.
If you don't have an entry for ImageStoreService, you must add one, or the manifest will fail validation (by default, the image store service is configured with more replicas than there are nodes in this cluster).
Above, I set the target and min replica set size to 3, for the 5 nodes cluster.
If you want the one node cluster, you need to change the target and min replica set size to 1.
```xml
<Section Name="ImageStoreService">
      <Parameter Name="TargetReplicaSetSize" Value="1" />
      <Parameter Name="MinReplicaSetSize" Value="1" />
</Section>
```
Did you change all the templates with fabric:ImageStore? Have you re-opened to make sure they are correctly set before re-creating the cluster? Which cluster are you creating, 5 nodes or 1 node (.\DevClusterSetup.ps1 -CreateOneNodeCluster)?

Out of curiosity, have you tried these steps on a different machine?

**Comment by Jose-CF** [comment]
Hello,

Although not solving my problem I am happy to know you have the `ImageStoreConnectionStringPlaceHolder` token origially also.

Yes, I have been repeating and going over these steps since last week. I tried in different machines in Windows 10, this problem always there. The cluster in Linux working flawlessly though.
I tried many permutations for the solution, including 1 to 5 nodes, rebooting, reinstalling .NET ... nothing seems to have an effect. Whatever I do, the cluster will tell its connection string is `file:C:\SfDevCluster\Data\ImageStoreShare`

I did NOT try to add a ImageStoreService, let me do it when I will switch to Win 10 again, I hope that fixes the problem :)

**Comment by Jose-CF** [comment]
@oanapl Sorry, first of all excuse me, my bad that I missed the `ImageStoreService` in your previous message.

I added it now and it worked LIKE A CHARM! 

So that was the problem apparently.
But the real problem is in my opinion... an usability problem. Why is the hell the template would not use by default the `fabric:ImageStore` connection string? I mean what is the benefit of not using it? If none why not to use it? 
Thank's!

**Comment by oanapl** [comment]
@Jose-CF , glad it worked!
Like I mentioned, the setup script used to have an option to allow you to choose which image store you prefer. This was removed; we want to expose the same experience as with standalone package.
The default for local cluster is share because it optimizes some copy operations when uploading and downloading packages on nodes.
In our next release, we changed the option that allows using the machine name (`.\DevClusterSetup.ps1 -UseMachineName`) to use image store. So you won't have to manually change any manifests like we did now.
Once we fix the upload package cli to work correctly for shares, the image store type won't matter.

**Comment by niravbhalodiya** [comment]
Hi,

I am getting below error while publishing my application to the service fabric(see attached image),
Is it related to ImageStore disk space issue ? If so, what is the maximum allowed size in ImageStore directory ?
![sf-issue](https://user-images.githubusercontent.com/8242582/29558250-273c3cd8-8749-11e7-80cc-e0d1e575a843.jpg)

**Comment by oanapl** [comment]
The error message says "not enough space on the disk". That means that the VM where the image store service primary is has no more space. Try [removing unused application packages](https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricapplicationpackage) to make more space.
You can also look on the VM to see if something else consumes space - too many logs etc.
