### ISSUE TITLE
Service Fabric Explorer - Not able to disable all nodes

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#600]
Hi Team,
i have 2 VMs which are running 3 nodes.
In 1 VM, i have 2 nodes running. i tried to deactivateboth the nodes on that VM from SF Explorer  but its saying Fabric node is taking longer than expected to deactivate.” 

Thanks,
Naresh

**Comment by nareshkhatri81** [comment]
one more issue after disabling one of node from SF. i was still able to get to that by using proxy service.
 http://ipnode3:19081/app/service. 
if node3 is down and its naming service is down in SF Explorer. how can i reach to the service using proxy service.

what disabling/deactivating node does actual ?

**Comment by vturecek** [comment]
@nareshkhatri81 Are you trying to bring down the cluster? Also running 3 nodes on 2 VMs isn't a good idea, definitely not supported for production workloads.

This overview doc might help clarify some of this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-content-roadmap

**Comment by nareshkhatri81** [comment]
Yes. This is our test env. For prod, we are aware of recommedation.
I am trying to bring 2 nodes down in 1VM but no luck.

**Comment by EVMartinez** [comment]
@nareshkhatri81  I don't think you can bring down more than 1 at best, the second will be forever (you'll get an error eventually) disabling due to quorum loss

**Comment by masnider** [comment]
The feedback here is correct. You can't shut down all the nodes in a cluster gracefully because it would cause downtime, so SF itself stops you. Also, 3 nodes on 2 VMs is an unsupported scenario. I would back up and consider what you're really trying to achieve with this scenario and perhaps open a new issue with a clearer description if you're still having issues after understanding what deactivation does and with a cluster that meets the minimum requirements.
