### ISSUE TITLE
Question - Does Service Fabric has something OOB for auto scaling based on demands ?

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#620]
There are ways to scale up and down manually from SF Explorer.
We are running cluster on premise.
Does SF has any OOB capabilities where it can monitor Node resources like RAM, CPU, Containers IIS Request in queue and spin up new instances of containers ?

Thanks,
Naresh

**Comment by xunlu** [comment]
VMSS itself provides auto scale feature based on standard perf counter.  Chacko can provide more details on our plan if you are looking for service fabric driven auto-scale.

**Comment by nareshkhatri81** [comment]
could you elaborate more on VMSS ?

**Comment by ChackDan** [comment]
VMSS does not apply to you, since you are an on-premise deployments. The new instances of the containers are nothing but adding new app instances or service instances. At this time there is no 
auto scaling" of containers based on CPU/RAM out of the box, however you are very easily add a service watchdog that does that, based on the criterion you need.
Read more on the building blocks you can use - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-scalability
