### ISSUE TITLE
Please allow creation of cross platform .NET Core 2.0 Reliable Services

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#644]
Default project templates for .NET Core 2.0 currently have in csproj:
```
<RuntimeIdentifier>win7-x64</RuntimeIdentifier>
```
In my opinion it would be a good idea to try to remove this identifier because it will allow to create cross platform packages that will work on both Linux and Windows SF clusters.

However there is a problem, because there is no (or at least I am not aware of) cross platform way to specify .NET Core assembly as an entry point.

Using cmd is not cross-platform.

**Comment by vturecek** [comment]
@mkosieradzki this is something we're working on.

For background, you should be able to *remove* the RuntimeIdentifier from your .csproj so that the project builds a platform-neutral DLL *without* an EXE in the build output.

Then you need to use the dotnet CLI to run the application DLL. This requires two things:
1. The .NET Core runtime must be installed on the cluster
2. The service entry point needs to be "dotent myapp.dll". The issue here is that Service Fabric performs a validation on the service package to make sure the executable in the entry point exists in the service package. Since "dotnet" is an executable that is installed on the machine rather than carried with the service package, the validation fails. This is something we can fix.

**Comment by linggengmsft** [comment]
This support will be released in v6.2 as "ExternalExecutable", please notice our release note for details.
