### ISSUE TITLE
Unable to roll over to new reverse proxy certificate when using cert common name

### ISSUE THREAD

**Issue by mattcorr** [Azure/service-fabric-issues#659]
Hello,

We have a On Premises Service Fabric 6.0.219 cluster.
We have defined the SSL certificate to use for the Reverse Proxy in the cluster manifest as shown:

```
       "CertificateInformation": {
             "ReverseProxyCertificateCommonNames": {
              "CommonNames": [
                  {
                    "CertificateCommonName": "Certname"
                  }
                ],
                "X509StoreName": "My"
            }
        }
```
But when we update this certificate on all the cluster nodes, we are unable to find a way for the cluster to "recognise" it and start using it without having to restart the actual servers in the cluster. This seems a bit drastic, and would have thought a rolling restart of the nodes might have been possible so there is no down time.

The [official doco about certificates](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure) implies you need to use a primary and secondary certificate thumbprint and _switch over_ between the certificates. 

So given that you can define a certificate via the `CertificateCommonName` as shown above, I would like to see a process for switching over to an updated certificate given that they would be sharing the same common name?

Thanks for your help!

**Comment by kavyako** [comment]
@vturecek : Do you have any suggestions on how to go about this without any downtime?

**Comment by mattcorr** [comment]
Any updates on this? Still curious if there is something I am missing?

**Comment by dealboy** [comment]
I would also be interested to know the answer  (or better see it in the official documentation)

**Comment by dealboy** [comment]
@mattcorr did you find a solution for that case ? I think restarting nodes is also fine, but I would expect it to be in the documentation.

**Comment by kavyako** [comment]
@mattcorr A node reboot is not required for cert updates for the reverse proxy. We have logic in place to monitor the cert if it is updated and start using it. Could you share some more details to help us identify if this is a bug. Correct me if I am wrong, the scenario you have is:
1. Reverse proxy certificate is specified using common name.
2. This cert was updated on all the nodes.
3. When you say the cluster was not recognizing it , what was the behavior you are seeing? Did request to the reverse proxy fail? Since you updated the cert, I assume the old certificate was not present on the nodes anymore Or was reverse proxy still serving the old certificate?
4. Was reverse proxy cert same as cluster/server cert?

**Comment by mattcorr** [comment]
We had situation 4. The reverse proxy certificate was the same. We were just updating how it was getting referenced. (From thumbprint to common name). 

Honesty, it has been so long since this was mentioned I am a bit fuzzy about it. But I will be getting back to this next week. I'll see what is happening now when we upgrade to SF 6.1 on our on Prem servers.

**Comment by kavyako** [comment]
I would recommend updating to 6.2. We have also added some logic to check for certificate updates and set the right acl's so that reverse proxy has access to the cert s private keys.

Here is a brief summary of the logic:
Case where reverse proxy certs are updated with cluster config upgrade: In this case, reverse proxy should start serving the new certificate immediately after the upgrade is successful. A node restart is not required.
Case where reverse proxy certs are specified using common name and new certs are installed on the machine, there is no config upgrade: We check for certificate updates every 60 minutes so there might be a delay of max 60 minutes for reverse proxy to start serving the new certificate.

I am closing the issue with this info. 
If you run into issues with certificate update with 6.2, please reopen and we will look into it.

**Comment by mattcorr** [comment]
Thanks fo the update... But when will 6.2 be released? when I looked at the [SF blog](https://blogs.msdn.microsoft.com/azureservicefabric/), they only mention 6.1 update 3.
