### ISSUE TITLE
Custom ActorFactory creates v1 client by default.

### ISSUE THREAD

**Issue by tanwarsatya** [Azure/service-fabric-issues#667]
Similar to #547 

I have a method to check active actors and when I try to create ActorServiceProxy it's using the V1 client by default.  

Same method creates a V2 client if before creating ActorServiceProxy I create any other Actor Proxy which has V2.Client attribute specified in Interface. 

` public async Task<List<string>> GetActiveActorsIds()
        {
            ActorProxyFactory factory = new ActorProxyFactory();
             var fabricClient = new FabricClient(); // Re-use as much as possible

            ServicePartitionList partitionList = await fabricClient.QueryManager.GetPartitionListAsync(_uri);

            List<string> actorIds = new List<string>();

            foreach (var partition in partitionList)
            {
                var key = partition.PartitionInformation as Int64RangePartitionInformation;
                
                Microsoft.ServiceFabric.Actors.

                **IActorService actorServiceProxy = ActorServiceProxy.Create(_uri, key.LowKey);**

                ContinuationToken continuationToken = null;

                var cancellationTokenSource = new CancellationTokenSource();

                do
                {
                    PagedResult<ActorInformation> page = await actorServiceProxy.GetActorsAsync(continuationToken, cancellationTokenSource.Token);
                    actorIds.AddRange(page.Items.Select(x => x.ActorId.GetStringId()));

                    continuationToken = page.ContinuationToken;
                }
                while (continuationToken != null);
            }

            return actorIds;
        }
`
What should be the default behavior when we are exclusively using the V2.Client by specifying the attribute on my actor interface ?? Challenge here is I am not passing that actor interface and instead the proxy factory returning standard IService. 

Or should we be creating a custom service to register our actors. Currently the main method for my actor service uses ActorService class to register our actors. 

` private static void Main()
        {
            try
            {

                using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("SchoolWayz-Actors-DiagnosticsPipeline"))
                 {

                    // Create default garbage collection settings for all the actor types
                    var settings = new ActorGarbageCollectionSettings(Constants.ActorIdelTimeout, Constants.ActorScanInterval);
                    
                    ActorRuntime.RegisterActorAsync<DeviceMessageQueueActor>(
                                    (context, actorType) => **new ActorService**(context,
                                        actorType,
                                        (s, i) => new DeviceMessageQueueActor(s, i),
                                        null,
                                        null,
                                        new ActorServiceSettings
                                        {
                                            ActorGarbageCollectionSettings = settings
                                        })).GetAwaiter().GetResult();

                    // Register SmartTrack Device Actor
                    ActorRuntime.RegisterActorAsync<SmartTrackDeviceActor>(
                    (context, actorType) => new ActorService(context,
                        actorType,
                        (s, i) => new SmartTrackDeviceActor(s, i),
                        null,
                        null,
                        new ActorServiceSettings
                        {
                            ActorGarbageCollectionSettings = settings
                        })).GetAwaiter().GetResult();

                    // Register SmartTrack Device Message Processor Actor
                    ActorRuntime.RegisterActorAsync<SmartTrackDeviceMessageProcessorActor>(
                    (context, actorType) => new ActorService(context,
                        actorType,
                        (s, i) => new SmartTrackDeviceMessageProcessorActor(s, i),
                        null,
                        null,
                        new ActorServiceSettings
                        {
                            ActorGarbageCollectionSettings = settings
                        })).GetAwaiter().GetResult();

                    Thread.Sleep(Timeout.Infinite);
                 }
          
            }
            catch (Exception e)
            {
                ActorEventSource.Current.ActorHostInitializationFailed(e);
                throw;
            }
        }`

**Comment by amanbha** [comment]
@tanwarsatya Could you please try with specifying the V2 client attribute on the assembly in which you are making the ActorServiceProxy calls.

**Comment by tanwarsatya** [comment]
This is what I am thinking , but if we create any other actor before that proxy it’s creating V2 client. Is there a way we can specify in constructor that we want to create a v2 client for service proxy. If not I will go with creating my actor service class inherit from IActorService.

**Comment by tanwarsatya** [comment]
Hi @amanbha  I tried both the approach mentioned below but it's not working as expected and returning a v1 client.

1. Adding attribute for V2 in calling assembly.
2. Creating MyService class which implements IMyService which derive from IActorService.

I believe the root cause is due to the fact that ActorServiceProxy.Create(_uri, key.LowKey)
 returns an IActorService and hence no matter which approach we take it always return V1 client. 

The only workaround I found to get a V2 client is by creating a dummy Actor before calling
ActorServiceProxy.Create(_uri, key.LowKey). Calling the dummy actor is forcing the factory to initiate a V2 client and the same is used later when ActorServiceProxy.Create() is called. 

I am not sure how this should be handled by ActorFactory to force a V2 client in this scenario.

**Comment by amanbha** [comment]
@tanwarsatya Could you please share the repro code for 1 & 2 above, i will debug it.

**Comment by Mardoxx** [comment]
@tanwarsatya I think you are correct. If you instantiate ActorServiceProxy as you are doing it will create a V1 ActorProxyFactory for internal DefaultProxyFactory (which is a singleton).

What happens is this:
1. Call [non-typed method](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/c7d15c5bdfcf676c55e60f3604be746573360b8a/src/Microsoft.ServiceFabric.Actors/Client/ActorServiceProxy.cs#L81) on ActorServiceProxy

2. This calls [ActorProxyFactory with IService](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/c7d15c5bdfcf676c55e60f3604be746573360b8a/src/Microsoft.ServiceFabric.Actors/Client/ActorProxyFactory.cs#L140) (which has no attribtes, default is V1)

3. This [instantiates DefaultProxyFactory singleton with V1 proxy](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/c7d15c5bdfcf676c55e60f3604be746573360b8a/src/Microsoft.ServiceFabric.Actors/Client/ActorProxyFactory.cs#L204)

4. When you try and perform any action on the returned ActorService IService it will assume it is a V1 service and hence fail.

A [similar issue](https://github.com/Azure/service-fabric-issues/issues/570) happens with the ServiceProxy class but it is relatively easily worked-around. The associated PR outlines the issues and potential fix. Basically I think this is a side-effect of an optimisation whereby you only create the proxy once -- and also avoid the need to check the assembly attribute each time you call to the proxy. Trouble is, the one that is created internally isn't necessarily the correct version!

V1 remoting is to be deprecated "soon", so hopefully this won't be an issue going forward. 

Your best option is, as @amanbha says create a dummy `IMyActorService : IActorService` and have assembly attribute on this to say use V2,(I would have it in the same assembly as my `IMyActor : IActor` interface, then you only need the assembly directive once), then instantiate your proxy using `IMyActorService` as your type param. This should work.

>Could you please try with specifying the V2 client attribute on the assembly in which you are making the ActorServiceProxy calls. 
I would not have thought would work -- since the `IActor` used for proxy creation is in the `Microsoft.ServiceFabric.Actors` assembly which does not have this attribute.

**Comment by amanbha** [comment]
Thanks @Mardoxx  specifying the V2 client attribute on the assembly in which you are making the ActorServiceProxy calls should also work as code tries to get the attribute eventually from EntryAssembly as well. @tanwarsatya Please try these and if it doesn't work, share the repro, I will take further look at it.

**Comment by tanwarsatya** [comment]
Thanx @Mardoxx , @amanbha , as I mentioned above i tested both approaches and it's not working. @Mardoxx  correctly explained that even creating IMyService won't help because  "This calls ActorProxyFactory with IService (which has no attribtes, default is V1) ". 

If in future V1 will be deprecated "soon", this would be a non issue. Untill then i am creating a dummy actor proxy instance before calling ActorProxyService which is forcing the V2 client generation. 

I am working to create a sample repository and will share the soon.

**Comment by amanbha** [comment]
Sure @tanwarsatya, pleas share the sample. @Mardoxx mentioned that creating derived service with attribute on it would work.

**Comment by amanbha** [comment]
I am closing this issue, if you have further questions please feel free to ping me.
You can also look at for sample: https://github.com/amanbha/servicefabric/blob/master/samples/ActorCustomSerialization/ActorClient/Program.cs#L55
