### ISSUE TITLE
Register-ServiceFabricApplicationType : Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by spottedmahn** [Azure/service-fabric-issues#718]
In `ApplicationManifest.xml` I defined `<EnvironmentOverrides>` w/ one `<EnvironmentVariable>` entry but I forgot to define that `<EnvironmentVariable>` in `ServiceManifest.xml`.  That produces the following:

>Register-ServiceFabricApplicationType : Value cannot be null.

>Parameter name: source

---

Can that error be improved?  It was hard for me to track down.  I was working w/ someone else's code...

Can the error be made more **self-documenting**?  thanks!

**Comment by masnider** [comment]
@spottedmahn did you already figure this out? I've seen it in cases where there's an application parameter missing or an environment variable not overridden in the service manifest. 

Agree we already have work ongoing to improve this, but if you can help me by telling me what the issue was it will help with routing the bug.

**Comment by spottedmahn** [comment]
Hi @masnider - yes I figured it out.  I tried to override the env variable in the app but I hadn't defined it in the service.

I also have a sample [repo here](https://github.com/spottedmahn/Experiments/tree/master/ServiceFabricEnvTest).

**Comment by mkosieradzki** [comment]
Yup this is a very common mistake. It would be nice to have this error message fixed.

**Comment by oanapl** [comment]
We will improve the error message, thank you for reporting.

**Comment by oanapl** [comment]
We improved the error message in our incoming 6.2 release.
