### ISSUE TITLE
"Index was outside the bounds of the array" when using base EventSource class

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#72]
With the latest update 5.3/2.3, it is no longer possible to use inheritance for the EWT logger classes. It throws the following exception:

`
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=mscorlib
  StackTrace:
       at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
       at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1)
       at Example.ServiceEventSourceBase.ServiceHostInitializationFailed(String exception) in C:\src\github\service-fabric-event-source-bug\src\Example\ServiceEventSource.cs:line 139
       at Example.Program.Main() in C:\src\github\service-fabric-event-source-bug\src\Example\Program.cs:line 33
  InnerException: 
`

I have created a very simple repository with example implementation that throws exception:

https://github.com/sondreb/service-fabric-event-source-bug

**Comment by karolz-ms** [comment]
Hi Sondre,

generally subclassing EventSource with a depth of more than one (e.g. having a base abstract class that derives from EventSource, then having a concrete implementation deriving from an abstract base) is not recommended. Due to how ETW manifests are derived from the shape of the EventSource class it usually does not work. This has nothing to do with Service Fabric and is just a general EventSource limitation.

I understand that there might be desire to share some of the functionality between various EventSources in your system. In general there are 3 ways to deal with it:

	1. Use separate EventSources.   Thus there is a contract for common stuff, and other contract (EventSource) for non-common stuff.
	2. Relax the contract.   Make ‘generic’ events (Message, or Operation, or OperationFailed, or DependencyCall, or …) that can be defined in the common contract but are sufficiently flexible that they cover any interesting case.  
	3. Use Dynamic events (give up on contracts).    In this case you use the new Write<T> events.  This can be combined with either option 1 or 3 (thus you use contract for the static stuff but dynamic for new stuff). 

In practice we have seen option #2 is what people are adopting most frequently.

**Comment by sondreb** [comment]
Ok thanks for the reply, it worked before but not anymore. Ended up having all the logging code duplicate right now, can probably move some of the code in utility classes.
