### ISSUE TITLE
32 bit support within Stateless Services

### ISSUE THREAD

**Issue by wasabii** [Azure/service-fabric-issues#728]
I am trying to retrofit an existing legacy application to run within Service Fabric. Guest executables are fine, but I don't really want to deal with them. It's much cleaner to just build a new entry point. On top of that, I have custom communication listeners, and such (I'm actually firing up a full copy of IIS within a Console app).

Anyways, this app, far down underneath, uses a bunch of COM objects which originate from VB6. Sure, someday I'll fix them. For now, reg-free COM, and a clean build/release system is what I'm after.

But they won't work from inside SF, because the process has to be 64 bit.

What are all of the things keeping this from working? Communication between the process and SF is some sort of weird binary protocol or something? I don't know. I don't intend to use reliable collections.

**Comment by AceHack** [comment]
@wasabii Just from the sound of what you are talking about it seems like a docker container with IIS installed would be an easier path.  At one time I don't think IIS was supported in service fabric before they supported containers.  I think IIS is only supported in service fabric via containers.

https://github.com/Microsoft/iis-docker
https://loekd.wordpress.com/2017/02/08/running-windows-containers-on-azure-service-fabric/
https://quickanddirtyscripting.wordpress.com/2017/05/24/deploying-net46iis-apps-as-containers-into-azure-service-fabric/
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-container

**Comment by wasabii** [comment]
Yeah. It's not easier. My hosting provider doesn't support nested VMs. No
way to start a Windows container.

Thanks for the suggestion though.

**Comment by masnider** [comment]
The guest exe process shouldn't have to be 64 bit since it's not loading any of Service Fabric's APIs, right? 

If you're using our APIs for things, then yes they require 64 bit today, since we require longs for lots of things, and hence your whole process has to be 64 bit. There's no [clean ](https://blog.mattmags.com/2007/06/30/accessing-32-bit-dlls-from-64-bit-code/) [way ](https://blogs.msdn.microsoft.com/oldnewthing/20081020-00/?p=20523) to have 32 bit code loaded inside a 64bit process, so you could always just spawn a different process and then IPC between them, effectively having the 64-bit process that SF needs serving as a proxy to the one that holds the old 32-bit com code. Just make sure you put them in the same job so that if one crashes they both fail. 

I'd suggest that this isn't really cleaner than the guest exe approach, but it is certainly an option and does give you a lot of coll opportunities to mix and match SF capabilities with the existing 32 bit stuff you've got.

**Comment by wasabii** [comment]
Yeah, well, ImpliciteHost is where it looks like I'll be going. But losing out on the Fabric SDK stuff kinda blows. The biggest hit is in the configuration system. I've already got everything being setup and configured through ConfigOverrides. But, now, of course, the guest executable cannot actually read them.

**Comment by masnider** [comment]
Well you can, you just have to go and explore the folder structure and read the XML yourself. The config changes will still get applied and the file rewritten. 

I don't think we're going to be adding explicit 32-bit support for our APIs any time soon. Too many interop and platform issues, and a lot of SF internal fields are explicitly 64 bit for future proofing. 

Running IIS 32-bit inside a container may still be the best option for you. Another thing I've seen people do is to fork another process off from your main service host process that's 32 bit, and load your 32-bit only stuff there (and then interact with it via some local http api or named pipes or somesuch). 

If someone else here has a better idea feel free to suggest it, but at this point I'm going to close down the issue. There's no great solution here :)
