### ISSUE TITLE
Not all files in code package copied over to a node in the cluster

### ISSUE THREAD

**Issue by EspenG** [Azure/service-fabric-issues#74]
When doing a deployment we noticed something strange. A .dll and a .json file was not copied over to one of the nodes in the azure cluster. The problematic code package contained all the other files, it was just these two files that were missing. All the other nodes in the cluster had all the files.

We solved the problem by copying over the two missing files manually, but it would be nice if there was some kind of check to verify that all the files in the code package was copied successfully.

Cluster version 5.3.301.9590

**Comment by cwe1ss** [comment]
Another good example that it would be great to use ZIP files for application packages. Copying just one file and unzipping it on a node is more likely to succeed than copying many distinct files.

**Comment by masnider** [comment]
@EspenG - this is usually because the files were added to the solution as resources, but the item property was not set to always copy that item to the build directory. I've made this mistake a lot of times personally. It is hard for the platform to know what you need to actually be present in the package and what is not, which is why we just take the result of the build. If you are seeing the files present in the build output, but _not_ in the resulting application package then there is a bug in the MSBuild directives somewhere. Can you check and let us know?

@cwe1ss - sure if the file is actually in the build output. Also this is work we know about and are considering, but I think it is orthogonal (though helpful) to what @EspenG ran into.

**Comment by EspenG** [comment]
@masnider sorry if i was unclear. the files are present in the build output and the application package. the files where also copied over to all but one of the nodes in the cluster.

**Comment by masnider** [comment]
Can you repro this and take a screenshots of what is in the image store as well as what you are seeing on disk of the nodes where it succeeded and failed? If that is happening we can take a look. I don't know of any issue today which would cause this. Was the service actually trying to start on that machine without the resources?

**Comment by EspenG** [comment]
This happened on our production cluster, so i can't try to reproduce it now, but i will keep an eye out for the problem in the future. 

Yes, it was trying to start it as a seconday replica, but failed because of the missing dll. that was how we noticed the problem in the first place.

**Comment by masnider** [comment]
@EspenG Do you have the traces available/archived from this timeframe? We can take a look.

**Comment by EspenG** [comment]
We might have something in our log storage. I will take a look when i get into the office tomorrow.

**Comment by vaishnavk** [comment]
@EspenG Please let us know once you have the logs available along with the node name and files that you observed were missing.

**Comment by mholo65** [comment]
@masnider @vaishnavk  I noticed the exact same today. But with the data package. Want logs?

**Comment by mholo65** [comment]
Checking Event Log, seeing lots of these:

```
Log Name:      Microsoft-ServiceFabric/Admin
Source:        Microsoft-ServiceFabric
Date:          2/2/2017 8:38:58 PM
Event ID:      256
Task Category: Common
Level:         Error
Keywords:      Default
User:          NETWORK SERVICE
Computer:      nt1vm000007
Description:
WriteNode failed. HRESULT=-2147467259, Output=CustomOutput
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-ServiceFabric" Guid="{CBD93BC2-71E5-4566-B3A7-595D8EECA6E8}" />
    <EventID>256</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000001</Keywords>
    <TimeCreated SystemTime="2017-02-02T20:38:58.996870400Z" />
    <EventRecordID>28987</EventRecordID>
    <Correlation />
    <Execution ProcessID="26700" ThreadID="6032" />
    <Channel>Microsoft-ServiceFabric/Admin</Channel>
    <Computer>nt1vm000007</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="id">
    </Data>
    <Data Name="type">XmlLiteWriter</Data>
    <Data Name="text">WriteNode failed. HRESULT=-2147467259, Output=CustomOutput</Data>
  </EventData>
</Event>
```

**Comment by oanapl** [comment]
@mholo65 , you can ignore the "WriteNode failed" event log entries. It's a very chatty trace that is otherwise benign. It has been fixed in newer releases.

Regarding the missing files, we have identified a very rare race condition that would lead to missing files from the package downloaded on a node. We are going to fix it in a future release.

**Comment by oanapl** [comment]
@mholo65 , please open an Azure support ticket for this so we can get a closer look and see if there is the known bug or something else: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
