### ISSUE TITLE
Different Fault Domain handling with 6.x

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#747]
Hello,
since we have our own data center with two geo-locations, we always had two fault domains for our three-node cluster.
With the update to 6.x, we can't update the cluster manifest anymore.

This is the error: Config validation: Fault domain count must be greater than 2, current FD count 2.

Is this a bug or a feature? Is it possible to update anyway?

If we raise the count to 3, it works, but only if we specify it when asked, not as input parameter:
![sf_fail](https://user-images.githubusercontent.com/5556013/34664004-f39fd992-f459-11e7-8a34-8e893e60136b.jpg)

**Comment by senj** [comment]
Ok we solved the issue by specifiying the path of the config in the input field instead of the paramter value...

**Comment by masnider** [comment]
Two fault domains has never been supported. If it wasn't catching it before it was just a validation miss. 

Two geos is also insufficient - there's a majority somewhere and if you lose that datacenter then your whole cluster will collapse. You need at least three FDs and three locations for this to really work the way you're expecting and to give you the results you're looking for. 

Please check out the docs [here ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-disaster-recovery) and [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#fault-domains).

**Comment by xela30** [comment]
Is it possible to change existing nodes allocation between Fault Domains?

**Comment by julioas09** [comment]
I'm having the same problem trying to update the configuration of my development cluster.
In production we use a cluster with more fault/upgrade domains, but in dev we use a cluster with only 2FD/2UD... is there any way around this?

Thanks

**Comment by masnider** [comment]
@xela30 yeah nodes can move between fault domains, you just have to do multiple upgrades usually to do it (delete/remove from one FD and then add back with the new FD info). 

@julioas09 I don't think there's any way to override this. Two just doesn't make sense since one of the FDs must have a quorum of some service (like the system services). If your test cluster has more than 3 nodes in it, then 3 FD/UDs should work. There's a bunch of different layouts described [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#fault-domains).

At this point I'm going to close down this issue. We understand that adding this validation broke you, but it's doing the right thing by flagging these configurations which shouldn't have been allowed in the first place.
