### ISSUE TITLE
"Corrupt" Settings.xml SF issue - delete impossible (6.0.211.9494)

### ISSUE THREAD

**Issue by patrikSE83** [Azure/service-fabric-issues#754]
I don't know if I would call it a bug-report but a serious issue that took alot of time to solve.

It started with issues on one of my nodes in my 3node cluster. Had to force a restart from the Azure portal to get it responsive at all.

When I finally got it up and running it didn't want to start certain Applications correct anyway, package issues.

I then deleted the application itself so I could re-create it - that normally solves the issues.  The problem here is that one instance from the Node3 of the application couldn't be deleted - because it couldn't be started.

So I couldn't re-create the application at all. I dug down to find out that the Settings.xml file in the Pkg.Config.1.0.11 folder of the package that was unable to be created had been corrupted. It was only alot of spaces.

So when I reentered the correct Settings.xml, the package could be created from the ServiceFabric node3, and then the deletion could occur.

I would say that the correct behavior would be that if an application is set for deletion - and in startup mode (I restarted both the VM and also restarted from SF) - the instance should be able to be deleted before startup? - Or this might cause issues with replicaSets and such?

At least give some more information when the Settings.xml.

**Comment by masnider** [comment]
Hi @patrikSE83 - some things and info to try:

- If the package is somehow locally not starting, you could usually remove it with something like Remove-ServiceFabricReplica -ForceRemove. This will force SF to forget about the replica and quit restarting it. 
- The same basic thing works at the application level: Remove-ServiceFabricReplica -ForceRemove. Again these should only be used when there's no other way to get the service to shut down cleanly.
- We also would typically recommend that instead of removing the services that instead you push through an upgrade that addresses the issue. That way the service will launch correctly. You can do this even when the application is already unhealthy by setting health thresholds that take the unhealthy things into account, or you could also go to full manual upgrade and just push it through (use sparingly :) )
- Even in these cases, yeah, by default, SF will try to launch things to shut them down cleanly. We do give up eventually, but we try for a long time, because we're trying to perform a graceful shutdown. The above commands skip that, but it means your code doesn't get to run to clean itself up. SF doesn't know the consequences of that, so we try not to do it unless you tell us. 

Hope this helps - what you have sounds like it makes sense and is normal behavior, but that we could be providing more information about what specifically is failing. Does that sound accurate?

**Comment by masnider** [comment]
@patrikSE83 - any additional information? We've also made a lot of telemetry updates in the last few releases that should hopefully catch this sort of corruption, but we haven't seen it yet ourselves. I'm going to be closing down this issue for now since we haven't heard back from you, but please feel free to reopen it if you have a specific repro or any other questions (and you can always open an new issue for any other questions too). 

Thanks!
