### ISSUE TITLE
Subscribe to event when SF resets Instance/Replica of a service

### ISSUE THREAD

**Issue by nineralpha** [Azure/service-fabric-issues#760]
Hi we have a scenario where we are downloading a file locally on each instance of a "**Guest executable service**(stateless service)" when service starts. Now when SF shifts any instance in case of load balancing/failure to a new node we want to download that file again. All we need is an event that notifies when reset occurs, any suggestions?

So far we have found service endpoint change event FabricClient.ServiceManagementClient.ServiceNotificationFilterMatched but when port is reset two notifications are generated instead of one.

Any help in this regard will be appreciated

**Comment by nineralpha** [comment]
@oanapl its the same issue as i discussed in comment of issue "https://github.com/Azure/service-fabric-issues/issues/122".

**Comment by nineralpha** [comment]
@oanapl @alexwun  RegisterServiceNotificationFilterAsync() behaves unexpectedly..Scenario is, a stateful service have subscribed for the events of Guest Exe. even if it is raising 2 notifications for each endpoint change event, then it should always do that, but that not how it is behaving,as the logs show sometimes one notification some times 2.
Change Occured1/15/2018 6:49:05 PM

Change Occured1/15/2018 6:50:05 PM

Change Occured1/15/2018 6:50:50 PM
Change Occured1/15/2018 6:50:55 PM

Change Occured1/15/2018 6:51:45 PM

Change Occured1/15/2018 6:52:05 PM
Change Occured1/15/2018 6:52:10 PM

Change Occured1/15/2018 6:52:40 PM

Change Occured1/15/2018 6:53:00 PM
Change Occured1/15/2018 6:53:05 PM

**Comment by nineralpha** [comment]
@MedAnd SetupEntryPoint will not work in our case

**Comment by alexwun** [comment]
Notifications are delivered as endpoints change and the exact number of notifications resulting from reconfiguration is not deterministic. The notifications will always converge and present you with a notification representing the latest stable state though.

Since you want to hook into SF placement events, consider developing an SF stateless service (non-guest executable). Full SF services will have lifecycle events for when an instance opens and closes.

**Comment by nineralpha** [comment]
@alexwun we are hosting the Node js application so non-guest services will not be an option.."**notifications resulting from reconfiguration is not deterministic**" so is that a bug or something?? do we have an alternate option for Guest exe?

**Comment by alexwun** [comment]
By design, notifications can be used to detect endpoint changes in services for the purposes of service resolution, not for tracking detailed service state changes. Delivered notifications will converge to the latest set of stable endpoints as long as service reconfiguration stabilizes, but you are not guaranteed to observe every intermediate state change during reconfiguration.

What is this file you are trying to download? It needs to be re-downloaded when the guest executable restarts?

**Comment by nineralpha** [comment]
"What is this file you are trying to download?"
We have client server scenario. server is written in Nodejs and hosted as a guest executable.
file contains information about a specific building and for each file(building) there will be dedicated readonly server(guest service). 

"It needs to be re-downloaded when the guest executable restarts?"
Yes, each guest service have 3 instances for reliability, one goes down other will serve client but we have to immediately redownload the file on failed instance. for this we have watchdog which will remember which file each guest service was working on, and will subscribe to failure/reset event to immediately redownload the file by making a call to that affected instance when it get ready again.

so what we are trying to achieve is to immediately act upon failures of instances. and for this we only found **ServiceNotificationFilterMatched**. but two notifications means two download calls to server.

is there any better alternative SF have???

**Comment by alexwun** [comment]
Can't the watchdog keep track of pending downloads to avoid duplicate download calls?

**Comment by nineralpha** [comment]
Yes we have to implement something similar to handle extra notifications as we don't have any other option available. but SF should give something to notify failures properly for Guest executables in future.

**Comment by alexwun** [comment]
Thanks for your feedback, we'll take that into consideration.
