### ISSUE TITLE
File SFlog huge size

### ISSUE THREAD

**Issue by lucamazzanti** [Azure/service-fabric-issues#762]
Hi, I'm expecting a strange behaviour checking the file size of two SFlog file in ServiceFabric folder they have both a Size dimension of 250 GB but a Size on disk of 100 Kb and the other one 4 Mb. I don't have this space on the disk so I think the real size is the disk one, but why i have these values?

**Comment by masnider** [comment]
The replicated SF log is a Windows Sparse File, so that's what you're seeing. 

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365564(v=vs.85).aspx
https://technet.microsoft.com/en-us/library/cc788025.aspx
http://www.flexhex.com/docs/articles/sparse-files.phtml

Hopefully this answers your question.
