### ISSUE TITLE
SDK issue: HealthOperationTimeout has no effect

### ISSUE THREAD

**Issue by karataliu** [Azure/service-fabric-issues#769]
nuget package: 
`<PackageReference Include="Microsoft.ServiceFabric" Version="6.1.232-preview" />`

When using following code to retrieve health state:
```
var fcs = new FabricClientSettings
            {
                ConnectionInitializationTimeout = TimeSpan.FromSeconds(1),
                HealthOperationTimeout = TimeSpan.FromSeconds(1),
            };
var fabricClient = new FabricClient(fcs, endpoint);
var healthState = fabricClient.HealthManager.GetClusterHealthAsync().GetAwaiter().GetResult();
```

If the endpoint is not ready, the `GetClusterHealthAsync` will always waiting for about 60s before returns, ignoring the `HealthOperationTimeout ` setting.

ErrorCode returned in exception: System.Fabric.FabricErrorCode.GatewayNotReachable

**Comment by oanapl** [comment]
Thank you for reporting. We will investigate and get back to you.

**Comment by oanapl** [comment]
HealthOperationTimeout is used only for sending health reports and not for querying health. All the health related settings on the fabric client settings are related to reporting rather than querying (HealthReportRetrySendInterval, HealthReportSendInterval, HealthOperationTimeout). 
The documentation is misleading, we will improve it to be explicit about it.
When a query doesn't specify a timeout, the default fabric client query timeout is used, which is 1 minute.

**Comment by karataliu** [comment]
Got that. Thanks @oanapl.
