### ISSUE TITLE
Guest executable: port in use error for a minute when publish new version

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#78]
When publishing a new version, it seems service fabric tries to start new version of my service before shutting down the old version. Because the port is still used by old version. So the new version will keep failing with "port in use" error, until the old version is shut down.

Is there any way to resolve this? Or am I doing something wrong?

**Comment by masnider** [comment]
That doesn't seem right. By default we do shut down the existing service before starting a new one (if it is an upgrade). Is it possible that you're deploying a new application instance side by side with your old one, rather than doing an upgrade or removing the existing application first? Can you share the steps you followed?

**Comment by qrli** [comment]
I guess it may be related to this: Because we are still in testing phase, we used Publish-NewServiceFabricApplication with -OverwriteBehavior Always. So maybe this does not count as an upgrade?

But I looked into the source code of Publish-NewServiceFabricApplication and found it does remove old app first. I also found that when Publish-NewServiceFabricApplication says the old version is removed, the old version of services are still running.

**Comment by VipulM-MSFT** [comment]
The de-activation of the processes from the node is asynchronous with respect to the delete. The processes may keep running on the node for few more minutes. This is by design. 
$a = Get-ServiceFabricNode | Get-ServiceFabricDeployedCodePackage -ApplicationName <applicationName>
jects
$a.Count

If this returns zero then it means that there are no processes from this application is running on any nodes and it is safe to deploy the application again.

We can update the Visual Studio script to check for the running processing before re-deploying the application.

**Comment by preddy4690** [comment]
I ran into this issue again and it drove me nuts... I've tried everything and I keep getting the same message..

"

> level=fatal msg="Error preparing server: error opening listener: listen tcp :443: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

"

Finally, I have to RDP into each node and restart the server. That resolved the issue and I was able to redeploy the application.

What's the best way to avoid this in the future. I have the  -OverwriteBehavior set to 'Always' in VSTS. Is that the issue?
