### ISSUE TITLE
Question on FabricClient.QueryClient.GetApplicationListAsync Method

### ISSUE THREAD

**Issue by karataliu** [Azure/service-fabric-issues#789]
Ref to: https://msdn.microsoft.com/en-us/library/azure/mt161414.aspx

There is the 'applicationNameFilter' parameter:
```
applicationNameFilter
Type: System.Uri
The application name to get details for.
```

Basically I've got following applications:
- fabric:/a1
- fabric:/a2
- fabric:/b1

I want to select out 'fabric:/a*' application. I tried passing 'fabric:/a' and 'fabric:/a*', but both return empty result.
If using 'fabric:/', it will return all three items.
If using full application name , it will return single result.

Questions:
1. Could there be some document for what 'applicationNameFilter' does?
2. Is there any way to archive listing 'fabric:/a*' applications?
3. Is there any way to list application based on application type?
For the rest api, it does support passing application type:
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getapplicationinfolist

Thanks

**Comment by oanapl** [comment]
The documentation link you are looking at is very old and deprecated. The documentation is now on [docs](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.queryclient.getapplicationlistasync?view=azure-dotnet). 

We have a newer form of the query, [GetApplicationPagedListAsync](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.queryclient.getapplicationpagedlistasync?view=azure-dotnet) that we recommend. 
This API gets a query description that offers ways to filter the returned items.
If no filter is passed, the application list query returns all applications in the cluster. The [applicationNameFilter](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.applicationquerydescription.applicationnamefilter?view=azure-dotnet#System_Fabric_Description_ApplicationQueryDescription_ApplicationNameFilter) is a filter that allow selecting one application. You can't pass a prefix of the application name, you must pass full application name. If such an application exists, it's returned; otherwise, no app is returned.
One of the filters is [ApplicationTypeNameFilter](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.applicationquerydescription.applicationtypenamefilter?view=azure-dotnet#System_Fabric_Description_ApplicationQueryDescription_ApplicationTypeNameFilter). Again, you must specify full app type name, not a prefix.

@rwike77 , can we please remove the msdn link?

**Comment by rwike77** [comment]
@oanapl Yes, I'll get the old MSDN content removed.

**Comment by oanapl** [comment]
The old documentation link was removed.
