### ISSUE TITLE
Unhealthy DnsService due to clashing with windows services

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/service-fabric-issues#796]
Since i have installed the latest runtime (6.1.456) and SDK (3.0.456 ) on my windows 10 workstations (works OK on my windows 2016 server instance) There seems to be a clash with the DNS service trying to bind to port 53 and it being unable due to two other services using the port. Which i established (by finding the PID listed) to be the `Internet Connection Sharing (ICS) service`, and the `Docker Engine (dockerd.exe)`.

If i stop both these services and start my local cluster then all is well.  This seems to be a new thing as i don't remember experiencing this previously.  

I have spotted this on two different windows laptops.

**Comment by milvuko** [comment]
DnsService requires address 0.0.0.0:53 to be free in order to function properly. ICS service has been turned on by default on Windows RS3 Client OS (RS3 was published recently). ICS has a new feature called Default Switch which uses DNS port as well. More info on the new Windows feature can be found at:
https://blogs.technet.microsoft.com/virtualization/2017/07/26/hyper-v-virtual-machine-gallery-and-networking-improvements/

Note that the clash happens only on Client OS, Server is OK. Also, stopping ICS should be sufficient, dockerd.exe can continue running since it doesn't listen on all adapters (0.0.0.0).

**Comment by eaglo** [comment]
sorry to comment here but maybe my problem is related. i also switched to the latest service fabric version and deployed a test cluster in azure (also 3 nodes). my dns service showed a warning about an unhealthy partition ... since waiting didn't seem to help i rebooted the corresponding VM ... afterwards the service was gone and app insights only stated that the Dns Service was removed. Could this be related to this problem?

**Comment by milvuko** [comment]
@eaglo, I don't think it is related. The clash mentioned in this thread happens only on OneBox (dev environment), not real clusters. I can take a look at the problem if you can share cluster's resource ID and region with me.

**Comment by eaglo** [comment]
hey thanks, that would be great. the region is eu-west, the cluster id is 

> 61a5f0ac-a4b5-4a83-83e9-b2cb5f8bdf97

 and the resource id of the cluster is 

> /subscriptions/a709a92b-2db1-44e5-be0a-a750559e5a02/resourcegroups/sws-dev-backend/providers/Microsoft.ServiceFabric/clusters/sws-dev-cluster

**Comment by milvuko** [comment]
Cluster manifest doesn't have the DnsService section, in order for DnsService to be enabled, the cluster manifest has to have the following:
```
    <Section Name="DnsService">
      <Parameter Name="IsEnabled" Value="true"/>
    </Section>
```
I can see that a upgrade was performed on Tue, 13 Feb 2018 20:02:36 GMT
This is probably when the DnsService section was removed. Note that we are currently investigating a bug where portal removes DnsService section (among other things) from the manifest when upgrade is triggered.
You can enable DnsService again please follow the steps described here:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings
Just add the DnsService section above to the json document.

Milan

**Comment by mani-ramaswamy** [comment]
The fix to the bug has been rolled out already (which removed the DNSService when upgraded through the portal).

**Comment by eaglo** [comment]
hi thanks for the help, really appreciated! 

so i tried following the description, set the the explorer to read/write and added a new section in the fabricSettings like
```
      {
        "name": "DnsService",
        "parameters": [
          {
            "name": "IsEnabled",
            "value": true
          }
        ]
      }   
```
but unfortunately the ressource explorer didn't really change the configuration. it showed a green mark but did not add the new section :/

**Comment by virasana** [comment]
Where is the cluster manifest?

**Comment by jspuij** [comment]
Why was this closed? Stopping ICS is not really a nice workaround since it will disable internet for your VM's and ICS auto restarts on reboot. It also seems to restart based on schedule / triggered events, because when you leave your machine overnight, it will restart ICS.
Subsequently the service fabric DNS service will fail / try rebinding to port 53 until memory is exhausted. I had a FabricDnsService.exe consuming 32GB ram this morning after the weekend.

**Comment by oanapl** [comment]
@jspuij , in our incoming release, 6.2, you won't have to stop the ICS anymore, we fixed the sharing violation. 
We also have a fix for the memory leak (which didn't make it in 6.2 unfortunately). This bug only manifests when the service fails to start in a loop, so with the previous change you won't see it.

**Comment by tbertenshaw** [comment]
brilliant @oanapl  :)

**Comment by jspuij** [comment]
Thank you @oanapl for the info. Looking forward to the fixes.
