### ISSUE TITLE
Unable to load System.Fabric.Management.ServiceModel.dll if using MEF

### ISSUE THREAD

**Issue by wkit23** [Azure/service-fabric-issues#8]
If we use Service Fabric together with MEF Depedency Injection, when we create the AssemblyCatalog, the error "unable to load System.Fabric.Management.ServiceModel.dll" will be thrown.

We have tested version 5.0.217. The temporary workaround we had is to include this dll manually in our service fabric project.

**Comment by masnider** [comment]
Hi there, two questions (and sorry for not getting back to you sooner)
1) Can you try this again on a more recent version of the SDK?
2) Do you know if the SDK and runtime were actually present on that machine at the time? Asking since the file should be present. 

These days that file shouldn't be required, so I'm going to close this issue for now. If you're still having problems with it and can provide a repro, please reopen this and let us know (and sorry again for not providing an answer sooner).
