### ISSUE TITLE
Renew endpoint certificate

### ISSUE THREAD

**Issue by RaleS** [Azure/service-fabric-issues#805]
We have multiple services (using HttpSysCommunicationListener with HttpSys on 2016-Datacenter-Server-Core) that listen at HTTPS port configured with SSL certificate. The certificate is about to expire and we need to renew it. We have added the new SSL certificate (and not removed the existing) using the ARM template and we have verified that both certificates are deployed in the certificate store on the nodes. The applications are running using the old SSL certificate.

We have tried to change the thumbprint in EndpointCertificate section of ApplicationManifest and redeployed one of the applications. The application failed to start, but the other ones are still running.

How to renew/switch endpoint certificate without downtime? Do we have to switch it for all service simultaneously? If yes, how?

Executed on the node: netsh http show sslcert

Result...

 IP:port                      : 0.0.0.0:443
    Certificate Hash             : 87ceca59f7dc161489718201dd3cf5f26ad01713 <- old certificate
    Application ID               : {1879dfae-685a-4b26-a29d-27fdc7c617e0}
    Certificate Store Name       : My
    Verify Client Certificate Revocation : Disabled
    Verify Revocation Using Cached Client Certificate Only : Disabled
    Usage Check                  : Enabled
    Revocation Freshness Time    : 0
    URL Retrieval Timeout        : 0
    Ctl Identifier               : (null)
    Ctl Store Name               : (null)
    DS Mapper Usage              : Disabled
    Negotiate Client Certificate : Disabled
    Reject Connections           : Disabled

**Comment by RajeetN** [comment]
You cannot have a port shared across multiple applications because http.sys does not allow multiple certificates for the same port. So SF cannot upgrade cert for one application without causing a downtime for the other. So SF detects this condition and fails the upgrade. It is fine to have all services of the same app share the port though since SF will upgrade services of the same app together but cannot upgrade multiple apps together. The right way if you need to have multiple applications share a port is to have a "gateway" service that listens on a port and then routes the request to the appropriate service on the backend. 
At this point to get out of the situation, you will need to move services of other applications off the nodes and then do the upgrade.

**Comment by RaleS** [comment]
To renew the endpoint certificate without any downtime and without moving the services, (once we had added the new certificate to the keyvault and redeployed the cluster arm template containing the new certificate thumbprint) we had to remove the CertificateRef from all endpoints (except one) and redeploy the apps, leaving single app as is (we learned the hard way that removing the app would also remove the sslcert binding). This last app was used to replace the certificate.

We are currently looking into Api Management.

**Comment by RajeetN** [comment]
Sorry that you had to go through this issue. We will see what we can do to improve the experience here. Our documentation does call out this limitation:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security

**Comment by billysug** [comment]
That documentation has moved here:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade#upgrading-multiple-applications-with-https-endpoints

**Comment by starforce** [comment]
![image](https://user-images.githubusercontent.com/4247353/87742979-e8fb1b00-c7b5-11ea-956b-0d6f7ffd1d95.png)
