### ISSUE TITLE
I want to deploy standalone cluster on multimachine on-premise 

### ISSUE THREAD

**Issue by vi1996ash** [Azure/service-fabric-issues#839]
This is what i did
 1) in the configUnsecuredMultiMachine.json I edited machine ip.
 2) i disabled firewall
 3) enabled the remote service registry 
 this is my error screen shot  https://drive.google.com/open?id=13pzP5xW_SGjhjy6piGix9OElB2GoZ_3v

**Comment by alsantam** [comment]
This error is probably due to not having administrator privileges on each of the machines. Please make sure you have admin privileges on the deploying machines as described here (in the administrator privileges): 
[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation).

**Comment by vi1996ash** [comment]
Thank you for your reply. This was not actually the case, I was using windows 10 for this cluster that is why it was not working. when i switched to windows server it was working perfectly fine.
