### ISSUE TITLE
Visual Studio 2017 reporting Service Fabric Tools unresponsive

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-issues#843]
I'm using the latest VS 2017 preview (15.6.0 Preview 4.0)

Opening an existing solution and adding in a new .Net core 2.0 stateful service resulting in a warning appearing saying.

`Extension 'Service Fabric Tools 2.0.20181224.2' likely caused 7 seconds of unresponsiveness`

Everything appears ok, but I know you guys are really keen on improving Visual Studio performance, so I felt this was probably important.

**Comment by masnider** [comment]
Thanks for letting us know! Adding Devin and Ravi.

**Comment by dbreshears** [comment]
Thanks.  We have seen this in 15.6 Preview builds.   VS added some additional performance checks for extensions recently.   For our extension, we have seen it primarily occur after service project creation,  which we would expect to take a few seconds( or more in the case of asp.net core )  while the extension awaits the project creation.   We should have this fixed by the time 15.6 ships.
