### ISSUE TITLE
System Services Fail on Application Deployment

### ISSUE THREAD

**Issue by awcab** [Azure/service-fabric-issues#888]
I have a cluster running fine for a few weeks.  When I tried to upgrade the application, it failed.  I now see that the Failover Manage and Image Store services are both in error.  Any attempts to resolve this with powershell commands has failed.  As a result, I'm having to completely replace the cluster.
![sf_failure](https://user-images.githubusercontent.com/337839/36798769-5aa3f0dc-1c60-11e8-9e3c-a409ec9cb188.PNG)

**Comment by oanapl** [comment]
@awcab , let's try to fix the cluster so you don't have to replace it.
Can you give me a few more details:
- Is this a local cluster / Azure cluster / standalone? 
- How many nodes are in the cluster? Are they all healthy?
- How big is your application (in terms of services, partitions, replicas)? Is the cluster overloaded?
- How did the application upgrade fail? Was it because of health? Did it rollback? Note that System app health won't directly impact your app upgrade.
- The screenshot shows that one of the FM replicas is down. If you dig in the health at replica level, is there any other health information there?
- Does the ImageStoreService have the same issue (one replica down, so it's below target)?

**Comment by awcab** [comment]
That would be great!

- It's a local cluster
- 3 healthy nodes
- Just 1 service.  Stuck on deleting and unknown state
- I'm not sure
- The Active Secondary is reporting the following:

> Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on _svworker_0. -2147017517 For more information see: http://aka.ms/sfhealth
> --

- Yes

**Comment by awcab** [comment]
Oh - I set up a 3 node with bronze availability for development purposes.  I wasn't aware this wasn't supported.  And sorry!  I just realized that I said local cluster.  It absolutely isn't - this is running on Azure.

**Comment by oanapl** [comment]
If this is Azure cluster, can you look on the VMs (starting with _svworker_0) to see if there is enough disk space?
If that's not the issue, you can check the event log on _svworker_0 to see if there's something that can help figure out why the store error happens. 
Is the image store service replica that is down also on _svworker_0? If so, you can try restarting that node (you can do it through SFX).

**Comment by awcab** [comment]
The vm is out of disk space on my application partition.  Is this the same disk used for the system services?  If so, that makes sense.  I would've expected these to be isolated.

**Comment by oanapl** [comment]
They are not. Can you make some space on the VM and see if the replicas can open successfully?

**Comment by oanapl** [comment]
@awcab , I haven't heard back from you. I hope cleaning the disk helped the replica to open successfully.
I will close the issue, if you are still having trouble, feel free to re-open or open another issue.
