### ISSUE TITLE
Vanilla template Stateful service Asp.net Core not working version 6.1.480

### ISSUE THREAD

**Issue by francescocristallo** [Azure/service-fabric-issues#969]
I formatted my PC, reinstalled VS2017 on Windows 10 x64 (English International), imported my project and the stateful services were not working anymore. Meanwhile the Refresh 3 came out, I installed it.
Couldn't make the Stateful services work in any way in the local cluster. The stateless works just fine.

I created a new project with an Empty Stateful Asp.net Core service and is not working.
To replicate the problem:

File => New Project => Service Fabric Application => Stateful Asp.net Core => Empty => Debug

Launch debug, the error is:

**`The service host terminated with exit code: 2148734499`**

The local cluster mode is 1 Node.

You seriously need to put more info in there, every update there is something not working, packaging not restoring or new errors popping up without explanation.
I'm stuck in development until I figure out why even a zero code app is not working.

<img width="1877" alt="1" src="https://user-images.githubusercontent.com/9793825/38449809-3224e5b6-39da-11e8-8021-19e5fdd15d71.PNG">

<img width="1820" alt="2" src="https://user-images.githubusercontent.com/9793825/38449810-33aadf8a-39da-11e8-9c2e-4b2012648a12.PNG">

TESTS:
1) Tried with 5 Nodes mode type with same error.
2) Used the Stateful service template (Non the Asp.net Core one), same errors:

<img width="1856" alt="capture" src="https://user-images.githubusercontent.com/9793825/38450160-db84e3b4-39de-11e8-8ddb-e3e315c28d10.PNG">

<img width="1837" alt="4png" src="https://user-images.githubusercontent.com/9793825/38450151-b0e29084-39de-11e8-870a-13ef9bc34c65.PNG">

What is exit code: 2148734499? 

How do I solve this? Why it's happening on a New project without any modification?

**Comment by francescocristallo** [comment]
I'm using SDK 3.0.480
I think this is related to #619

**Comment by hrushib** [comment]
@francescocristallo, as mentioned in earlier incidents this mainly happens due to known issue with CoreCLR dotnet/coreclr#12668 on non en-us version of Windows 10 which results in Stateful service process crashing with -2146232797, refer to #619 for details.

This issue is fixed in 2.0.3 version of coreclr, so you can use this version or higher to get your code running without the above work around. To make sure that you use 2.0.3 (or higher) add below line in your csproj under properties. 
`<RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>`

@dbreshears, we should update templates to include above line in csproj. 

Closing this issue, given that @francescocristallo unblocked him using the workaround and this reply answers his his question on why this happens.
