### ISSUE TITLE
Deployment fails when nodes are in an error state

### ISSUE THREAD

**Issue by Telavian** [Azure/service-fabric-issues#973]
5 node cluster
6.1.472.9494

During development I have sometimes deployed and seen various errors on startup. Most of the times these errors were related to my code which I immediately fix and deploy again.

However it seems if the nodes are in an error state then the deployment has a hard time removing the old and then updating with the new. Almost always there is a timeout during the removal portion.

The only reliable fix I have is to do a "Taskkill" for every process I deploy, wait 5 seconds, see them restart, and then kill them again. This seems to remove the process and then the SF removal works as expected.

However if the nodes are in a healthy state then removal goes much faster without problems.

**Comment by masnider** [comment]
Are the _nodes_ unhealthy (ex: down, or have some specific health error reported against them), or is it the application/service that has the error?

**Comment by Telavian** [comment]
It is the app specifically.

**Comment by masnider** [comment]
For this then you should be able to use the [-ServiceTypeHealthPolicyMap](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-health-introduction) option to mask out the health of the unhealthy service. There's also manual upgrade options where you push the upgrade through at your desired pace, but most of the time we'd expect people to control the pace via the more common [upgrade parameters](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-parameters).

What may also be happening is that your service isn't shutting down cleanly/quickly due to the bug, so SF is trying to gracefully close things and it's taking a long time (since by default we give the service pretty much as much time as it wants). On the whole it's best to avoid these kinds of bugs by doing chaos or lifecycle tests before deploying into real clusters. 

@oanapl in case she has other ideas.

**Comment by masnider** [comment]
@Telavian were you able to determine whether these additional parameters were helpful?

**Comment by Telavian** [comment]
Thank you for following up.

I actually have not tried it yet however I will.
You say to avoid these kinds of bugs which I would love to do. However I can't know it is a bug until I deploy and run it to see the problem.

To keep things clean you can close this and then if I have issues I will open a new issue.
