### ISSUE TITLE
Multi region service fabric node placement

### ISSUE THREAD

**Issue by govjobss** [Azure/service-fabric-issues#979]
Hi, as per https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-disaster-recovery service fabric support multi region but i m not able to find how can i place nodes / vnets to cover multi region support for service fabric cluster so that the cluster will be available in case of disaster in one region (very unlikely but still want to know option).

if this is not possible then do we have any other option for service fabric DR in case of region/datacenter failure?

**Comment by masnider** [comment]
[Here's ](https://github.com/ChackDan/Service-Fabric/tree/master/ARM%20Templates/Multi%20Region%20Spanning%20Sample) an example. It's not fully fleshed out (you should probably not have node types that span all the regions, but you can set up placement constraints so that your workloads end up spanned (NodeType == NT1 || NodeType == NT2).

**Comment by masnider** [comment]
Hi there @govjobss . Hopefully we've answered your question. The original doc describes the different disaster recovery options, including how to handle multiple separate clusters. Since we haven't heard back from you in a while I'm going to close down this issue. If you have further questions on this topic, just reopen the issue and let us know.
