### ISSUE TITLE
Question - replicatorshared text file size is around 8GB

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#999]
Team,

One of node in cluster has replicatorshared file in SF data folder size of around 8GB.
could you let me know what is purpose of this file ?

i see below issue in SF explorer sometime as warning but this goes away.
All nodes are healthy in SF Explorer.

The Data Collection Agent (DCA) does not have enough disk space to operate. Diagnostics information will be left uncollected if this continues to happen.

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
is there way to limit/configure size of this file ? 
i can see file size is around 8GB in all nodes in cluster.

**Comment by AlanWarwick** [comment]
The replicatorshared.log file is temporary log space for all stateful reliable collection applications that run on that node. The size of the file is determined by a value in the cluster manifest and once the file is created, it is not resized. You can do a configuration update that will change the size of file if it ever needs to be created in the future.

Take a look at this: https://github.com/Azure/service-fabric-issues/issues/138

**Comment by MichalKoscielniak** [comment]
@AlanWarwick does it mean that in order to change the actual file size - i need to re-create the cluster ? What if i need to do it on my production cluster ? I can't afford recreating it ( can't afford downtime ). What is the reason behind this file not being changeable ?

**Comment by AlanWarwick** [comment]
There is a roundabout way to change the replicatorshared.log file size. 

1. Perform a config upgrade and change the KtlLogger settings to reflect the new file size.
2. Add a new node to the cluster and move all services from an old node to this new node. The replicatorshared.log will be recreated with the new size.
3. Remove the old node.
4. Repeat for all nodes in the cluster.

The replicatorshared.log file has temporary log data and metadata for all of the stateful services on the node. Recreating the file would be very disruptive as the data would be lost. Resizing is also problematic since the log data is written as a circular buffer so it would not be safe to just truncate the file.

I do have a work item on my list to investigating allowing resizing of this log file but not timeline that I could share.

**Comment by MichalKoscielniak** [comment]
Thank you @AlanWarwick for such a quick response. It would be very useful to be able to do this ( accepting the fact the data loss ). In our case we are not using Stateful Services at all, so there would be no harm in that.
